CHANGELOG.md, package.json
Update changelog and version in package.json for submit job functionality
=> Update changelog for submit job functionality

CHANGELOG.md, package.json, scripts/systemTestEnv.ts, src/DatasetTree.ts
Needed to update zowe CLI core and imperative and a few small changes
=> Fix issue with loading password 

CHANGELOG.md, package.json
Published 0.9.0 just now. This PR just updates package.json and changelog.md
=> update changelog and version for informational message

.vscode/settings.json, CHANGELOG.md, README.md, package.json
Fix 2 links to point to current documentation (install and create profiles).
=> Fix links to documentation

CHANGELOG.md, package.json, src/extension.ts
Needed to test it's a USS file before saving file
=> USS File needs to be checked

CHANGELOG.md, package.json, src/extension.ts
Add more log messages for saving data sets
=> add more log messages

CHANGELOG.md, package.json
Update changelog for USS binary mode toggling and README gifs
Signed-off-by: boech02 <christopher.boehm@broadcom.com>
=> bump version and update changelog

dco_signoffs/Colin Stone-vscode-extension-for-zowe.txt
=> Colin Stone-DCO text

CHANGELOG.md, package.json
Should we push this version to market place also?.
=> Bump version number

CHANGELOG.md, package.json
=> Allow submitting jcl from physical sequential data sets

package.json
=> Bump version for spool changes

CHANGELOG.md, package-lock.json, package.json
=> Request publish 0.21.0

__tests__/extension.test.ts, package-lock.json, package.json, src/extension.ts
Implements current MVS features in USS. Addresses issue #49.
=> Add USS File Refresh and USS Safe Save

__tests__/extension.test.ts, src/extension.ts
Uses the recently provided command to open files taking consideration of the files indicated tagged state.
=> Include chtag

__tests__/extension.test.ts, __tests__/uss/ussNodeActions.test.ts, package.json, src/extension.ts, src/uss/ussNodeActions.ts
=> USS file upload through dialog

__tests__/mvs/mvsNodeActions.test.ts, package.json, src/mvs/mvsNodeActions.ts
Signed-off-by: KRISTINA MAYO <ktopchi@us.ibm.com>
=> Add ability to upload in the favorites section

CHANGELOG.md, package-lock.json, package.json
- Add ability to create directories or files on the root node. Thanks to @kristinochka
- Add ability to upload files through regular OS browse dialog on regular nodes and favorites. Thanks to @kristinochka
- Add USS File Refresh and USS Safe Save. Thanks to @adambattenburg
- Honor the file tag (binary or ascii) if not specified. Thanks to @Colin-Stone
=> Publish 0.22.0

__tests__/jes/jesNodeActions.test.ts, src/extension.ts, src/jes/jesNodeActions.ts
Signed-off-by: KRISTINA MAYO <ktopchi@us.ibm.com>
=> Set jes-jcl language type on spool files for syntax highlighting

__tests__/extension.test.ts, src/extension.ts
https://github.com/zowe/vscode-extension-for-zowe/issues/105
=> Dataset suffix

src/extension.ts
Addresses zowe/vscode-extension-for-zowe#146
Many thanks to my teammate Prasang for his help in tracking the issue down!
Signed-off-by: Lauren Li <Lauren.Li@ibm.com>
=> Fix activation error

CHANGELOG.md, __tests__/__unit__/extension.unit.test.ts, package.json, src/extension.ts
=> Remove default suffix

src/extension.ts
Windows machines can lowercase
=> Fix for unable to save datasets - Upper case for Datasets 

CHANGELOG.md, package-lock.json, package.json
Fix #165
The code for the fix is in #166
=> Publish fix for 165

src/extension.ts
=> Fix data set attributes display - use color:false when calling TextUtils.prettyJson - Fix #173

__tests__/__unit__/SpoolProvider.unit.test.ts, __tests__/__unit__/extension.unit.test.ts, package-lock.json, src/SpoolProvider.ts, src/extension.ts
=> Fix up tests

CHANGELOG.md, package-lock.json, package.json
=> Bump version 0.24.0

__tests__/__unit__/extension.unit.test.ts
Updated tests failed linter. Doh!.
=> Lint updates to modified tests

i18n/sample/src/extension.i18n.json
Signed-off-by: Lauren Li <Lauren.Li@ibm.com>
=> Update extension i18n file

__mocks__/vscode.ts, __tests__/__integration__/extension.integration.test.ts, src/extension.ts
Signed-off-by: Peter Haumer <phaumer@us.ibm.com>
=> Automatically detecting extension runs in Theia

i18n/sample/package.i18n.json, i18n/sample/src/DatasetTree.i18n.json, i18n/sample/src/USSTree.i18n.json, i18n/sample/src/extension.i18n.json, i18n/sample/src/uss/ussNodeActions.i18n.json
=> New translation samples

src/ZoweNode.ts
Signed-off-by: Lauren Li <Lauren.Li@ibm.com>
This is addresses issue #136 as part of the larger refactor for MVS favorites node naming.
It seems Colin is in the middle of refactoring several functions that MVS favorites use. This PR should not affect his work there, but I think it may be prudent to wait until he has finished his refactoring before doing additional work for this issue.
=> Specify tooltip definition for MVS

__tests__/__unit__/__snapshots__/extension.unit.test.ts.snap, package.json
Fixes: https://github.com/zowe/vscode-extension-for-zowe/issues/252
=> Fix edit context on search

Jenkinsfile, package.json
On every new release (major, minor or patch) the pipeline will create a tag and push it to the repository.
Fixes #207
=> Add release tags

CHANGELOG.md, i18n/sample/package.i18n.json, package-lock.json, package.json, package.nls.json, src/DatasetTree.ts, src/USSTree.ts, src/ZosJobsProvider.ts
Incremented version for next release. Updated pacakage-lock file
=> Version 0.26.0 updates and some rewording ready to be published

.codecov.yml, Jenkinsfile
- Added webhook directly from Codecov.io
- Added token to the Jenkins server
- Added codecov.yaml file to specify the 90+% coverage
- Added step in the pipeline to upload most recent Coverage results
- Not sure what happens to the history when branches get created and PRs immediately after
Fixes #291 
=> Implement Codecov

__mocks__/@brightside/core.ts, __tests__/__unit__/DatasetTree.unit.test.ts, __tests__/__unit__/ZoweNode.unit.test.ts, __tests__/__unit__/__snapshots__/extension.unit.test.ts.snap, package-lock.json, package.json, src/ZoweNode.ts, src/extension.ts, src/utils.ts
Signed-off-by: Colin Stone <30794003+Colin-Stone@users.noreply.github.com> Although not a GA specific item this provides the UI context for the migrate functional updates that @Pranay154 is working on.
Applied extra testing for coverage purposes
=> Handle migrated context. Increase testing

__tests__/__unit__/Profiles.unit.test.ts, src/Profiles.ts
Fixes https://github.com/zowe/vscode-extension-for-zowe/issues/307
=> Update URL Parsing

README.md
Signed-off-by: Igor Kazmyr <43951184+IgorCATech@users.noreply.github.com>
=> add a link to z/OSMF pre-reqs

__tests__/__integration__/extension.integration.test.ts, __tests__/__unit__/__snapshots__/extension.unit.test.ts.snap, __tests__/__unit__/extension.unit.test.ts, i18n/sample/package.i18n.json, package.json, package.nls.json, src/extension.ts
=> feat: rename data set member

__tests__/__unit__/DatasetTree.unit.test.ts, i18n/sample/src/DatasetTree.i18n.json, src/DatasetTree.ts
Signed-off-by: jellypuno <jessielaine.punongbayan@broadcom.com>
=> add try catch on loadnamedprofile during initialization

package-lock.json, package.json
=> Update package json files

CHANGELOG.md, package-lock.json, package.json
=> Publish a 1.0.1 version

README.md
Signed-off-by: Igor Kazmyr <43951184+IgorCATech@users.noreply.github.com>
=> add the develop for Eclipse Theia link

README.md
Resolves issue #416 
Signed-off-by: MikeBauerCA <35504792+MikeBauerCA@users.noreply.github.com>
=> Fix Issue #416

__tests__/__unit__/extension.unit.test.ts, src/Profiles.ts, src/extension.ts
Signed-off-by: jellypuno <jessielaine.punongbayan@broadcom.com>
=> Fix Issue 413 according to comments

CHANGELOG.md, i18n/sample/src/Profiles.i18n.json, package.json
=> Update version information v1.1.0

package-lock.json
Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>
=> Update @brightside/core dependency to fix vulnerability

.gitignore, __tests__/__unit__/DatasetTree.unit.test.ts, __tests__/__unit__/extension.unit.test.ts, __tests__/__unit__/uss/ussNodeActions.unit.test.ts, package-lock.json, package.json, src/uss/ussNodeActions.ts
Updated gitignore with system  folder of WebStorm. Added isBinary lib for checking of files. Added handling for binary files when user tries to upload them.
=> Fix - Issue#244

Jenkinsfile
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>
Getting ready for v1.2.1
=> Add variable for full name of release VSIX

src/extension.ts
=> checks for undefined node

__tests__/__integration__/extension.integration.test.ts, __tests__/__unit__/DatasetTree.unit.test.ts, __tests__/__unit__/USSTree.unit.test.ts, __tests__/__unit__/ZoweJobNode.unit.test.ts, __tests__/__unit__/extension.unit.test.ts, package-lock.json, src/DatasetTree.ts, src/USSTree.ts, src/ZosJobsProvider.ts, src/extension.ts
=> Fix issue 485

Jenkinsfile
=> fix v1.2 jenkinsfile

__tests__/__unit__/extension.unit.test.ts, i18n/sample/src/extension.i18n.json, src/ImperativeInit.ts, src/extension.ts
=> Ph fix 514 spawn

CHANGELOG.md, package.json
Apologies for taking this long.
=> Ready for 1.2.2

__tests__/__unit__/Profiles.unit.test.ts, __tests__/__unit__/extension.unit.test.ts, package-lock.json, src/Profiles.ts, src/extension.ts
Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>
Fix #514 Without spawning a process
=> Don't require ~/.zowe folder to exist

__mocks__/@zowe/imperative.ts, __tests__/__unit__/KeytarCredentialManager.unit.test.ts, __tests__/__unit__/ZoweJobNode.unit.test.ts, i18n/sample/src/extension.i18n.json, package-lock.json, src/KeytarCredentialManager.ts, src/extension.ts
Ports the change in PR #531 to master for v1.3.0 of the extension.
=> Port #531 to Master

src/extension.ts
=> await needed on CredentialManagerFactory.initialize

CHANGELOG.md, package.json
=> Version Bump v124

CHANGELOG.md, package.json
=> Version 1.3 updates

Jenkinsfile, package-lock.json, package.json
This should help going forward when maintaining the pipeline and other automation processes. :smile:
- Added a few dev-dependencies to help with reporting purposes.
- Captured test results on every build
- Removed "Smoke Test" stage to leverage the `archiveOperation` on the shared pipeline library
- Combined `Public` and `Release` stages into a single `Publish stage in order to remove duplication
- Added a TODO item related to #556 
Fixes #456
=> Introduce the library to the Zowe Explorer

src/DatasetTree.ts, src/ZosJobsProvider.ts
Signed-off-by: Colin Stone <30794003+Colin-Stone@users.noreply.github.com>My apologise for causing this.. 
Would you be okay reviewing please as it will get everyone running again
=> reset filter prompt

src/extension.ts
fixes #595
fixes #596
Signed-off-by: Alexandru-Paul Dumitru <alexandru.dumitru@broadcom.com>
=> bug fix for triggering uploading of USS files and using correct Interface in saveFile()

__tests__/__integration__/dataset/dsNodeActions.integration.test.ts, __tests__/__integration__/job/jobNodeActions.integration.test.ts, __tests__/__integration__/uss/ussNodeActions.integration.test.ts, __tests__/__unit__/ZoweNode.unit.test.ts, __tests__/__unit__/ZoweUSSNode.unit.test.ts, __tests__/__unit__/command/mvsCommandHandler.unit.test.ts, __tests__/__unit__/dataset/dsNodeActions.unit.test.ts, __tests__/__unit__/extension.unit.test.ts, __tests__/__unit__/job/jobNodeActions.unit.test.ts, __tests__/__unit__/uss/ussNodeActions.unit.test.ts, i18n/sample/src/extension.i18n.json, src/Profiles.ts, src/ZoweUSSNode.ts, src/dataset/dsNodeActions.ts, src/extension.ts, src/job/jobNodeActions.ts, src/uss/ussNodeActions.ts, src/utils.ts
Prepare for a v1.3.1 release :smile:
=> Prepare v1.3.1

src/uss/ussNodeActions.ts
Fixes regression that bypassed the API registry
=> Fix uploadBinaryFile redirection

__tests__/__unit__/extension.unit.test.ts, __tests__/__unit__/utils/workspace.unit.test.ts, src/extension.ts, src/utils/workspace.ts
- Cherry-picked merge-commit
- Removed unnecessary imports
=> Port fix 589 into v1.3.x

__tests__/__unit__/utils/workspace.unit.test.ts, src/utils/workspace.ts
Missing license info. Please merge before https://github.com/zowe/vscode-extension-for-zowe/pull/613
=> Added license info

src/ZoweUSSNode.ts, src/uss/ussNodeActions.ts
Added fix for incorrect renaming of USS folder.
=> Issue #616

CHANGELOG.md, i18n/sample/src/extension.i18n.json, package-lock.json, package.json
Update changelog and version numbers
=> Ready for 1.4.0 release

src/extension.ts
Signed-off-by: Peter Haumer <4391934+phaumer@users.noreply.github.com>
=> Emergency fix for USS files do not get saved (Issue #660)

__tests__/__unit__/shared/context.unit.test.ts, i18n/sample/src/dataset/actions.i18n.json, src/dataset/DatasetTree.ts, src/dataset/ZoweDatasetNode.ts, src/dataset/actions.ts, src/dataset/dsNodeActions.ts, src/dataset/utils.ts, src/job/ZosJobsProvider.ts, src/job/actions.ts, src/shared/actions.ts, src/shared/context.ts, src/uss/USSTree.ts, src/uss/ZoweUSSNode.ts, src/uss/actions.ts
Signed-off-by: Colin Stone <30794003+Colin-Stone@users.noreply.github.com> Adds more regular expression testing that was lost
=>  Additional regexp tests

Jenkinsfile, package-lock.json, package.json
Here is the working pipeline build: 
https://wash.zowe.org:8443/blue/organizations/jenkins/zowe-cli-vscode-extension/detail/v1.5.x/16/pipeline/147
=> Allow changelog to have single quotes

CHANGELOG.md, package-lock.json, package.json, src/Profiles.ts
I couldn't make @JillieBeanSim a reviewer. (EDIT: GH wouldn't let me, not sure why)
My apologies
=> Fixes for 1.5.2

CHANGELOG.md, Jenkinsfile, package-lock.json, package.json
Before closing the 1.6 milestone and releasing, we need to make sure that all fixes and security patches have been properly applied to master, as well as changelog updates from the hot fixes released after v1.5.0 went out.
Milestone: 1.6
Changelog: Update `changelog` and `package-lock.json`
=> docs: updates from v1.5.2

CHANGELOG.md, package-lock.json, package.json
Changelog for v1.7.0
Milestone:
Changelog:
=> Doc: Changelog for v1.7.0

__mocks__/mockCreators/datasets.ts, __mocks__/mockCreators/uss.ts, __tests__/__integration__/DatasetTree.integration.test.ts, __tests__/__unit__/Profiles.unit.test.ts, __tests__/__unit__/dataset/DatasetTree.unit.test.ts, __tests__/__unit__/dataset/actions.unit.test.ts, __tests__/__unit__/dataset/dsNodeActions.unit.test.ts, __tests__/__unit__/shared/actions.unit.test.ts, __tests__/__unit__/uss/USSTree.unit.test.ts, src/PersistentFilters.ts, src/Profiles.ts, src/__mocks__/USSTree.ts, src/abstract/ZoweTreeProvider.ts, src/api/IZoweTree.ts, src/command/MvsCommandHandler.ts, src/dataset/DatasetTree.ts, src/dataset/actions.ts, src/job/ZosJobsProvider.ts, src/shared/actions.ts, src/uss/USSTree.ts, src/uss/ZoweUSSNode.ts
Signed-off-by: Katelyn Nienaber <katelyn.nienaber@broadcom.com>
Changing the names of the functions in PersistentFilters in a separate PR, as requested by Vit on [this PR](https://github.com/zowe/vscode-extension-for-zowe/pull/920).
I changed the names because having "history" and "recall" arrays in the settings file is not clear. So "history" is changed to `searchHistory` and "recall" is changed to `fileHistory` because those are the types of items stored in each array...search strings and file paths.
Also I reordered the functions in the file so that similar functions for each persistent array are grouped together (ie. getSearchHistory grouped with getFileHistory/getFavorites, etc.)
Milestone: 1.8
Changelog: Changed names of history and recall functions in PersistentFilters to …
=> Changing names of functions in PersistentFilters

src/shared/utils.ts, src/uss/actions.ts
https://github.com/zowe/vscode-extension-for-zowe/issues/928
Pass etag to putContent()/putContents() so if the file has changed on the mainframe while editing with zosmf profile the etag compare should not match and the compare pop up should show allowing the user to overwrite what's on the host or not.
Milestone:
1.7.x or 1.8.0
Changelog:
Bug Fix: Pass etag as to not automatically overwrite changes between local and the mainframe.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist …
=> Issue 928 bug fix USS Save

__tests__/__unit__/Profiles.unit.test.ts, i18n/sample/src/Profiles.i18n.json, src/Profiles.ts
https://github.com/zowe/vscode-extension-for-zowe/issues/921
User will be notified that the profile is being validated during validation
Milestone:
1.7.x or 1.8
Changelog: 
Alert user to validation of profiles
=> Issue921 validation information

CHANGELOG.md, README.md, __tests__/__unit__/Profiles.unit.test.ts, i18n/sample/src/Profiles.i18n.json, package-lock.json, package.json, src/Profiles.ts, src/shared/utils.ts, src/uss/actions.ts
Publish version 1.7.1 with the agreed fixes/enhancements
Milestone: 1.8.0
Changelog:
- Fix USS save operation. Thanks @JillieBeanSim
- Add validation information message. Thanks @JillieBeanSim
- Restructure Readme. Thanks @IgorCATech
=> HotFix: v1.7.1

src/abstract/ZoweTreeProvider.ts
Fixes issue #944 (Validate profile error message replaced by "Failed to load message bundle" message)
Error message now shows as expected:
Milestone: 1.8
Changelog: (This is a fix for an issue on master branch; thus, I don't believe it needs its own Changelog entry.)
N/A
=> Fix: Use nls message bundle instead of file format

.github/workflows/theia-zowe-explorer-ci.yml, .github/workflows/zowe-exlorer-ci.yml
Signed-off-by: Dan Kelosky <dkelosky@gmail.com>
This reduces the amount of times codecov and `npm audit` are done to avoid using the backend APIs and having requests be rejected.
Milestone:
Changelog:
=> fix: limit API requests to codecov and npm audit

.github/workflows/theia-zowe-explorer-ci.yml
Signed-off-by: Dan Kelosky <dkelosky@gmail.com>
Renames the build for theia pipeline to `theia-build` so that the status check is more descriptive than just `build`:
Milestone:
Changelog:
=> feat: run status checks on pr

__tests__/__unit__/ZoweExplorerExtender.unit.test.ts, package-lock.json, src/dataset/actions.ts
Signed-off-by: Katelyn Nienaber <katelyn.nienaber@broadcom.com>
Quick fix for error when deleting data set nodes
Milestone: 1.9
Changelog: Fixed issue with deleting data set nodes.
=> Issue #963: Delete node doesn't work

CHANGELOG.md, package-lock.json, package.json
Signed-off-by: Zachariah Mullen <zachariah.mullen@broadcom.com>
Update the changelog for 1.8.
Milestone:
Changelog:
=> Update changelog for 1.8 release

CHANGELOG.md
Update master with v1.7.x fixes
Milestone: 1.8.0
Changelog:
=> Pull v1.7.x

CHANGELOG.md, README.md, package-lock.json, package.json
Signed-off-by: Igor Kazmyr <43951184+IgorCATech@users.noreply.github.com>
This PR updates both ReadMe and Changelog with 1.9.0 release notes. 
Milestone: 1.9.0
=> Update the Readme and Changelog docs. Zowe Explorer 1.9.0 release

README.md
Signed-off-by: Igor Kazmyr <43951184+IgorCATech@users.noreply.github.com>
Minor fixes: 
TOC fix + adding one more release note.
=> Fix ZE 1.9.0 TOC 

__tests__/__unit__/Profiles.unit.test.ts, __tests__/__unit__/api/ZoweExplorerZosmfApi.unit.test.ts, __tests__/__unit__/profiles/utils.unit.test.ts, src/Profiles.ts, src/abstract/ZoweTreeProvider.ts, src/api/ZoweExplorerZosmfApi.ts, src/command/MvsCommandHandler.ts, src/dataset/DatasetTree.ts, src/dataset/actions.ts, src/job/ZosJobsProvider.ts, src/job/actions.ts, src/profiles/utils.ts, src/shared/actions.ts, src/uss/USSTree.ts, src/uss/actions.ts, src/utils.ts
=> Base profile billie

__tests__/__unit__/Profiles.unit.test.ts, src/Profiles.ts, src/abstract/ZoweTreeProvider.ts, src/command/MvsCommandHandler.ts, src/dataset/DatasetTree.ts, src/dataset/actions.ts, src/job/actions.ts
=> Handle single base profile revert

__mocks__/mockCreators/shared.ts, __tests__/__theia__/extension.theia.test.ts, __tests__/__unit__/Profiles.unit.test.ts, __tests__/__unit__/dataset/DatasetTree.unit.test.ts, __tests__/__unit__/job/ZoweJobNode.unit.test.ts, __tests__/__unit__/shared/utils.unit.test.ts, __tests__/__unit__/uss/USSTree.unit.test.ts, __tests__/__unit__/uss/ZoweUSSNode.unit.test.ts, __tests__/__unit__/uss/actions.unit.test.ts, i18n/sample/src/Profiles.i18n.json, package-lock.json, package.json, src/Profiles.ts, src/abstract/ZoweTreeProvider.ts, src/api/ZoweExplorerApi.ts, src/api/ZoweExplorerZosmfApi.ts, src/dataset/DatasetTree.ts, src/job/ZosJobsProvider.ts, src/uss/USSTree.ts, src/uss/actions.ts
This is the MVP for loading base profiles in Zowe Explorer. 
The goal of this PR are the following:
- Load the default base profile (internally)
- Allow Service Profiles that uses base profiles to work in Zowe Explorer
Milestone:
Changelog:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …
=> Feat: MVP for handling default base profiles

README.md
Signed-off-by: Zachariah Mullen <zachariah.mullen@broadcom.com>
Add information about how to log in via the API ML and then leverage base profile and token in Zowe Explorer. 
1.10
Milestone:
Changelog:
=> Update readme 1.10

src/Profiles.ts
Issue #1055
Update tokenType & tokenValue command args to keep the order of precedence consistent between service profile and base profile in Zowe Explorer.
Use Cases:
In Zowe Explorer, service profiles generally take precedence over base profiles, However:
1. If a user has an alternate profile type which has the capability to authenticate with it's server via JWT token and the user has a base profile that may just store host, username, password but not a token. The token will be overwritten to an undefined value.
2. This will also occur if the base profile has a token for other profile types that may be behind the API ML but this particular profile type (the alt profile) isn't behind the API ML therefore it …
=> Issue 1055: Keep order of precedence with service & base profiles for token information

CHANGELOG.md, package-lock.json, package.json
See #1055 for details 😋 
Thanks @JillieBeanSim 👍 
Milestone:
Changelog:
=> Prepare v1.10.1 Release

.github/workflows/theia-zowe-explorer-ci.yml
Make Theia tests run and pass.
Disables artifact upload because the name of the vsix is no longer stable - requires a separate fix.
Milestone:
Changelog:
=> Fix Theia Pipeline

.github/workflows/theia-zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ci.yml
Add fixes for Zowe Explorer CI Github Actions
Milestone:
Changelog:
=> Fix: Github Actions for Explorer

.github/workflows/zowe-explorer-ci.yml
Update `yarn audit` command to:
1. Only scan for vulnerabilities in the `dependencies` group
2. Show a table representation of all severity categories (e.g. info, low, med, high) since the `--level` option doesn't not affect the exit code and low vulnerabilities will result in a failing run anyways. 😋 
Milestone: 1.11 ?
Changelog: Update `yarn audit` command
This PR could be merged before #1064 (Hoping to remove any vuln-check errors in the …
=> Update audit command

packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
This PR will fix spike #1094. As per investigation, ZE is passing ru=true because of how it is coded in the API. I changed it  and now it is fixed 😄 
Milestone:
Changelog:
=> Fix: Change RU to fix the spike

packages/zowe-explorer/theia_tests.Jenkinsfile
Signed-off-by: Jack (T.) Jia <jack-tiefeng.jia@ibm.com>
Part of fixes for https://github.com/zowe/zlc/issues/199.
The label is pointed to exactly same Docker image hash but different image name to remove word `slave`.
=> update build agent

.vscode/launch.json, .vscode/tasks.json
The VS Code FTP extension launcher was originally just watching the zowe-explorer package. This PR adds a separate watcher for the FTP extension to use, so developers working on the FTP extension can view their changes in the Extension Development Host.
- **Test:** Make some changes to the FTP extension (for example, edit a string), and run the FTP extension in the Extension Development Host to see that those changes manifest.
- **Test for regressions:** Make some changes to Zowe Explorer (zowe-explorer package), and run Zowe Explorer in the Extension Development Host to see that those changes manifest.
(If you'd like, you can paste the line `vscode.window.showInformationMessage("Testing PR 1105");` in the respective package's `activate` function for an easily viewable test change that …
=> Update FTP extension launcher to watch FTP package

package.json, packages/zowe-explorer/CHANGELOG.md
Signed-off-by: Zachariah Mullen <zachariah.mullen@broadcom.com>
Preparation for the 1.11.0 release
- package.json at top level updated with new version
- changelog.md updated with changes
Milestone: 1.11
Changelog:
=> Preparing for release

.github/workflows/deployment.yml, package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
Updates to change logs and package versions to prepare for 1.11.1 release.
Milestone: 1.11.1
Changelog:
=> Prepare for 1.11.1 release

README.md, package.json, packages/zowe-explorer/CHANGELOG.md
Signed-off-by: Richelle Anne Craw <richelleanne.craw@broadcom.com>
Preparation for the 1.12.0 release
- package.json at top level updated with new version
- release notes added to top level readme
- changelog.md updated with changes
Milestone: v1.12.0
Changelog:
=> Preparing for v1.12 release

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Preparation for v1.12.1 release
Milestone:
Changelog:
=> Changes for v1.12.1 release

packages/zowe-explorer/src/Profiles.ts
This PR fixes the issue with Credentials are not prompted and login is not supported for some profiles
Milestone: 1.13.0
Changelog: Bug fix for merging of base profiles with service profiles where ports didn't match.
=> issue 1190: Prompted vs APIML login

packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json, packages/zowe-explorer/src/dataset/DatasetTree.ts
I moved the resetting of child & member pattern into it's own loop then added a check for an existing pattern in the assignment loop as to not overwrite a previous pattern added
As it is now 1.12.1
This PR
Milestone: 1.13.0
Changelog: bug fix for multi data set filter search with member pattern, second search pattern overwriting the first.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
=> Issue 1210: Member filter refinement

packages/zowe-explorer/src/shared/actions.ts
Ctrl+Alt+R allows you to use the "Open Recent Files" functionality. This currently has a bug and this PR fixes it. The issues is because the sessionName in  fileHistory settings are set to Uppercase. 
Milestone:
Changelog:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …
=> Hot fix: Recent open files

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> Prepare for 1.13.0 release

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md
A release notes update for Zowe Explorer 1.13.1. Changes are made to the ZE ReadMe and Changelog.
Milestone: 1.13.1
Changelog:
=> (Doc) Update Zowe Explorer 1.13.1 RNs

package.json, packages/zowe-explorer-api/package.json, yarn.lock
Bumping the CLI version to 6.30
Milestone:
Changelog:
=> Fix: Bump CLI to 6.30

packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpJesApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts, packages/zowe-explorer-ftp-extension/src/abstractFtpApi.ts, packages/zowe-explorer-ftp-extension/src/extension.ts, yarn.lock
Signed-off-by: tian na <tiantn@cn.ibm.com>
Enabled zftp Jes functions in this PR. Also optimize some code, like conmon used getSession().
Milestone:
Changelog:
- [ x] New feature (non-breaking change which adds functionality)
- [ x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
If this is a relatively large or complex change, kick off the discussion by …
=> enable zftp Jes functions and optimize some code

docs/Developer's ReadMe.md
Signed-off-by: chladnefazole <nienaber@protonmail.com>
I was trying to test Deepali's PR, and I couldn't run the tests without a lot of trouble. So, I added a few things to the docs:
- A list of dependencies you need for the tests
- A note to compile the code before running tests
- A note to make sure Theia is running in the background during test execution
Milestone: Backlog
Changelog: Updated README with more information about Theia regression tests
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the …
=> Update README with more information about Theia tests

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> Prepare for v1.15.0 release

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Signed-off-by: Lauren Li <45975633+lauren-li@users.noreply.github.com>
Milestone:
Changelog:
=> Prepare for v1.16.0 release

.github/actions/common.js, .github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/.vscodeignore, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/README.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Removes redundant entry from Zowe Explorer FTP extension's `.vscodeignore` file.
Aimed at addressing issue #1377 (no zftp profile type option after installed Zowe Explorer Extension for FTP version 1.16.0).
Milestone: 1.16.1
Changelog: Fix Zowe Explorer Extension for FTP VS Code Marketplace release.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …
=> Remove redundant entry from ZE FTP vscodeignore

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Updated the pre-release version to 2.0.0-next.202107151328
Milestone:
Changelog:
=> Pre-release Ze 2.0.0-next.202107151328

docs/Early Access - Using Global Profile Configuration.md
This will add the initial document for the early access preview release of the global team configuration file
Milestone:
Changelog:
=> [next] Early access doc

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md
Regular update of doc for the new release.
Milestone: 1.17.0
Changelog: Inlcuded
=> (Doc) Update the 1.17.0 Readme and Changelog

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> Prepare 1.17.0 release

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md
Regular Readme and Changelog update for the next release.
Milestone: 1.18.0
Changelog: 
=> (Doc) Update 1.18.0 Readme and Changelog

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> Prepare 1.18.0 Release

packages/zowe-explorer-api/package.json
Signed-off-by: Peter Haumer <4391934+phaumer@users.noreply.github.com>
Fix for https://github.com/zowe/vscode-extension-for-zowe/issues/1410. This could be published as 1.18.1.
To test this you must update the version number in <https://github.com/zowe/vscode-extension-for-zowe/blob/added-cli-dependency-to-api/packages/zowe-explorer-api/package.json> and build it yourself and include the resulting tar file as a file dependency. Otherwise it …
=> Added cli dependency to api

.github/PULL_REQUEST_TEMPLATE.md
Reminder added to PR template to create a PR from `master` to `next` after PR is merged into `master` branch.
Milestone:
Changelog:
=> Reminder added to PR template

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md
The regular doc update before the next release. This is a patch release.
Milestone:
Changelog: 1.18.1
=> (Docs) Update Readme and Changelog for 1.18.1

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Prepare for v1.18.1 release.
After this PR is merged into the `v1.18.x` branch, another PR will be opened against `master` branch from `v1.18.x`.
=> Prepare for v1.18.1 release

.github/actions/common.js, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Update the pre-release version names to include `-SNAPSHOT` on the master branch along with the upcoming version, in this case 1.19.0.  Also, added a check for `SNAPSHOT` in the version name in the deployment common.js to not publish if true.
Milestone:
Changelog: Update the pre-release version names to include `-SNAPSHOT` on the master branch along with the upcoming version and a check in the deployment script to not publish if `SNAPSHOT` is in the version name.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
=> Update the pre-release version names to include `-SNAPSHOT` and deployment scripts

.github/actions/common.js, .github/workflows/deployment.yml, package.json, yarn.lock
- Set outputs regardless of whether there is a new version or not 😋 
- Comment out the ESLint upload step
Milestone:
Changelog:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what …
=> Make sure we get an archive name in the Step Outputs

docs/extenders/Error Handling.md
Signed-off-by: Katelyn Nienaber <katelyn.nienaber@broadcom.com>
Updates to Error Handling.md, advising extenders to use the new API logging functions.
Milestone: 2.0
Changelog: Updates to Error Handling.md, advising extenders to use the new API logging functions.
=> Documentation for imperative logger for extenders

.github/workflows/theia-zowe-explorer-ci.yml, packages/zowe-explorer/src/Profiles.ts
After the investigation done in PR #1487 it is known that Theia versions above 1.15.0 are breaking for us, trying our GHA tests to use v1.15.0
Docs will need to be updated to state the supported Theia version 1.15.0 until we figure out how to overcome these breaking changes with the newer versions
Milestone:
Changelog:
After a PR is merged into the `master` …
=> Fix Theia GHA tests by using the supported version 1.15.0 

packages/zowe-explorer/i18n/sample/src/dataset/DatasetTree.i18n.json, packages/zowe-explorer/src/dataset/DatasetTree.ts
Should remove this when `Save Credentials` is chosen
Also, shouldn't see this message either
This error was removed completely and if Cancel is chosen user should only get `Operation cancelled`
Milestone:
Changelog:
If this is a relatively large …
=> Fix for incorrect error seen with Check Credentials bugfix

packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/README.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md
Regular Readme and Changelog update
Milestone: 1.19.0
Changelog:
=> (Docs) Update Readme and Changelog for 1.19.0

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Prepare for 1.19.0 release
Milestone:
Changelog:
=> Prepare for 1.19.0 release

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Set 1.20.0-SNAPSHOT pre-release version on master
Milestone:
Changelog:
=> Set 1.20.0-SNAPSHOT pre-release version on master

.vscode/settings.json, packages/zowe-explorer-api/src/globals/Constants.ts, packages/zowe-explorer-api/src/globals/index.ts, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer-api/src/security/KeytarApi.ts, packages/zowe-explorer-api/src/security/KeytarCredentialManager.ts
Zowe Explorer API changes: `allExternalTypes` from `registerCustomProfilesType()` is not showing in `allProfiles` & `allTypes` on the `next` branch.  This change creates an array of all types merging `allExternalTypes` and `apiRegister.registeredApiTypes())` without duplicates for refresh method so all profile types are added to the `allProfiles` & `allTypes` arrays of ProfilesCache.
Milestone:
Changelog:
After a PR is merged into the …
=> [next] Refresh update for external types

packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json, packages/zowe-explorer/src/Profiles.ts
Update the localization keys for Add Session so that USS, Data Sets, and Jobs views all have unique keys. Resolves issue #1526.
Milestone: Any
Changelog: Use unique localization keys for Add Session in the USS, Data Sets, and Jobs views.
If this is a relatively large or complex change, kick off the discussion by explaining …
=> Issue 1526: Specify the tree view in localization keys for Add Session

packages/zowe-explorer/src/Profiles.ts
Signed-off-by: Richelle Anne Craw <richelleanne.craw@broadcom.com>
Fixes #1288 
Previously, the user and password prompt only stores the credentials for the session. 
This PR uses the config set API to store user and password as secure when the fields are defined as such in the config file. 
Changelog: Set user and password as secure after prompting
After a PR is merged into the `master` branch, create a PR from `master` to …
=> [next] Set user and password as secure after prompting

packages/zowe-explorer/README.md
Signed-off-by: ik673626 <igor.kazmyr@broadcom.com>
This PR addresses the #1572 issue. It adds a note to the Associate Profile feature description. The note notifies a user that the feature is deprecated and with the release of V2 will be entirely removed.
Milestone: should have been 1.18
Changelog: 
If this is a relatively …
=> (Doc) Add Deprecated note to Associate Profile section in doc

packages/zowe-explorer/src/globals.ts
Signed-off-by: Vit Gottwald <vit.gottwald@gmail.com>
=> Expression over statements

packages/zowe-explorer/src/globals.ts
A cherry pick of https://github.com/zowe/vscode-extension-for-zowe/pull/1579 to synchronize `next` branch.
=> Next small fix

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Prepare for 1.21.0 release
Milestone:
Changelog:
=> Prepare for 1.21.0 release

package.json, packages/zowe-explorer-ftp-extension/.prettierignore, packages/zowe-explorer-ftp-extension/__mocks__/@zowe/zowe-explorer-api.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/TestUtils.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/uss.unit.test.ts, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpJesApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts, packages/zowe-explorer-ftp-extension/tsconfig.json, yarn.lock
cherry-picked commits:
- https://github.com/zowe/vscode-extension-for-zowe/pull/1582/commits/7f758387562632e0082da1d06d24172c3b271c8a
- https://github.com/zowe/vscode-extension-for-zowe/pull/1582/commits/2d409625bcb998afbcf363884d90bdf49c64f608
- https://github.com/zowe/vscode-extension-for-zowe/pull/1582/commits/35383b870638103c1fafc4fef96e0aad78abd9bf
- https://github.com/zowe/vscode-extension-for-zowe/pull/1596/commits/6519be2b67c1bbd41c9fa2f67b2c14f97c218bb4
- https://github.com/zowe/vscode-extension-for-zowe/pull/1596/commits/e128cd7cd6b1a6c048d203a95293262735d715ef
Also cherry-picked Windows audit fix
- https://github.com/zowe/vscode-extension-for-zowe/pull/1580/commits/2debf9d8ab364d3aed5f9d5f545b7ea3e51fb97b
Changelog: FTP USS unit tests added.
What types of …
=> [next] FTP unit test updates from master branch

.github/workflows/deployment.yml
This PR addresses the following deployment issue:
A similar issue that was fixed by the user updating to Node 14: https://github.com/microsoft/vscode-vsce/issues/653; however, we are still supporting Node 12.
vsce 1.103.1 is the last version before it switched to Node 14 in version 2. (Both of these vsce versions were released Nov 4, 2021, per the [vsce releases page](https://github.com/microsoft/vscode-vsce/releases).)
Milestone: 1.21.0
Changelog: Update deployment script to use vsce 1.103.1 for Node 12 compatibility. (Internal)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
=> Update deployment to use vsce 1.103.1 for Node 12 compatibility

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Update master with 1.21.0 snapshot version.
=> Update master with 1.21.0 snapshot version

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Update master with 1.22.0-SNAPSHOT versioning
Milestone:
Changelog:
=> Update master with 1.22.0-SNAPSHOT versioning

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Update v1.21.x with 1.21.1-SNAPSHOT versioning
Milestone:
Changelog:
=> Update v1.21.x with 1.21.1-SNAPSHOT versioning

package.json, yarn.lock
Update dependencies from PRs #1591 and #1601.
Changelog: Update dependencies for improved security.
=> [next] Update dependencies from PR 1601

.vscode/launch.json, docs/README-Theia.md
Signed-off-by: Rudy Leonel Pichola Flores <rudyflores@ibm.com>
Work around for debugging Zowe Explorer VS Code extension on Theia
Milestone:
Changelog: Work around for being able to debug Zowe Explorer on Theia
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …
=> [Next] Work around for debugging in Theia

.github/workflows/zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ftp-ci.yml, README.md, packages/zowe-explorer/README.md
remove node 10.x from GHA files and update the minimum in READMEs to be node v12
Milestone:
Changelog:
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …
=> Update READMEs and GHA to Node 12 or later

.github/workflows/audit.yml, .github/workflows/zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ftp-ci.yml, package.json, yarn.lock
- Updated the `resolutions` object to resolve some dependabot alerts. 
- Separated the `audit` checks to its own workflow 
N/A
Milestone: N/A
Changelog: Updated `log4js` and `markdown-it` resolutions to resolve security alerts.
- Will do! 😋 
- There are more in-depth …
=> fix(dependencies): update resolutions + separate audit workflow

package.json, packages/zowe-explorer/__tests__/__unit__/command/tsoCommandHandler.unit.test.ts, packages/zowe-explorer/i18n/sample/src/command/TsoCommandHandler.i18n.json, packages/zowe-explorer/src/command/TsoCommandHandler.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts, yarn.lock
_Porting PR https://github.com/zowe/vscode-extension-for-zowe/pull/1645 to the `next` branch._
Added an `onDidHide` handler for `resolveQuickPickHelper`, which always return `undefined` result. 
The issue itself is opened for TSO command execution feature initially, but this bugfix affects a helper function, which is used in many places, and as a result it also fixes the cancelling cases for other commands (e.g. Issue MVS command, filter selections and etc.
Milestone:
Changelog:
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for …
=> [next] Fix input cancelling messaging

package.json, yarn.lock
Signed-off-by: Peter Haumer <4391934+phaumer@users.noreply.github.com>
The recent switch of the log4js version from v3 to v6 break activation of Zowe Explorer in Eclipse Che. 
```log
ERROR:Activating extension 'Zowe Explorer' failed:TypeError: Cannot read property 'name' of undefined
```
As this is a major version switch I propose we take more time in evaluating the changes required to make the latest log4js version work with Zowe Explorer on all platforms.  As this is not log4j and the [reported security vulnerability](https://github.com/advisories/GHSA-82v2-mx6x-wq7q) only is a moderate impact one I propose switching back for now. 
As the vulnerability applies to log file permissions of files, that in our case are located in the private home directory of a VS Code user and a personal …
=> The new log4js version breaks activation on Eclipse Che 

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/README.md, packages/zowe-explorer/package.json
=> Prepare 1.22.0 release

.github/workflows/deployment.yml
Use the LTS versions of NodeJS when publishing artifacts
N/A
Milestone: N/A
Changelog: N/A
- Will update #1630 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you …
=> fix(ci/cd): Update nodejs to use the LTS version for future deployments

.github/workflows/deployment.yml
Use node 14 for now
N/A
Milestone: N/A
Changelog: N/A
- Will update #1630 
- N/A
=> Use node 14 for now

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> Post release 1.23.0-SNAPSHOT

packages/zowe-explorer/__tests__/__unit__/command/mvsCommandHandler.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/command/mvsCommandHandlerTheia.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/mvs/mvsNodeActions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts, packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json, packages/zowe-explorer/i18n/sample/src/command/MvsCommandHandler.i18n.json, packages/zowe-explorer/i18n/sample/src/dataset/DatasetTree.i18n.json, packages/zowe-explorer/i18n/sample/src/job/ZosJobsProvider.i18n.json, packages/zowe-explorer/i18n/sample/src/shared/actions.i18n.json, packages/zowe-explorer/i18n/sample/src/uss/USSTree.i18n.json, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/command/MvsCommandHandler.ts, packages/zowe-explorer/src/dataset/DatasetTree.ts, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/job/ZosJobsProvider.ts, packages/zowe-explorer/src/shared/actions.ts, packages/zowe-explorer/src/uss/USSTree.ts
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>
fixes: #1651 
Updated the selector cancellation messages & their tests.
Milestone:
Changelog:
=> #1651 Updated all the selector cancellation messages

docs/Early Access - Using Global Profile Configuration.md, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/__tests__/__unit__/command/mvsCommandHandler.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/command/mvsCommandHandlerTheia.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/mvs/mvsNodeActions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts, packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json, packages/zowe-explorer/i18n/sample/src/command/MvsCommandHandler.i18n.json, packages/zowe-explorer/i18n/sample/src/dataset/DatasetTree.i18n.json, packages/zowe-explorer/i18n/sample/src/job/ZosJobsProvider.i18n.json, packages/zowe-explorer/i18n/sample/src/shared/actions.i18n.json, packages/zowe-explorer/i18n/sample/src/uss/USSTree.i18n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/command/MvsCommandHandler.ts, packages/zowe-explorer/src/dataset/DatasetTree.ts, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/job/ZosJobsProvider.ts, packages/zowe-explorer/src/shared/actions.ts, packages/zowe-explorer/src/uss/USSTree.ts
Update `next` with changes from `master` branch
includes PRs
#1675 
Milestone:
Changelog:
=> [next] Update with master

packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Fixes #1618 
The issue stems from the merging of `allprofiles` and not being able to filter like-named profiles in nested config files.
Milestone: pre-release
Changelog: Fixed the bug that overwrites like-named profiles in a nested config
If this is a relatively large or complex change, kick off the discussion by explaining …
=> [next] Fix nested config issue

docs/Early Access - Using Global Profile Configuration.md, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json, yarn.lock
updated zowe cli sdk for issues seen in last pre-release
7.0.0-next.202202242016
Some ZE API users are cli plugins and are seeing the install issues we spoke of in slack.
Milestone: 2.0.0-next.202202281000
Changelog: Update Zowe CLI SDK to version 7.0.0-next.202202242016
After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch …
=> Pre-Release and update sdk 7.0.0-next.202202242016

packages/zowe-explorer/src/Profiles.ts
If config file is in place open the config file when Add Profile is selected.
Milestone: 2.0.0-next
Changelog: Open Config file that is being used when Add Profile is selected.
If this is a relatively large or complex change, kick off the …
=> [next] Open config file with add profile

docs/Conformance Criteria/README-Conformance Criteria V2.md
Rose's comment:
"I noticed you have 2 entries labeled # 23 in your conformance criteria, assuming this is a mistake and your total should be 28?
One comment, in item 10 where the instructions state MARK (a) (b) or (c); I feel we should eliminate the word "OR" since we are asking for "all" that apply.  Let me know what you think."
I presented a couple options for rewording # 10 to her and `Mark all that apply, (a) (b) (c)` was decided on.
Milestone:
Changelog:
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor …
=> Address v2 conformance feedback from Rose

packages/zowe-explorer/src/Profiles.ts
Changed Logout extender profile type check to include a check for API ML tokenType
Changelog:
=> Check for API ML tokenType with extender profile types on Logout

.github/workflows/deployment.yml, docs/Early Access - Using Global Profile Configuration.md, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
please review and make sure all new PRs are included within the Zowe Explorer & Zowe Explorer API CHANGELOGs
Milestone: pre-release 2.0.0-next.202204041200
Changelog:
If this is a relatively large or complex change, kick off the discussion by …
=> Prepare pre-release 2.0.0-next.202204041200

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
Add SNAPSHOT to next branch as discussed will update wiki to include release prep of next to have format 
[wiki Notes section](https://github.com/zowe/vscode-extension-for-zowe/wiki/Preparing-for-a-release#notes) updated
Milestone:
Changelog:
If this is a relatively large or complex change, kick off the discussion by …
=> Release follow up add SNAPSHOT

docs/README-Extending.md, packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
Added documentation on `promptCredentials()`
Milestone: V2
Changelog: Added documentation on `promptCredentials()`
=> Add doc for prmoptCredentials() api

packages/zowe-explorer-ftp-extension/__mocks__/vscode.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
Milestone:
Changelog:
- [x ] Bugfix (non-breaking change which fixes an issue)
- [ x] I have added unit test and it is passing
=> Check lrecl

packages/zowe-explorer/src/Profiles.ts
fixes issue #1752 
came across it when creating the very first Config file after updating from 1.22.0 to a v2 vsix.  So may need to check and delete any zowe config references in your credential manager before hand to see the error if trying to recreate the issue.  I was starting from clean slate like a user would when they change over
Milestone:
Changelog:
After a PR is merged into the `master` branch, create a PR from `master` to the `next` …
=> fix for migration issue 1752

packages/zowe-explorer/src/Profiles.ts
updates for writing to file during login/logout
https://github.com/zowe/vscode-extension-for-zowe/issues/1753
=> update to writing to files

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
Pre-release 2.0.0-next.202204202000
To be merged after https://github.com/zowe/vscode-extension-for-zowe/pull/1757
=> Pre-release publish

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
To follow https://github.com/zowe/vscode-extension-for-zowe/pull/1762
=> Add back SNAPSHOT

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
1.22.1 hotfix release with FTP fix
Milestone:
Changelog:
=> Set up for 1.22.1 hotfix release

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> 2.0.1-SNAPSHOT

.github/PULL_REQUEST_TEMPLATE.md, packages/zowe-explorer/src/Profiles.ts
bugfix: adding profile to view in Theia #1774 
Milestone: 2.0.1
Changelog: Fix adding profile to view in Theia.
=> Fix for adding profile to view in Theia

package.json, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts, packages/zowe-explorer-api/src/vscode/doc/IPromptCredentials.ts, packages/zowe-explorer/package.json, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts, yarn.lock
Signed-off-by: Rudy Flores <68666202+rudyflores@users.noreply.github.com>
Fix previously discovered activation issue with log4js by bumping to latest version 6.4.6.
Milestone:
Changelog: Bump log4js version to 6.4.6 to fix activation for Che.
=> Fix log4js activation issue

package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/ZoweExplorerExtender.ts, yarn.lock
In this PR:
- Introduces support for Environmental Variables in Zowe Explorer
Milestone: 2.1.0 (preferably)
Changelog: Added environmental variable support.
=> fix(profiles): Avoid replacing the `loadedConfig` in favor of using `getZoweDir`

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> 2.0.3-SNAPSHOT PR

packages/zowe-explorer/i18n/sample/src/extension.i18n.json, packages/zowe-explorer/src/extension.ts
Signed-off-by: Rudy Flores <68666202+rudyflores@users.noreply.github.com>
Added a pop up error message when a silent refresh is performed on Che after creating a team config file.
Milestone:
Changelog:
=> Add pop up message for Che refresh issue

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
=> Prepare 2.0.3 release

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> Follow up SNAPSHOT

packages/zowe-explorer/README.md, packages/zowe-explorer/i18n/sample/package.i18n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/package.nls.json
update Refresh Zowe Explorer keybinding as to not overwrite default.
updated README to include our keybindings
updated Activity Bar title from `ZOWE` TO `ZOWE EXPLORER`
Milestone:
Changelog:
=> keybinding updates

packages/zowe-explorer/src/job/ZosJobsProvider.ts, packages/zowe-explorer/src/job/actions.ts
fix for #1751 
Milestone:
Changelog:
=> Bugfix: job submitted hyperlink

packages/zowe-explorer-ftp-extension/__tests__/__unit__/FtpApi/ZoweExplorerAbstractFtpApi.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Jes/ZoweExplorerFtpJesApi.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpJesApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts, packages/zowe-explorer-ftp-extension/src/extension.ts, packages/zowe-explorer-ftp-extension/src/ftpSession.ts
Signed-off-by: Tina <tiantn@cn.ibm.com>
Milestone:
Changelog:
=> reuse listconnection

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
prepare 2.2.0 release version updates and release notes.
=> 2.2.0 release 

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> 2.3.0-SNAPSHOT 

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
=> 2.2.1 Release

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> 2.3.0 SNAPSHOT

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
Update version to 2.3.0 for publishing.
Updated CHANGELOGs for 2.3.0 release.
=> Prepare 2.3.0 release

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
release follow up PR 2.4.0-SNAPSHOT
=> 2.4.0-SNAPSHOT  

packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts, packages/zowe-explorer/__mocks__/@zowe/cli.ts, packages/zowe-explorer/__tests__/__unit__/command/tsoCommandHandler.extended.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/shared/actions.ts
Fix code smells identified by Coverity scan
I don't think this needs to be mentioned in the changelog
=> Fix code smells

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__mocks__/mockCreators/shared.ts, packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts, packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/ZoweExplorerExtender.ts, packages/zowe-explorer/src/dataset/DatasetTree.ts, packages/zowe-explorer/src/extension.ts, packages/zowe-explorer/src/job/ZosJobsProvider.ts, packages/zowe-explorer/src/uss/USSTree.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts
Add check for existing config in location of Create Team Config choice.  If file exists user is notified of existing file and prompted to continue with creation.  If user cancels the existing config will open for editing and if user chooses Create New the create process will continue as usual with the creation/merging of existing values with new config in selected location.
Milestone: 2.4.0
Changelog: Added check for existing team configuration file in location during create, prompting user to continue with the create action.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
=> Create config check

packages/zowe-explorer/package.json, packages/zowe-explorer/src/web/extension.ts
These changes lay the groundwork for a Zowe Explorer web extension. It defines a new `extension.ts` to be run in browser environments, adds a new webpack CLI command to compile `extension.ts` for a browser environment, and edits the prepublish script to perform this task.  
This will allow other web extensions to be dependent on Zowe Explorer. There is no web functionality now, but this is a starting point for those changes. 
Milestone:
Changelog:
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the …
=> feat : Stubbing out Zowe Explorer web extension

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
=> Update version 2.5.0-SNAPSHOT

package.json, packages/zowe-explorer-api/package.json, yarn.lock
Updated dependencies for technical currency
Milestone: 1.22.3
Changelog: Updated dependencies for technical currency purposes
=> patch(dep): update V1 dependencies

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
=> Follow-up version 2.5.0-SNAPSHOT

package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/__mocks__/@zowe/imperative.ts, packages/zowe-explorer/__tests__/__unit__/api/__snapshots__/ZoweExplorerZosmfApi.unit.test.ts.snap, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/__snapshots__/ZoweUSSNode.unit.test.ts.snap, packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts, packages/zowe-explorer/package.json, yarn.lock
update Jest versions to latest and fix tests for updates as well as the jest configuration
Changelog:
=> Update jest versions to latest

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
Prepare 1.22.2 release
Milestone: 1.22.2
Changelog:
=> 1.22.2 release

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/package.json
release follow up PR with SNAPSHOT version
Milestone:
Changelog:
=> 1.23.0-SNAPSHOT

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
=> Prepare 2.5.0 release

package.json, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
=> 2.6.0-SNAPSHOT

packages/zowe-explorer/README.md
Fix #2014
Signed-off-by: zFernand0 <37381190+zFernand0@users.noreply.github.com>
Add links under the `more info` section
Changelog:
=> fix(doc): Add secure-settings link to readme

package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts, packages/zowe-explorer/src/globals.ts, yarn.lock
Update isTheia check to reduce false positives.
Changelog: Updated check for Theia environment to reduce false positives in different environments.
=> update isTheia check to reduce false positives

.github/workflows/theia-zowe-explorer-ci.yml, packages/zowe-explorer/__tests__/__theia__/extension.theia.test.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts
Take screenshots of failing Theia tests and save them in the "results/integration" folder which is archived by the GitHub workflow.
Hopefully this will help us to diagnose the problem causing several tests to occasionally have transient failures.
Example run with screenshots in the artifact: https://github.com/zowe/vscode-extension-for-zowe/actions/runs/3915784470
N/A since only tests have been changed
=> Take screenshots of failing Theia tests

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- Resolves #2084 
Fallback to the previous implementation when there is no implementation for `dataSetsMatching` (`dsm`)
Changelog: Fallback to previous implementation when `dsm` is not implemented in the `mvsApi`
=> fix(ds-matching-list): fallback to previous implementation if needed

README.md, packages/zowe-explorer-ftp-extension/README.md, packages/zowe-explorer/README.md
Top level, ZE, and FTP ext vsc badge link updates
Milestone:
Changelog:
what is seen on marketplace now and in GH repo top level README (also in copy on zowe.org), no badge links for FTP ext
After this change
=> Fix links for VS Code marketplace badges in the READMEs

.github/workflows/deployment.yml, package.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
=> 2.6.0 release

package.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
should follow #2089 
follow up PR 2.7.0-SNAPSHOT
=> 2.7.0-SNAPSHOT

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__mocks__/vscode.ts, packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts, packages/zowe-explorer/i18n/sample/src/dataset/actions.i18n.json, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/uss/actions.ts, packages/zowe-explorer/src/utils/workspace.ts
Resolves #2099
Milestone: 2.6.1
Changelog: Fixed possible data loss when file is saved but fails to upload and VS Code does not detect unsaved changes. #2099
=> fix(ds/uss): Mark document as unsaved if upload fails

packages/zowe-explorer-api/__mocks__/fs.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/extension.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/ftpSession.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/shared/context.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/LoggerUtils.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/ProfileUtils.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/SessionUtils.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/SettingsConfig.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/TempFolder.unit.test.ts
Part two of the ongoing test coverage changes, this should bring the test coverage for branches up to 80%
Milestone:
Changelog: Increased branch coverage to 80%
=> Increase branch coverage to 80%

.github/workflows/deployment.yml, lerna.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>
prepare 2.6.1 release
=> 2.6.1 release

.github/workflows/deployment.yml
=> Fix wrong names used for ovsx and vsce tokens

.github/workflows/deployment.yml
=> Fix wrong token being used to push release commits

.github/release.config.js
=> Fix npm tags for zowe-explorer-api package

.github/workflows/theia-zowe-explorer-ci.yml, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/uss/ZoweUSSNode.ts
Fix code smells identified by Coverity scan
N/A
=> Fix code smells (part 3)

.github/workflows/theia-zowe-explorer-ci.yml, .gitignore, .prettierignore, .vscode/launch.json, package.json, packages/zowe-explorer/__tests__/__integration__/Profiles.integration.test.ts, packages/zowe-explorer/__tests__/__integration__/command/mvsCommands.integration.test.ts, packages/zowe-explorer/__tests__/__integration__/command/tsoCommands.integration.test.ts, packages/zowe-explorer/__tests__/__integration__/dataset/actions.integration.test.ts, packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts, packages/zowe-explorer/__tests__/__integration__/index.ts, packages/zowe-explorer/__tests__/__integration__/shared/refresh.integration.test.ts, packages/zowe-explorer/__tests__/__integration__/uss/ussNodeActions.integration.test.ts, packages/zowe-explorer/__tests__/__theia__/index.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts, yarn.lock
Here are some of the updates I believe might be necessary to get the Theia (and our "integration") tests working after updating the mocha types to be up to date with our mocha version. 😋
=> Update mocha types

README.md
=> Add Codecov and Slack badges to top level readme

lerna.json
I hope I did this right @t1m0thyj :slightly_smiling_face:
Prepare 2.6.2 release
Milestone:
Changelog:
=> 2.6.2 release

package.json, packages/zowe-explorer-api/package.json, yarn.lock
Update Zowe CLI to 7.11.0
Milestone: 2.7.0
Changelog: N/A
=> Update Zowe CLI dependency

package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer/CHANGELOG.md, yarn.lock
Update Zowe CLI dependency to pick up changes for bugs https://github.com/zowe/vscode-extension-for-zowe/issues/2175 
Changelog: ZE - Fixed z/OSMF profiles issue with Data Sets and Jobs with special characters in the names. [#2175](https://github.com/zowe/vscode-extension-for-zowe/issues/2175)
=> Update Zowe CLI to pick up fixes for special characters in Jobs

packages/zowe-explorer/__tests__/__unit__/utils/LoggerUtils.unit.test.ts, packages/zowe-explorer/src/globals.ts, packages/zowe-explorer/src/utils/LoggerUtils.ts
can remove the return from initLogger since new code gets log file location and can use that for initVscLogger(). also, set the log file log level to match the ZE log level during initLogger
Milestone:
Changelog:
=> Suggested changes for logging

packages/zowe-explorer/src/extension.ts
Initialize logger first so other activation events that log output can follow and not cause extension to crash.
Can verify issue by packaging main branch and installing change the log level to trace then refresh vsc.
Changelog: N/A due to new issue brought in with development
=> Fix for activation order failures

lerna.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/i18n/sample/src/job/actions.i18n.json
Prepare the release
Updated CHANGELOGs 
Changelog: N/A
=> 2.8.0 Release

.github/workflows/audit.yml, .github/workflows/auto-comment.yml, .github/workflows/changelog.yml, .github/workflows/deployment.yml, .github/workflows/lint.yml, .github/workflows/stale.yml, .github/workflows/theia-zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ftp-ci.yml
* Update workflows to remove deprecation warnings
* Remove Node 14 (EoL) from workflow matrix
Milestone:
Changelog: N/A
=> Update workflows to remove deprecation warnings

packages/zowe-explorer-ftp-extension/README.md
Added snippet to Step 6 of [Create a Team Configuration File](https://github.com/zowe/vscode-extension-for-zowe/tree/main/packages/zowe-explorer-ftp-extension#create-a-team-configuration-file).
This resolves [Issue 1899](https://github.com/zowe/vscode-extension-for-zowe/issues/1899)
=> updating readme w/ zftp snippet

lerna.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/utils/SettingsConfig.unit.test.ts, packages/zowe-explorer/src/utils/SettingsConfig.ts
Fixes #2312 
Milestone: 2.8.2
Changelog: Fixed `zowe.settings.version` being added to settings.json in workspaces
=> Fix zowe.settings.version being added to workspace settings

.github/workflows/deployment.yml
=> Install known good version of Lerna in deployment workflow

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts, packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json, packages/zowe-explorer/i18n/sample/src/shared/init.i18n.json, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/shared/init.ts
Solves #2211 
Fix profile watcher for browser based environments
Milestone: v2.9.1
Changelog: Fixed profile watcher on browser based environments
=> Fix watcher on browser based environments

packages/zowe-explorer/README.md
Updates to Zowe Explorer's README to include information on MFA support as well as password term for use with other authentication secrets.
Did re-org as the Sample Use Cases took over the README making users dig for important information so kept the quick links at top pointing to scenarios stored further down in file and each scenario has a quick link back to list of use cases.
Milestone: 2.9.1
Changelog: n/a
=> Updates to ZE README

lerna.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
Prepare 2.9.1 release
Milestone: 2.9.1
Changelog: n/a
=> 2.9.1 Release

lerna.json, package.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md, packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/__snapshots__/ZoweUSSNode.unit.test.ts.snap, packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json, packages/zowe-explorer/i18n/sample/src/shared/init.i18n.json, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts, packages/zowe-explorer/src/job/ZosJobsProvider.ts, packages/zowe-explorer/src/job/ZoweJobNode.ts, packages/zowe-explorer/src/shared/init.ts, packages/zowe-explorer/src/shared/utils.ts, packages/zowe-explorer/src/uss/ZoweUSSNode.ts, yarn.lock
Update Main branch with Maintenance 2.9.1
Milestone: n/a
Changelog: n/a
=> Update Main branch with Maintenance 2.9.1

package.json, yarn.lock
Cherry picked Fernando's fix that went into main
Changelog: n/a
=> Bring audit fix into maintenance branch

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts, packages/zowe-explorer/i18n/sample/src/job/ZoweJobNode.i18n.json, packages/zowe-explorer/src/job/ZoweJobNode.ts
Solves #2362 
Add `Jobs not found` message to jobs view when performing a filter search and not jobs are returned.
Changelog: Added jobs not found message when no results are returned from filter.
=> Add jobs not found message

packages/zowe-explorer/__tests__/__theia__/extension.theia.test.ts, packages/zowe-explorer/__tests__/__theia__/theia/Locators.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts
=> Fix integration tests for Theia 1.37

packages/zowe-explorer-ftp-extension/README.md, packages/zowe-explorer/README.md, packages/zowe-explorer/i18n/sample/package.i18n.json, packages/zowe-explorer/i18n/sample/src/utils/SettingsConfig.i18n.json, packages/zowe-explorer/package.nls.json, packages/zowe-explorer/src/Profiles.ts
Merge after https://github.com/zowe/vscode-extension-for-zowe/pull/2388
Changelog:
1) Edit config right-click option
2) Add/Create Session options if v1 Profiles in place
=> UX fixes for v3 pre-release

packages/zowe-explorer/__tests__/__theia__/extension.theia.test.ts, packages/zowe-explorer/__tests__/__theia__/theia/Locators.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts
cherry picked @t1m0thyj 's commits for the Theia fixes on maintenance branch
Milestone: n/a
Changelog: n/a
=> Port Theia fixes from maintenance branch

lerna.json, packages/zowe-explorer/README.md
Prepare 2.9.2 patch release
Changelog: N/A
=> Prepare 2.9.2 patch release

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
Fix the USS refresh icon (replacing "download" with "refresh")
Fix the USS refresh icon (replacing "download" with "refresh")
Milestone:
Changelog:
- [ x] Bugfix (non-breaking change which fixes an issue)
=> Fix for the USS refresh icon

package.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md, packages/zowe-explorer/__tests__/__unit__/ZoweNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts, packages/zowe-explorer/i18n/sample/src/dataset/ZoweDatasetNode.i18n.json, packages/zowe-explorer/i18n/sample/src/job/ZoweJobNode.i18n.json, packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json, packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts, packages/zowe-explorer/src/dataset/DatasetTree.ts, packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts, packages/zowe-explorer/src/job/ZosJobsProvider.ts, packages/zowe-explorer/src/job/ZoweJobNode.ts, packages/zowe-explorer/src/uss/USSTree.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts, yarn.lock
Port 2.9.2 changes to main branch
Milestone: n/a
Changelog: n/a
=> Port 2.9.2 changes to main branch

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts
fix regression introduced in 2.9.2 for token authentication
Milestone: 2.10.0 
Changelog: Fix error for Theia check when token authentication returns 401.
=> Fix for 401 token error regressions

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
fix for #2033 to remove the 'Show Atrributes' content menu action for migrated datasets.
Milestone: 10.0.1
Changelog: Remove the 'Show Attributes' context menu action for migrated datasets.
=> fix(ds): remove 'Show Attributes' menu item if DS is migrated

package.json, packages/zowe-explorer/package.json, packages/zowe-explorer/webviews/edit-attributes/package.json, yarn.lock
Add definition of workspace to package.json workspaces for the `edit-attributes` package, the `fresh-clone` command was also added to this to make sure the latest changes are bundled.
Changelog: corrected workspace for webviews on zowe explorer
=> Correct workspace for webviews

.github/release.config.js, lerna.json, package.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
Making a draft until we get deployment updated correctly for release
Changelog: n/a
=> [vNext] Prepare v3 pre-release 1

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils.unit.test.ts, packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json, packages/zowe-explorer/src/job/ZosJobsProvider.ts, packages/zowe-explorer/src/job/ZoweJobNode.ts, packages/zowe-explorer/src/job/actions.ts, packages/zowe-explorer/src/uss/USSTree.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts
fixes issue seen in https://github.com/zowe/vscode-extension-for-zowe/issues/2440
fixes job & uss tree update when new search entered
Milestone: 
Changelog: Fixed issue with favorited Job filter search. https://github.com/zowe/vscode-extension-for-zowe/issues/2440
=> Fix issue with favorited searches for jobs tree

.github/workflows/deployment.yml
Fixes our deployment workflow so it will run when changes are pushed to the next branch.
=> Update deployment.yml to include next branch

packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json, packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fix: Update check to include all prof types registered with API ML & add profile label to login popup like we did with creds popup so users know which profile is creating the warning popup
Changelog: n/a
=> Fix: Update check to include all prof types registered with API ML

.github/workflows/deployment.yml
The v1 LTS deployment workflow ended up crashing as it did not have the Lerna fix that is in the main branch.
Milestone:
Changelog:
=> fix(ci): install lerna@6 for deployment workflow

packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json, packages/zowe-explorer/webviews/edit-attributes/src/App.tsx
Fix an issue where edit attributes webview never loads since `useEffect` hook returns instantly since call is from a non `vscode-webview://` endpoint. 
this endpoint is specific to local VS Code only, in web environments such as che or vscode.dev this may not be the case which caused the issue.
Milestone: 2.11.1
Changelog: Fixed issue with webview not loading for web users
=> Fix webview for web

lerna.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json
prepare 2.11.1 patch release
Milestone: 2.11.1
Changelog: n/a
=> 2.11.1 release

.github/workflows/changelog.yml, .github/workflows/deployment.yml, samples/vue-webview-sample/package.json
Add the `install` and `build` steps in the deployment workflow
Milestone: N/A
Changelog: N/A
=> fix(cicd): Update deployment workflow

.github/workflows/deployment.yml, package.json, pnpm-lock.yaml
- Replace the old repository tokens with the new zowe org-wide tokens
- Replace the "workspace:" protocol to use the package path instead of the independent version.
Reasons:
- Lerna won't touch this protocol when using `pnpm` ([source](https://lerna.js.org/docs/recipes/using-pnpm-with-lerna))
- Running a `pnpm install` after a `lerna version` will cause the following error
```
 ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In : No matching version found for 
      eslint-plugin-zowe-explorer@workspace:3.0.0-next.202309141150 inside the workspace
```
- Decided on `./packages/eslint...` vs `packages/eslint...` because the latter is considered invalid. See error below:
```
 ERROR  Invalid workspace: spec (workspace:packages/eslint-plugin-zowe-explorer)
```
Milestone: N/A
Changelog: Update …
=> fix(cd): Fix workspace reference to allow for automatic versioning

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json
Fixes #2547 
Remove from menu old buttons that were moved to `Manage Profile` menu on USS view
Milestone: v2.12.1
Changelog: Removed duplicate buttons displayed on USS view that now exist on `Manage Profile` view
=> Move profile management menu items to proper location

lerna.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
prepare 2.12.1 release. set version and update CHANGELOGs
Milestone: 2.12.1
Changelog: n/a
=> 2.12.1 release

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts, packages/zowe-explorer/src/dataset/actions.ts
Added enhancement to show job confirmation dialog when user submits a local JCL. With this enhancement, behavior now aligns with submitting a JCL from Data Sets view.
Work item: https://github.com/zowe/vscode-extension-for-zowe/issues/2061
Milestone:
2.13.0
Changelog:
Display confirmation dialog when submitting local JCL. [#2061] (https://github.com/zowe/vscode-extension-for-zowe/issues/2061)
=> Include job confirmation popup when submitting local JCL 

packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts, packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/shared/utils.ts, packages/zowe-explorer/src/uss/actions.ts
Merge 2.12.2 into main
Milestone: n/a
Changelog: n/a
=> Merge 2.12.2 into main

package.json, packages/zowe-explorer-api/package.json, samples/tree-view-sample/package.json, samples/uss-profile-sample/package.json, yarn.lock
update cli dependency to 7.19.0
remove un-needed zowe imperative dependency from sample
Milestone: 2.13.0
Changelog: n/a
=> Update cli dependency

packages/zowe-explorer-api/package.json, packages/zowe-explorer/package.json, yarn.lock
as discussed in slack, we need to keep our versions matched when updating and with the update of Zowe CLI to 7.19.0 we need to update the Zowe Secrets version to 7.18.6
Milestone: 2.13.0
Changelog: n/a
=> Update secrets to match latest cli version

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/init.unit.test.ts, packages/zowe-explorer/i18n/sample/src/dataset/DatasetTree.i18n.json, packages/zowe-explorer/i18n/sample/src/job/ZosJobsProvider.i18n.json, packages/zowe-explorer/i18n/sample/src/job/utils.i18n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts, packages/zowe-explorer/src/dataset/DatasetTree.ts, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/globals.ts, packages/zowe-explorer/src/job/ZosJobsProvider.ts, packages/zowe-explorer/src/job/ZoweJobNode.ts, packages/zowe-explorer/src/job/init.ts, packages/zowe-explorer/src/job/utils.ts
-> For filtering the jobs at the zOSMF session level a filter icon is added for the easier accessibility to filter jobs based on job name, job id and return code.
-> and also provided with an option 'Filter Jobs' at the right click menu of zOSMF session level to filter jobs based on job name, job id and return code.
And the input box added here will be filtering the content of Jobs dynamically. That means for each and every character user enters it will be displaying results based on that, which is an enhancement over the old method of filtering once the user enters text and hits the enter button.
Milestone:
Changelog:
_Put an `x` in the boxes that apply. You can also fill these out after …
=> feat: Local Filtering of Jobs Tree

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/src/Profiles.ts
Resolves https://github.com/zowe/vscode-extension-for-zowe/issues/2638
This adds a call to Profiles.getInstance().refresh() in ssoLogin() after successfully getting a new token. 
To test, log in to authentication service multiple times without closing VS Code and do something in one of the trees with logging set to trace. The token value shown in the logs should change each time you log in to the authentication service.
In 2.13.0, the first token value would be used until VS Code is restarted.
Milestone:
2.14.0
Changelog:
- Fixed failure to refresh token value after user logs in to authentication. [#2638](https://github.com/zowe/vscode-extension-for-zowe/issues/2638)
_Put an `x` in the …
=> fix(Profiles.ts): Add Profiles refresh after token log in

package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, yarn.lock
update zowe cli dependency  6.40.25 to address ssh2 vulnerability
Milestone: v1-lts
Changelog: Update dependencies to address vulnerabilities.
=> v1-lts - update zowe cli dependency to address ssh2 vulnerability

lerna.json, package.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, samples/uss-profile-sample/package.json, yarn.lock
Includes: 
Dependency update PR https://github.com/zowe/vscode-extension-for-zowe/pull/2640
Milestone: 2.13.1
Changelog: n/a
=> 2.13.1 Patch Release

README.md, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
merge in changes from 2.13.1 release, mainly just CHANGELOGs
Milestone: n/a
Changelog: n/a
=> Update main CHANGELOGS with 2.13.1 release

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md, packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts, packages/zowe-explorer/src/dataset/DatasetTree.ts, packages/zowe-explorer/src/uss/USSTree.ts, packages/zowe-explorer/src/uss/ZoweUSSNode.ts
Fix the updating of MVS and USS tree when a file or folder is renamed
Milestone: 2.14.0
Changelog: - Fixed issue seen after renaming an MVS or USS file or folder. [#2656](https://github.com/zowe/vscode-extension-for-zowe/issues/2656)
=> address rename treeview update regression

.github/workflows/update-project.yml
Ports #2654 to next branch so that workflow will run for pull requests for v3 opened against the next branch 🙂
=> Add update-project.yml workflow to next branch

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/i18n/sample/package.i18n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/package.nls.json
Resolves https://github.com/zowe/vscode-extension-for-zowe/issues/2670.
This PR rearranges the jobs tree context menu to match the data set tree context menu in terms of menu item order and also changes the text from "Filter jobs" to "Filter jobs..." for consistency.
New look:
Milestone:
v2.15.0
Changelog:
Adjusted order of 'Manage Profile' and 'Edit History' in the jobs tree's context menu to match the other trees. [#2670](https://github.com/zowe/vscode-extension-for-zowe/issues/2670)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as …
=> fix(jobs-tree-context-menu): Adjust menu item order for consistency

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts, packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/dataset/init.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/__snapshots__/ZoweUSSNode.unit.test.ts.snap, packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/init.unit.test.ts, packages/zowe-explorer/package.json, packages/zowe-explorer/src/dataset/DatasetTree.ts, packages/zowe-explorer/src/dataset/init.ts, packages/zowe-explorer/src/globals.ts, packages/zowe-explorer/src/uss/USSTree.ts, packages/zowe-explorer/src/uss/ZoweUSSNode.ts, packages/zowe-explorer/src/uss/actions.ts, packages/zowe-explorer/src/uss/init.ts
Follow up to #2594 that removes old commands and deprecated APIs no longer needed for encoding in the vNext branch
Milestone:
Changelog:
=> Remove old encoding commands and APIs in v3

package.json, packages/zowe-explorer/src/utils/ProfileManagement.ts, packages/zowe-explorer/src/webviews/package.json, pnpm-lock.yaml
I did this when I had some spare time thinking that I'd run into issues, but everything seems to be compiling and testing just fine!
This PR upgrades TypeScript to v5 so we can leverage some of the new features such as [Explicit Resource Management](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management) or [switch(true) narrowing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html#switch-true-narrowing) 😋 
Milestone: v3
Changelog: (no changelog)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to …
=> deps: Use TypeScript 5

.github/actions/deploy-npm-package/action.yml, .github/actions/deploy-vscode-extension/action.yml, .github/workflows/audit.yml, .github/workflows/auto-comment.yml, .github/workflows/changelog.yml, .github/workflows/codeql.yml, .github/workflows/deployment.yml, .github/workflows/lint.yml, .github/workflows/stale.yml, .github/workflows/theia-zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ftp-ci.yml, .github/workflows/zowe-explorer-samples.yml
Update deprecated workflows to versions running on Node 20.
Milestone:
Changelog:
=> Actions: Update workflows to Node 20 workflows

lerna.json, package.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/CHANGELOG.md, samples/uss-profile-sample/package.json, yarn.lock
cherry picked commits in https://github.com/zowe/vscode-extension-for-zowe/pull/2712 for 2.14.1 patch release
Milestone: 2.14.1
Changelog: n/a
=> 2.14.1 patch release

packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
port 2.14.1 to main branch
Milestone: n/a
Changelog: n/a
=> Port 2.14.1 updates to main 

packages/zowe-explorer-api/src/Types.ts, packages/zowe-explorer-api/src/utils/Poller.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts, packages/zowe-explorer/__tests__/__integration__/uss/ussNodeActions.integration.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/DecorationProviders.unit.test.ts, packages/zowe-explorer/src/PersistentFilters.ts, packages/zowe-explorer/src/command/UnixCommandHandler.ts, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/utils/DecorationProviders.ts
This PR ports the changes from #2714 to the `next` branch.
Milestone:
Changelog: No changelog
=> fix(v3): SonarCloud medium and high-priority bugs

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts, packages/zowe-explorer/src/job/ZoweJobNode.ts
Bring changes from [2721](https://github.com/zowe/vscode-extension-for-zowe/pull/2721) into `next`
Milestone: v3 pre-releases
Changelog:
=> Cherry-pick commits from Bugfix/2721

README.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer-api/src/security/KeytarCredentialManager.ts, packages/zowe-explorer/README.md, packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts, packages/zowe-explorer/l10n/bundle.l10n.json, packages/zowe-explorer/package.json
Address #2726 
Removal of Theia support in documentation and others.
Milestone:
Changelog:
=> Removal of Documentation related to Theia

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/src/Types.ts, packages/zowe-explorer-api/src/tree/sorting.ts, packages/zowe-explorer/.prettierignore, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/l10n/bundle.l10n.json, packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts, packages/zowe-explorer/src/dataset/utils.ts
To add an additional PDS member sorting option that allows users to sort by Date Created.
Milestone:
Changelog:
=> Sorting of PDS members by date created

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Solves #2111 
Fixes the issue of accessibility of all the profiles when the default profile is using the APIML token authentication
Milestone:
Changelog:
=> Restore accessibility to all profiles when default profile has APIML token authentication

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts, packages/zowe-explorer/src/shared/utils.ts
https://github.com/zowe/vscode-extension-for-zowe/issues/2695
This fix is to to push the new encoding onto the end of the array and filter any duplicates that are added.
Last part of this issue will be split up into another issue.
Milestone:
Changelog: Sort encoding by the latest encoding and filter any duplicate encoding if it already exists.
=> Sort encoding history

lerna.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md
Updated lerna and CHANGELOGs
believe this will also publish the audit issues fix, last publish of v3 was 2/14
Changelog: n/a
=> Next v3 Pre-Release

.github/release.config.js
=> Update release config to allow minor semver increments on maintenance branch

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/deployment.yml, README.md, docs/Conformance Criteria/README-Conformance Criteria V2.md, docs/early-access/v2/Profile-Configuration.md, package.json, packages/zowe-explorer-api/README.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/README.md, packages/zowe-explorer-ftp-extension/docs/README.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/Jenkinsfile, packages/zowe-explorer/README.md, packages/zowe-explorer/package.json, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts, samples/menu-item-sample/package.json, samples/tree-view-sample/package.json, samples/uss-profile-sample/package.json
Update repo name in all GitHub links, except for in CHANGELOG.md - not sure if we want to touch the changelogs or keep them as-is for historical purposes 😋 
Also enables provenance for the Zowe Explorer API package - I think we meet all the requirements listed [here](https://docs.npmjs.com/generating-provenance-statements). After next time we publish with provenance enabled, we should see a green checkmark next to the version number on npmjs.org like this:
Milestone:
Changelog:
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for …
=> Update repo name in GitHub links and enable provenance for ZE API package

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts, packages/zowe-explorer/src/job/actions.ts
To fix submitted job hyperlink throwing error
Milestone:
Changelog:
=> Clicking submitted job hyperlink throws error

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/src/dataset/DatasetTree.ts
resolves #2181 
Changelog: Updated MVS view progress indicator for entering a filter search. [#2181](https://github.com/zowe/zowe-explorer-vscode/issues/2181)
=> Add progress indicator to mvs view for filterPrompt

lerna.json, package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/webpack.config.js, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/webpack.config.js, yarn.lock
Resolves technical currency by updating `socks` transitive dependency
Milestone: v1.22.7
Changelog: Update dependencies for technical currency purposes
=> Update v1 deps for technical currency

package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/webpack.config.js, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/ZoweNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts, packages/zowe-explorer/i18n/sample/package.i18n.json, packages/zowe-explorer/i18n/sample/src/dataset/ZoweDatasetNode.i18n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/package.nls.json, packages/zowe-explorer/resources/dark/fileError.svg, packages/zowe-explorer/resources/light/fileError.svg, packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts, packages/zowe-explorer/src/globals.ts, packages/zowe-explorer/src/shared/init.ts, packages/zowe-explorer/webpack.config.js, samples/uss-profile-sample/package.json, yarn.lock
Merge maintenance to main, with audit fix
Milestone: n/a
Changelog: n/a
=> Merge maintenance to main

.github/workflows/audit.yml, .github/workflows/changelog.yml, .github/workflows/circular-deps.yml, .github/workflows/deployment.yml, .github/workflows/lint.yml, .github/workflows/zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ftp-ci.yml, .github/workflows/zowe-explorer-samples.yml
Locks the `pnpm` version in CI to v9.
Milestone: 
Changelog:
=> [v3] ci: lock pnpm version to 9

.github/workflows/theia-zowe-explorer-ci.yml, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer/__tests__/__theia__/extension.theia.test.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts, packages/zowe-explorer/i18n/sample/package.i18n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/package.nls.json, yarn.lock
Fixes #2831
Milestone: 2.15.3
Changelog: Fixed an issue where `ProfilesCache` may return missing or incorrect profile values when multiple extensions call it during activation
=> Fix race condition in ProfilesCache refresh

packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/src/Profiles.ts
cherry pick #2828 and clean up CHANGELOGs for 2.15.3 release.
Milestone: 2.15.3
Changelog: n/a
=> Cherry pick 2828 & clean up

.github/workflows/theia-zowe-explorer-ci.yml, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__theia__/extension.theia.test.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts, packages/zowe-explorer/__tests__/__unit__/ZoweExplorerExtender.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts, packages/zowe-explorer/i18n/sample/src/shared/utils.i18n.json, packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/src/ZoweExplorerExtender.ts, packages/zowe-explorer/src/dataset/DatasetTree.ts, packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/job/ZoweJobNode.ts, packages/zowe-explorer/src/shared/utils.ts, packages/zowe-explorer/src/uss/USSTree.ts, packages/zowe-explorer/src/uss/actions.ts, yarn.lock
=> Update main branch with changes from 2.15.3

lerna.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md
prepare next v3 pre-release with latest work including tree work.
Changelog: n/a
=> v3 pre-release 4.24.24

packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer/src/webviews/package.json, packages/zowe-explorer/src/webviews/src/edit-attributes/App.tsx, packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentTableData.tsx, yarn.lock
Update dependencies for dependency audit and scanning purposes
* Replaces the unmaintained package `lodash.isequal` with `lodash` 
* Changes the deps of our eslint plugin to be dev deps
Milestone:
Changelog: N/A
=> [v2]: Update deps for technical currency

.github/workflows/zowe-explorer-ci.yml, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer/src/webviews/package.json, packages/zowe-explorer/src/webviews/src/edit-attributes/App.tsx, packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentTableData.tsx, pnpm-lock.yaml
Update dependencies for dependency audit and scanning purposes
* Replaces the unmaintained package `lodash.isequal` with `lodash` 
* Changes the deps of our eslint plugin to be dev deps
Milestone:
Changelog: N/A
=> [v3] Update deps for technical currency

.github/workflows/deployment.yml, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/eslint-plugin-zowe-explorer/package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts, packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts, packages/zowe-explorer/src/dataset/actions.ts, packages/zowe-explorer/src/webviews/package.json, packages/zowe-explorer/src/webviews/src/edit-attributes/App.tsx, packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentTableData.tsx, yarn.lock
**Note:** Also updates deployment workflow to add permissions `contents: write` for creating releases and `pull-requests: write` for creating PR comments.
Changelog: N/A
=> Update main branch with changes from 2.15.4

packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpJesApi.ts, packages/zowe-explorer/src/job/ZoweJobNode.ts
Milestone:
Changelog:
Fix issue #2832
=> No spool file available for active job

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__mocks__/vscode.ts, packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/globals.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/TempFolder.unit.test.ts, packages/zowe-explorer/src/globals.ts, packages/zowe-explorer/src/shared/init.ts, packages/zowe-explorer/src/shared/utils.ts, packages/zowe-explorer/src/utils/TempFolder.ts
Fixes #2880
Changelog: Fixed issue where saving changes to favorited PDS member fails when custom temp folder is set on Windows
=> Normalize case of temp folder path to fix undefined node error

packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
This is a port of the SHA256 change for the main branch.
Milestone: 
Changelog:
=> port(ftp): Use `sha256` instead of `sha1`

.github/workflows/zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ftp-ci.yml, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Jes/ZoweExplorerFtpJesApi.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
This is a port of the SHA256 change for the v1-lts branch. This PR also:
* Fixes unit tests that were failing to run in Node 20
* Pins workflows to use x64 version of MacOS
Milestone:
Changelog:
=> port(v1/ftp): Port sha256 change to v1-lts

packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/uss/UssFSProvider.ts, packages/zowe-explorer/src/uss/ZoweUSSNode.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fixes 4 code smells detected by Coverity in the v3 branch
Milestone:
Changelog:
=> Fix Coverity code smells in v3

.husky/commit-msg
Fixes zowe/zowe-clI#2094
Milestone:
Changelog:
=> [v2] Fix pre-commit script to support Git worktrees

.husky/commit-msg
Ports #2897 to the v1-lts branch
Milestone:
Changelog:
=> [v1] Fix pre-commit script to support Git worktrees

.husky/commit-msg
Ports #2897 to the next branch
Milestone:
Changelog:
=> [v3] Fix pre-commit script to support Git worktrees

package.json, packages/zowe-explorer-api/package.json, packages/zowe-explorer-api/src/Types.ts, packages/zowe-explorer-api/src/fs/types/datasets.ts, packages/zowe-explorer-api/src/fs/types/jobs.ts, packages/zowe-explorer-api/src/fs/types/uss.ts, packages/zowe-explorer-api/src/fs/utils/abstract.ts, packages/zowe-explorer-api/src/fs/utils/datasets.ts, packages/zowe-explorer-api/src/fs/utils/jobs.ts, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer/l10n/bundle.l10n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/src/webviews/package.json, pnpm-lock.yaml
Ports #2900 to the next branch and fixes #2903
TODO
Milestone:
Changelog:
=> [v3] Update pnpm lockfile for technical currency

package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer/i18n/sample/src/utils/CertificateWizard.i18n.json, samples/uss-profile-sample/package.json, yarn.lock
Fixes #2633 by updating Zowe CLI dependency on the ZE API package
Changelog: Updated `@zowe/cli` dependency to fix issue where "Log out of authentication service" doesn't show in Manage Profile menu
=> Update CLI dependency to fix missing APIML log out option

package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, samples/uss-profile-sample/package.json, yarn.lock
Updates Zowe CLI to 7.26.0 for vulnerability fix
Milestone: 2.16.2
Changelog: Update dependencies for technical currency purposes.
=> Update Zowe dependencies

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts, packages/zowe-explorer/src/dataset/actions.ts
Port changes from PR #2942 to maintenance for 2.16.2
Milestone:
Changelog:
=> Port #2942 to maintenance

lerna.json, package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/package.json, yarn.lock
Milestone: 1.22.8
Changelog: Update dependencies for technical currency purposes
=> Update CLI dependencies for v1-lts

package.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/SpoolProvider.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts, packages/zowe-explorer/i18n/sample/src/job/actions.i18n.json, packages/zowe-explorer/src/SpoolProvider.ts, packages/zowe-explorer/src/job/actions.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts, samples/uss-profile-sample/package.json, yarn.lock
port 2.16.2 changes from maintenance to main
Milestone: n/a
Changelog: n/a
=> Port 2.16.2 to Main

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts, packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
Port changes of #2942 to next
Milestone:
Changelog:
=> Port #2942 to next

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/WebView.unit.test.ts, packages/zowe-explorer-api/package.json, packages/zowe-explorer-api/src/vscode/ui/WebView.ts, packages/zowe-explorer-api/src/vscode/ui/utils/HTMLTemplate.ts, yarn.lock
Uses the `mustache` dependency instead of `handlebars` to minimize dependency count.
Milestone: 2.17.0
Changelog:
Removed `handlebars` dependency in favor of `mustache` for technical currency purposes.
**General**
**Deployment**
=> refactor: Use Mustache instead of Handlebars

lerna.json, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts, packages/zowe-explorer/src/dataset/actions.ts
Fixes invalid logic for getting profile name of USS path and replaces it with code that matches vNext behavior
Milestone: 2.16.3?
Changelog: Fixed issue where USS files could not be submitted as JCL
**General**
**Deployment**
=> Fix issue where USS files can't be submitted as JCL

.github/workflows/theia-zowe-explorer-ci.yml, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__theia__/theia/Locators.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts, packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts, packages/zowe-explorer/src/dataset/actions.ts
Port changes from maintenance 2.16.2 & 2.16.3 releases.
Milestone: n/a
Changelog: n/a
**General**
**Deployment**
=> Port 2.16.3 to main

package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/webpack.config.js, packages/zowe-explorer/webpack.config.js, samples/uss-profile-sample/package.json, yarn.lock
Resolves #3003
Milestone: 2.17.0
Changelog: Updated the `@zowe/cli` dependency to 7.27.0 to support proxy environment variables
**General**
**Deployment**
=> Update Zowe CLI dependency to 7.27.0

.github/workflows/codeql.yml
Updates the CodeQL action to version 3, which will continue to have support after December 2024
Milestone: N/A
Changelog: N/A
**General**
**Deployment**
=> Update CodeQL Workflows to v3 [v2]

.github/workflows/circular-deps.yml, .github/workflows/codeql.yml
Updates checkout and node setup actions in Circular Dependencies workflow to avoid deprecation warning
Updates CodeQL action version to v3 for support after December 2024
Milestone: N/A
Changelog: N/A
**General**
**Deployment**
=> Update Circular Dependencies and CodeQL Workflows [v3]

.github/release.config.js, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/README.md, packages/zowe-explorer-ftp-extension/docs/README.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer-ftp-extension/resources/conformance/test_evaluation_guide_table.md, packages/zowe-explorer/CHANGELOG.md
Rename the zFTP extension to `IBM z/OS FTP for Zowe Explorer`
Changelog: Renamed extension 😋 
**General**
**Deployment**
=> Rename zFTP extension

package.json, samples/vue-webview-sample/package.json, samples/vue-webview-sample/webviews/vue-sample/package.json, samples/vue-webview-sample/webviews/vue-sample/yarn.lock, samples/vue-webview-sample/yarn.lock, yarn.lock
Resolves Dependabot alerts for the main branch 😁 
Milestone:
Changelog:
**General**
**Deployment**
=> Update dependencies for technical currency

packages/zowe-explorer-api/src/vscode/ui/WebView.ts, packages/zowe-explorer-api/src/vscode/ui/utils/HTMLTemplate.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts, packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts, packages/zowe-explorer/__tests__/__unit__/zosconsole/ZosConsolePanel.unit.test.ts, packages/zowe-explorer/package.json, packages/zowe-explorer/src/webviews/src/zos-console/App.tsx, packages/zowe-explorer/src/zosconsole/ZosConsolePanel.ts, yarn.lock
Fixes #3053
Changelog: N/A
**General**
**Deployment**
=> fix(console): Fix codicons in Theia and improve error handling

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/src/webviews/package.json, packages/zowe-explorer/src/webviews/src/edit-attributes/App.tsx, packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentTableData.tsx, pnpm-lock.yaml
The use of `lodash` is frowned upon due to its bundle size - using `es-toolkit` helps to [reduce the total bundle size](https://es-toolkit.slash.page/bundle-size.html#bundle-footprint) and also [offers performance benefits](https://es-toolkit.slash.page/performance.html#performance-comparison) over `lodash`. It also is designed to work well with tree shaking and offers TypeScript support out-of-the-box.
Milestone:
Changelog:
**General**
**Deployment**
- …
=> deps: Use `es-toolkit` instead of `lodash` in webviews for tech. currency

package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts, packages/zowe-explorer-api/package.json, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/abstract/ZoweCommandProvider.unit.test.ts, packages/zowe-explorer/src/Profiles.ts, packages/zowe-explorer/src/shared/refresh.ts, samples/uss-profile-sample/package.json, yarn.lock
Fixes #3066
Changelog: Fixed JSON errors being ignored when `zowe.config.json` files change on disk and are reloaded
**General**
**Deployment**
=> Fix JSON errors are ignored when config files change on disk

.github/release.config.js, .github/workflows/deployment.yml, lerna.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
Prepares `main` for release automation to publish `v2.18.0`.
**General**
=> release: `v2.18.0`

.github/release.config.js
Updates the `release.config.js` file for v3:
- Changes `release/2.*` branch pattern to publish on the `zowe-v2-lts` channel
- Adds `release/3.*` branch pattern to publish v3 releases to the `latest` channel
**General**
=> chore(v3): Update `release.config.js`

.github/release.config.js, lerna.json, packages/zowe-explorer/l10n/bundle.l10n.json
add next back to release.config
Changelog: n/a
**General**
**Deployment**
=> [v3] add next back to release.config

.github/workflows/auto-comment.yml, .github/workflows/update-project.yml
Fixes new issue autoresponder & automatic labeling
Fixes automatic movement of team project board items (PRs into Review/QA)
Milestone: N/A
Changelog: N/A
**General**
**Deployment**
=> Fix: Add missing workflow permissions (main)

package.json, samples/menu-item-sample/yarn.lock, samples/tree-view-sample/yarn.lock, samples/uss-profile-sample/yarn.lock, samples/vue-webview-sample/yarn.lock, yarn.lock
Also resolves several Dependabot alerts in dev deps
Milestone:
Changelog:
**General**
**Deployment**
=> Update function-bind dep for technical currency

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__mocks__/vscode.ts, packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerExtender.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts, packages/zowe-explorer/src/configuration/Profiles.ts, packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts, packages/zowe-explorer/src/utils/ProfilesUtils.ts
Port of:
- #3075
Milestone: Fix ZE activation and commands failing when team config contains JSON error
Changelog: V3.0.0-prerelease
**General**
**Deployment**
=> chore(v3): Fix ZE activation and commands failing when team config contains JSON error

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/src/commands/UnixCommandHandler.ts, packages/zowe-explorer/src/utils/AuthUtils.ts
Fix issue #2901
Handle error received with outdated SSH credentials stored securely in SSH profile, by prompting to update credentials.
Milestone:
Changelog:
**General**
**Deployment**
=> Prompt to update credentials when outdated credentials stored securely in SSH profile

.github/release.config.js
Milestone:
Changelog:
**General**
**Deployment**
=> Update release.config.js to set channel for prerelease build

.github/workflows/deployment.yml
Updating something in the workflow to make sure it triggers. 😢 
Again, sorry for the oversight 😿
=> chore: update workflows to trigger deployment of v1

.github/workflows/deployment.yml
Milestone:
Changelog:
**General**
**Deployment**
=> [v1] Update secrets and permissions in deployment workflow

.github/release.config.js, .github/workflows/deployment.yml
Milestone:
Changelog:
**General**
**Deployment**
=> [v2] Prepare deployment workflow for V2 patch releases

packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts, packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts, packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts, packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts, packages/zowe-explorer/src/trees/job/ZoweJobNode.ts, packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts, packages/zowe-explorer/src/utils/AuthUtils.ts
Fixes profile dereferencing to eliminate need to propagate profile object across child nodes and FSProvider entries.
Related to #3157 and #3197
Milestone:
Changelog:
**General**
**Deployment**
=> fix(api): Fix profile references being lost when cache is refreshed

packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
polish changelogs and try to kick off deployment
Milestone:
Changelog:
**General**
**Deployment**
=> polish changelogs 

lerna.json
Milestone:
Changelog:
**General**
**Deployment**
=> trigger deployment with dummy change to lerna

packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
=> chore: update changelogs for main w/ v3.0.2 content

packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer-ftp-extension/webpack.config.js, packages/zowe-explorer/l10n/bundle.l10n.json, packages/zowe-explorer/l10n/poeditor.json, packages/zowe-explorer/package.json, packages/zowe-explorer/webpack.config.js
technical debt:  updates to webpack for ZE and FTP4ZE to support the passing of --mode development that should be used with the VSC launch tasks for easier debugging for developers allowing ease of recognition of the variables shared. Change to build command from dev to prod was to keep building and packaging locally the same as before with minifying.
How variables look on main now with debugger due to minimization
How variables look with these changes in debugger with --mode development passed and recognized with `watch:zowe-explorer`
Thanks for helping with issue seen @rudyflores 
Milestone: n/a
Changelog: n/a tech debt
**General**
**Code …
=> Updates to webpack and package.json scripts for minimization

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts, packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts, packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerZosmfApi.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/extending/__snapshots__/ZoweExplorerZosmfApi.unit.test.ts.snap
Fixes the issue where the `responseTimeout` property was ignored during MVS and USS API calls when using z/OSMF profiles. 
Milestone: 3.0.3
Changelog:
- Fixed an issue where the `responseTimeout` profile property was ignored for z/OSMF MVS and USS API calls. #3225 
**General**
**Deployment**
=> fix(v3): Pass `responseTimeout` in z/OSMF MVS and USS API calls

packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
Update changelogs after 3.0.3 per [Release documentation](https://github.com/zowe/zowe-explorer-vscode/releases)
Milestone: n/a
Changelog: n/a
**General**
**Deployment**
=> Update changelogs after 3.0.3

.github/workflows/codeql.yml, .github/workflows/zowe-explorer-ci.yml, packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts, packages/zowe-explorer/src/trees/dataset/DatasetInit.ts, packages/zowe-explorer/src/utils/AuthUtils.ts, pnpm-lock.yaml
We can switch back to `ubuntu-latest` in our workflows now as GitHub has fixed the issues with the Ubuntu 24 image 😋 
Milestone:
Changelog:
**General**
**Deployment**
=> Update workflows and deps for technical currency

.github/workflows/codeql.yml, .github/workflows/zowe-explorer-ci.yml, yarn.lock
Ports #3373 to the v2-lts branch
Milestone:
Changelog:
**General**
**Deployment**
=> [v2] Update workflows and deps for technical currency

.github/workflows/audit.yml, .github/workflows/auto-comment.yml, .github/workflows/changelog.yml, .github/workflows/circular-deps.yml, .github/workflows/codeql.yml, .github/workflows/deployment.yml, .github/workflows/lint.yml, .github/workflows/merge-by-comments.yml, .github/workflows/merge-by-table.yml, .github/workflows/stale.yml, .github/workflows/update-project.yml, .github/workflows/zowe-explorer-ci.yml, .github/workflows/zowe-explorer-ftp-ci.yml
Downgrades runners to `ubuntu-22.04` to fix issues with `glibc`
Changelog: N/A
=> chore: downgrade ubuntu runners to ubuntu-22.04

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/trees/uss/USSInit.unit.test.ts, packages/zowe-explorer/src/trees/uss/USSActions.ts, packages/zowe-explorer/src/trees/uss/USSInit.ts
Resolves https://github.com/zowe/zowe-explorer-vscode/issues/2796
Milestone:
Changelog:
- Fixed issue where the 'Delete' key binding for the USS tree returns a 'contextValue' error. [#2796](https://github.com/zowe/zowe-explorer-vscode/issues/2796)
**General**
**Deployment**
=> fix: Pass TreeView selection when node is undefined

packages/zowe-explorer/src/webviews/package.json, pnpm-lock.yaml
Milestone:
Changelog:
**General**
**Deployment**
=> Update dev deps to resolve Dependabot alerts

packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts, packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
Ports #3428 to the `release/3.1` branch in preparation for a 3.1.1 release.
- Also fixes [issue spotted in #3421](https://github.com/zowe/zowe-explorer-vscode/pull/3421#issuecomment-2627551682)
Milestone: 3.1.1
Changelog:
- Fixed an issue where a TypeError occurred when applying VS Code proxy settings to an invalid session.
**General**
**Deployment**
=> Port #3428 into `release/3.1` (prep for 3.1.1 release)

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/commands/MvsCommandHandler.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/commands/TsoCommandHandler.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/commands/UnixCommandHandler.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts, packages/zowe-explorer/src/commands/ZoweCommandProvider.ts
Fixes #3422 
Also adds test case for cancelled command.
Milestone:
Changelog: Fixed issue where cancelling Unix, MVS or TSO command still submits the command
**General**
**Deployment**
=> Fix cancelling MVS/TSO command causing error

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/src/trees/shared/SharedHistoryView.ts, packages/zowe-explorer/src/webviews/src/edit-history/App.tsx, packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentDataPanel.tsx
Ports #3441 to the release/3.1 branch in preparation for a 3.1.2 patch release.
Changelog: Fixed a bug where edit history does not show the correct information.
**General**
**Deployment**
=> Port #3441 into release/3.1

packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts, packages/zowe-explorer/src/trees/job/JobTree.ts
Ports https://github.com/zowe/zowe-explorer-vscode/pull/3438 to the release/3.1 branch in preparation for a 3.1.2 patch release.
Milestone:
Changelog:
**General**
**Deployment**
=> Port #3438 into release/3.1

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts, packages/zowe-explorer/src/trees/job/JobFSProvider.ts, packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Fixes #3504 for V3
Changelog: Fixed an issue where profile encoding is not respected when opening job spool files
**General**
**Deployment**
=> fix(jobs): Respect profile encoding when opening spool files

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts, packages/zowe-explorer-api/src/profiles/AuthHandler.ts, packages/zowe-explorer-api/src/vscode/ui/TableViewProvider.ts, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/__mocks__/@zowe/zowe-explorer-api.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/FtpApi/ZoweExplorerAbstractFtpApi.unit.test.ts, packages/zowe-explorer-ftp-extension/__tests__/__unit__/extension.unit.test.ts, packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts, packages/zowe-explorer-ftp-extension/src/extension.ts, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts, packages/zowe-explorer/src/trees/dataset/DatasetActions.ts, packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts, packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts, packages/zowe-explorer/src/trees/job/JobTableView.ts, packages/zowe-explorer/src/trees/shared/SharedInit.ts, packages/zowe-explorer/src/trees/uss/UssFSProvider.ts, packages/zowe-explorer/src/utils/AuthUtils.ts, packages/zowe-explorer/src/webviews/src/table-view/types.ts
Ports my recent bug fixes: #3456, #3473, #3479, #3480, #3503 
Also ports #3457 
**General**
**Deployment**
=> ports: recent bug fixes for 3.1.2 release

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/README.md, packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts, packages/zowe-explorer/package.json, packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
Added "Copy Name" option to VSAM data sets in the tree view.
Milestone:
Changelog:
Added a "Copy Name" context option for VSAM data sets in the tree view.
**General**
**Deployment**
=> Added "Copy Name" option to VSAM data sets

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts, packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts, packages/zowe-explorer/src/configuration/Constants.ts, packages/zowe-explorer/src/trees/ZoweTreeProvider.ts, packages/zowe-explorer/src/utils/AuthUtils.ts
Fixes an issue where the profile expiration check had continued executing for profiles that do not explicitly support tokens through their API implementations.
Changelog:
- Fixed an issue where the token expiration check was performed on profiles whose APIs do not support a token type
**General**
**Deployment**
=> fix: Only check if token has expired when profile's API supports it

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts, packages/zowe-explorer/src/configuration/Profiles.ts
Performs certificate based authentication for zosmf profile given certificate file and certificate key file.
Solves https://github.com/zowe/zowe-explorer-vscode/issues/2373
Milestone:
Changelog:
**General**
**Deployment**
=> To provide client side certificate support for zosmf

lerna.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md
Prepare 2.18.1 release
Changelog: n/a
**General**
**Deployment**
=> Prepare 2.18.1 release

pnpm-lock.yaml
Restores updates made to dev deps for technical currency. These changes were made in #3559, but seem to have been accidentally reverted as the vulnerabilities have reappeared in Dependabot scans.
Milestone:
Changelog:
**General**
**Deployment**
=> Rebuild lockfile to update dev deps

README.md
Make it clear in README that user must install PNPM 8.x. 
https://openmainframeproject.slack.com/archives/CUVE37Z5F/p1743507513714599?thread_ts=1740267241.780299&cid=CUVE37Z5F
Milestone:
Changelog: N/A
**General**
**Deployment**
=> Make it clear in README that user must install PNPM 8.x

package.json, packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/package.json, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer-ftp-extension/package.json, packages/zowe-explorer-ftp-extension/src/ftpSession.ts, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts, packages/zowe-explorer/i18n/sample/src/shared/utils.i18n.json, packages/zowe-explorer/package.json, packages/zowe-explorer/src/shared/utils.ts, yarn.lock
Update SDKs to get the latest fixes around numeric encoding
Milestone: 2.18.3 (since Zowe released a 2.18.2 for Client side components) 😋 
Changelog: 
- Updated dependencies for technical currency purposes. [#3577](https://github.com/zowe/zowe-explorer-vscode/pull/3577)
**General**
**Deployment**
This is the equivalent CLI PR:
- …
=> V2: chore: update SDKs to address numeric encoding issue

.github/workflows/stale.yml
Fixes the stale bot only flagging issues as stale if they already contain the label "needs more info" or "pending closure".
Milestone:
Changelog:
**General**
**Deployment**
=> Fix stale bot ignoring most issues

.github/workflows/stale.yml
Milestone:
Changelog:
**General**
**Deployment**
=> chore: update stale config options

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
Modified zowe-explorer-vscode\packages\zowe-explorer\src\extending\ZoweExplorerExtender.ts to import ILocalStorageAccess from "@zowe/zowe-explorer-api" instead of from the source directory "@zowe/zowe-explorer-api/src/extend/ILocalStorageAccess".
This PR closes issue #3606
Changelog:  Replaced an import of ILocalStorageAccess from "@zowe/zowe-explorer-api/src/extend/ILocalStorageAccess" to "@zowe/zowe-explorer-api" [#3606](https://github.com/zowe/zowe-explorer-vscode/issues/3606)
**General**
**Deployment** …
=> Replace import from source to import from module

packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts, packages/zowe-explorer/src/utils/AuthUtils.ts
Add extra validation to make a hostname validation error appear.
Changelog:
**General**
**Deployment**
=> Fix a situation where hostname validation caused the host cannot be blank error to appear

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts, packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Extenders that may add `base` or `ssh` to the profile cache type array will result in duplicate nodes for ssh or base profile types when adding a profile to a tree.
Adding an ssh profile from an extender before the fix:
This fix changes the profile types to a set to avoid duplicate types and thus duplicate nodes
Adding an ssh profile from an extender after the fix:
Milestone:
Changelog:
**General**
**Deployment**
- Otherwise, please check with the rest of …
=> Fix duplicate nodes when adding profiles

packages/zowe-explorer-api/CHANGELOG.md, packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
Fix to https://github.com/zowe/zowe-explorer-vscode/issues/3647
Changelog:
- Fixed error message shown when creating a config file that already exists.
**General**
**Deployment**
=> Fix missing message insert for overwriting config file

.github/PULL_REQUEST_TEMPLATE.md
Per discussion in retrospective:
This adds a PR checklist item for enhancements to be tested with the FTP extension and profile to verify no breakages introduced for extenders.
Milestone: n/a
Changelog: n/a
**General**
**Deployment**
=> Add PR checklist item to test new functionality with FTP extender type

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts, packages/zowe-explorer/src/configuration/Profiles.ts
Fixes https://github.com/zowe/zowe-explorer-vscode/issues/3654
Milestone:
Changelog:
**General**
**Deployment**
=> Fix: Switch Auth Method misbehaviour

lerna.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md, packages/zowe-explorer-ftp-extension/CHANGELOG.md, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts, packages/zowe-explorer/src/configuration/Profiles.ts
Prepare 3.2.1 patch release
Milestone: 3.2.1
Changelog: n/a
**General**
**Deployment**
=> Prepare 3.2.1 release

packages/zowe-explorer-api/__tests__/__unit__/fs/BaseProvider.unit.test.ts, packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/trees/job/JobInit.unit.test.ts
Port 3.2.1 release to main
Milestone:
Changelog:
**General**
**Deployment**
=> Port 3.2.1 release to main

package.json, yarn.lock
Sets a resolution for `tar-fs` to resolve a vulnerability with `vsce`
Milestone:
Changelog: N/A
**General**
=> chore(v2): set resolution for `tar-fs` to resolve vuln in dev dep (`vsce`)

.github/workflows/update-project.yml, yarn.lock
Fixes non-draft PRs being categorized as In Progress rather than Ready for Review. The change doesn't take effect until merged.
=> ci(v2): Fix GH project status for pull requests

.github/workflows/update-project.yml, pnpm-lock.yaml
Fixes non-draft PRs being categorized as In Progress rather than Ready for Review. The change doesn't take effect until merged.
=> ci(v3): Fix GH project status for pull requests

packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts, pnpm-lock.yaml
Milestone:
Changelog:
**General**
**Deployment**
=> Update dev deps to fix npm audit

lerna.json, packages/eslint-plugin-zowe-explorer/CHANGELOG.md
prepare 2.18.2 release, update lerna and changelogs.  
Changelog: n/a
**General**
**Deployment**
=> Prepare 2.18.2 release

packages/zowe-explorer-api/src/vscode/ui/TableView.ts, packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTableView.unit.test.ts, packages/zowe-explorer/src/trees/dataset/DatasetTableView.ts, packages/zowe-explorer/src/webviews/src/table-view/ActionUtils.ts, packages/zowe-explorer/src/webviews/src/table-view/ActionsBar.tsx, packages/zowe-explorer/src/webviews/src/table-view/ContextMenu.tsx, packages/zowe-explorer/src/webviews/src/table-view/ContextMenuItem.tsx
Adds Pin/Unpin to the context menu
Follow-up from #3751 
Changelog:
N/A (new feature not out yet)
**General**
**Deployment**
=> refactor(ds/table): Add Pin/Unpin to context menu

packages/zowe-explorer/src/webviews/package.json, pnpm-lock.yaml
Milestone:
Changelog:
**General**
**Deployment**
=> Update dev dependencies for technical currency

package.json, packages/zowe-explorer/package.json, pnpm-lock.yaml
Also:
* Fixes #3868 - previously I updated directly from pnpm@8 to 10 which seemed to update dependencies in the lockfile without asking. Updating from 8 to 9 before 10 seems to have rebuilt the lockfile more safely.
* Removes dependency on Internet connection for ZE build - `pnpm dlx` always downloads package, `pnpm exec` runs npm bin script.
Milestone:
Changelog:
**General**
**Deployment**
- Otherwise, please check with the rest of the squad about any …
=> Update dev deps for technical currency

pnpm-lock.yaml
Milestone:
Changelog:
**General**
**Deployment**
=> Update `tar-fs` transitive dependency for audit

package.json, yarn.lock
Milestone:
Changelog:
**General**
**Deployment**
=> Update `tar-fs` transitive dependency for audit [v2]

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts, packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
Fixes #3856 where attributes other than the member name were no longer shown in the Show Attributes view after v3.3.0.
Milestone: 3.3.1
Changelog:
- Fixed regression where PDS member attributes were no longer listed when using the "Show Attributes" feature from the context menu.
**General**
**Deployment**
=> fix: include member attributes in Show Attributes view

packages/zowe-explorer/CHANGELOG.md, packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts, packages/zowe-explorer/src/trees/shared/SharedInit.ts
When we run the manual poll command, we check that the active editor is a spool file. I think the logic is outdated - possibly relating to an old way of interacting with z/OSMF.
Updating the logic to use existing code from elsewhere.
Resolves https://github.com/zowe/zowe-explorer-vscode/issues/3867
Fixed job spool poll command to refresh the job spool open in the editor. 
Milestone:
Changelog:
Fixed job spool poll command to refresh the job spool open in the editor. 
**General**
**Deployment** …
=> check for job spool correctly
