- src/extension.ts
Resolves #25 by using the `.zowe` directory in the users home directory as the location for the profiles.
Signed-off-by: Andrew Smithson <smithson@uk.ibm.com>
> Load profile information from the right location

- __tests__/ZoweNode.test.ts
- src/ZoweNode.ts
Resolves #3 by adding information nodes to a session when it is first added to indicate a search should be performed, and then if the search returns an empty list of datasets a message to indicate this has happened.
> Add information messages in sessions nodes

- __mocks__/@brightside/imperative.ts
- __tests__/extension.test.ts
- src/extension.ts
One test is failing because we don't mock the log.getAppLogger function
https://github.com/zowe/vscode-extension-for-zowe/issues/54
> Add logger mock

- __tests__/extension.test.ts
- package.json
- src/ZoweUSSNode.ts
- src/extension.ts
Resolves #57 as a workaround.
Adds a new menu item which allows to toggle between downloading the file
as text which will do data conversion even if the file doesn't require it
or binary which will just get the contents of the file allowing editing
of non EBCDIC files in an editor.
> Toggle download as binary to avoid conversion

- CHANGELOG.md
- __tests__/extension.test.ts
- package.json
- src/extension.ts
- src/zosjobs.ts
Resolves #68
1. Add a delete session menu item for sessions in the jobs view
2. Prevent the delete menu item for USS files and directories appearing on the context menu for sessions
> Fix context menu items for Jobs and USS sessions

- CHANGELOG.md
- __tests__/ProfileLoader.test.ts
- __tests__/extension.test.ts
- package.json
- src/extension.ts
Resolves #77
Add a download menu item inline on jobs which allows the user to specify a directory where all the spool content is downloaded.
> Add command to download all Spool content

- CHANGELOG.md
- package.json
- src/extension.ts
Attempt to deal with #76  (unknown if this will fix the issue for users) by comparing the temporary data set directory case insensitively
Also `await` functions used in safeSave(). Maybe there was a bit of a race condition
> compare data set path case insensitively - attempted resolution for #76

- .vscodeignore
- CHANGELOG.md
- __tests__/ZoweNode.test.ts
- package.json
- src/ProfileLoader.ts
In order to debug issues loading profiles more, I added the stderr of the getDefaultProfile or getAllProfiles process to display in the error message to the user. This should make it easier to debug issues loading profiles
> display stderr of profile process if we fail to retrieve profiles

- __tests__/extension.test.ts
- __tests__/zosjobs.test.ts
- __tests__/zosspool.test.ts
- src/extension.ts
- src/zosjobs.ts
Resolves #80 by adding new tests for the functionality that shows jobs and spool content.
> Add tests for jobs and spool processing

- CHANGELOG.md
- __tests__/extension.test.ts
- __tests__/integrationTests/extension.test.ts
- __tests__/uss/ussNodeActions.test.ts
- package.json
- src/ZoweNode.ts
- src/extension.ts
- src/uss/ussNodeActions.ts
- src/zosjobs.ts
Fixes #82 by specifically handling the `undefined` response from QuickPick input prompts in VS Code, rather than incorrectly assuming the first response in the list of options was selected
>  Handle undefined response from QuickPicks

- __tests__/USSTree.test.ts
- __tests__/extension.test.ts
- __tests__/integrationTests/extension.test.ts
- __tests__/uss/ussNodeActions.test.ts
- package.json
- src/USSTree.ts
- src/ZoweUSSNode.ts
- src/extension.ts
- src/uss/ussNodeActions.ts
- src/utils.ts
Add basic favorite functionality for USS explorer:
- Add files and directories as favorites
- Remove files and directories from favorites
- Expand favorited directories and open favorited files
- Sanitize search input starting with more than one slash
- Unit tests for the added functionalities
Related issues:
- #37 (Introduce Favorites functionality to USS extension)
- zowe/zowe-cli#297 (VSCode USS File extension - Favorites)
> USS Favorites

- __tests__/extension.test.ts
- package.json
- src/extension.ts
Resolves #81 by adding a menu item to jobs allowing the user to get the JCL.
Enhances the ability to submit JCL by allowing the content of any editor to be submitted by providing a list of available profiles to use to submit the Job if it can't be determined programatically.
Exploits the functionality made available in the [April 2019 release](https://code.visualstudio.com/updates/v1_34#_command-links-in-notifications) to provide a link in the information message which will open the spool for the newly submitted job.
> JCL Submission improvements

- CHANGELOG.md
- README.md
- package.json
Resolves #100
Add markdown linting to the prepublish steps and apply the linting to the CHANGELOG and README markdown files.
> Markdown linting

- README.md
- __mocks__/fs-extra.ts
- __mocks__/vscode.ts
- __tests__/extension.test.ts
- __tests__/integrationTests/extension.test.ts
- package-lock.json
- package.json
- src/extension.ts
Issue Number: #97
Adds preference to specify temp directory. In order change the temp folder location, add below to preferences.
```
"Zowe-Temp-Folder-Location": {
"folderPath": "/path/to/directory"
}
```
If no folder is specified, it will default to resource folder used now.
> Preference to Specify Temp Folder

- __tests__/extension.test.ts
- src/extension.ts
Resolves #123
The saveUss function will now correctly determine if a file is binary for saving.
> Correctly determine if file is binary for saving

- __tests__/DatasetTree.test.ts
- __tests__/ProfileLoader.test.ts
- __tests__/USSTree.test.ts
- __tests__/integrationTests/DatasetTree.test.ts
- __tests__/integrationTests/USSTree.test.ts
- __tests__/zosjobs.test.ts
- src/DatasetTree.ts
- src/ProfileLoader.ts
- src/USSTree.ts
- src/extension.ts
- src/zosjobs.ts
Addresses issue #133 (Massive error message when user has no Zowe profile defined)
**Summary:**
Replaces this massive error message:
With this much more user-friendly information message:
**Details:**
- The blue text links to Zowe's documentation on how to create a Zowe CLI profile: https://zowe.github.io/docs-site/latest/user-guide/cli-configuringcli.html#creating-zowe-cli-profiles
- If the user wishes to do additional debugging, the stack trace is now logged in zowe.log (where the rest of the Zowe VS Code extension's error/debug messages go).
- The main change in this PR is just in ProfileLoader.ts, but quite a few other files had to also be touched because adding logging for `loadDefaultProfile` requires passing the `log` object down multiple functions in different files, and updating …
> Default profile error

- __tests__/ProfileLoader.test.ts
- src/DatasetTree.ts
- src/ProfileLoader.ts
- src/USSTree.ts
- src/zosjobs.ts
When no profile is defined at all it should not throw an error, but instead the addSession() method should do nothing.
Signed-off-by: Peter Haumer <phaumer@us.ibm.com>
> Fixed case of no default profile present, yet

- __tests__/__unit__/extension.unit.test.ts
- i18n/sample/src/extension.i18n.json
- package-lock.json
- package.json
- package.nls.json
- src/extension.ts
Allow the user to submit a TSO command and view the response from VS Code.
'Zowe: Issue TSO Command ...' is available from the command palette. This then prompts the user to select the profile to use and then the command to issue. As a convenience function a leading / is removed from the command if present.
The results of the command are sent to a new OutputChannel (along with the command) making it easier for the user to review the output.
Signed-off-by: Andrew Smithson <smithson@uk.ibm.com>
> Add command to issue tso command

- src/DatasetTree.ts
- src/USSTree.ts
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com> Unfortunately the hack to force nodes to refresh is changing the label. This adds a blank or removes it from the label causing the node to repaint. The knock on effect is that every place you are doing a label compare you need a trim(). One place I had missed. 
Another consequence of this bug was that it indicated that when removing a session the node remained. The solution was to perform a higher level refresh.
> trim for compares - Review first as other PR has version increment

- CHANGELOG.md
- package.json
- src/extension.ts
Issue caused while rationalizing the number of duplicated fields. In USS files the session label has the filter path alongside it. So in this case only the duplicated mLabel and label fields were not the same.
This will be a quick fix for now and I intend to completely review the duplicated fields as another Issue
> Check profile name

- README.md
- i18n/sample/src/ProfileLoader.i18n.json
- src/ProfileLoader.ts
Signed-off-by: Lauren Li <Lauren.Li@ibm.com>
Related to issues #155 (No default zosmf profile found for ZOWE CLI) and #133 (Massive error message when user has no Zowe profile defined):
- Provides updated documentation links for creating a Zowe CLI profile
- Provides updated install instructions for Zowe CLI on the PC.
> Update documentation URLs

- __tests__/__integration__/extension.integration.test.ts
Issue seems to be that there are conflicts between tree views set up in the before sections and running in it sections. This fix has separated out the problem dataset test but the real solution is about moving the tests out of this monolithic file. 
I am intending to do that anyway as part of the restructuring. The USS equivalent test is passing simply because it isn't working correctly and testing what is needed. It ain't broke so I didn't fix it but will look at it again when I restructure the tests
Fixes #237
> Separate out test from main extensions

- __tests__/__unit__/extension.unit.test.ts
- src/extension.ts
The error needs to be rethrown to be reported.
> Make sure the error is thrown and reported

- __tests__/__unit__/uss/ussNodeActions.unit.test.ts
- package-lock.json
- src/USSTree.ts
- src/ZoweUSSNode.ts
- src/uss/ussNodeActions.ts
Need to be able to handle favorites. Although rename should be about changing just the label and not the folder it appeared in I allowed a degree of freedom with the path name. so ../temp/newtartget.txt is handled. 
Anything more and I think we should be atlking about a move operation
> Reworked the rename USS feature

- __tests__/__integration__/USSTree.integration.test.ts
- src/USSTree.ts
Tes relied on settings.json not having persisted entries or maybe one at most. This fix changes the logic in the test to remove a profile that has been added automatically and then adds it back again
> Broken test erratic results

- __tests__/__unit__/__snapshots__/extension.unit.test.ts.snap
- package.json
This PR addresses issue #369 ("Copy Data Set" and "Paste Data Set" listed twice in Data Set context menu):
- Remove duplicate commands 
- Update unit test snapshot for menu items
> Remove duplicate commands

- src/ZosJobsProvider.ts
Added the rather horrible labelHack to the Jobs tree so that the session node will have the label subtley changed and therefore vscode decides to refresh it. Without this VSCode thinks it's the same object that hasn't changed so would only refresh if manually pressing the expand button.
> Add Label hack

- __mocks__/@brightside/imperative.ts
- __tests__/__unit__/KeytarCredentialManager.unit.test.ts
- i18n/sample/src/extension.i18n.json
- package-lock.json
- src/KeytarCredentialManager.ts
- src/extension.ts
This PR adds support for profiles created with any version of the SCS plugin, without needing to have a credential key configured in VSCode settings.
The `KeytarCredentialManager` checks for credentials stored securely under any of the following IDs which have been used over time:
* `Zowe-Plugin`
* `@brightside/core`
* `@zowe/cli`
* `Broadcom-Plugin`
Much of the added code was taken from @zFernand0 's credential manager implementation in the SCS plugin. 😄 
When this PR is merged, a 1.2.3 patch release of Zowe Explorer should go out.
> Add KeytarCredentialManager class modelled after SCS plugin

- __tests__/__unit__/KeytarCredentialManager.unit.test.ts
- src/KeytarCredentialManager.ts
Fixes #541 
This makes Zowe Explorer compatible with the lts-incremental version of the Secure Credential Store plugin, which doesn't support the credential key "Zowe-Plugin".
This fix is also present in patch release 1.2.4, as part of #540
> Support "Broadcom-Plugin" as credential key

- src/DatasetTree.ts
Function was fixed for a later commit but the first commit had not included the PDS in the refactored method
> PDS Missed when refactoring dataset rename

- src/ZoweUSSNode.ts
deleteUSSNode() in src/ZoweUSSNode.ts was modifying the path for a zosmf bug that would break other implementations such as zFTP.  The same fix was already present in src/api/ZoweExplorerZosmfApi.ts (line 90).
> Remove zosmf specific code

- Jenkinsfile
- package.json
- theia_tests.Jenkinsfile
#702 - Move vsix deployment to the Theia pipeline
- Remove vsix deployment from the main build pipeline
- Add a stage in Theia pipeline to build and upload vsix file from branch build to Zowe artifactory
- Use this VSIX file to perform the smoke test in Theia
**Milestone:** v1.5
**Changelog:** N/A
> chore: move vsix deployment to the Theia pipeline

- __tests__/__unit__/dataset/dsNodeActions.unit.test.ts
- __tests__/__unit__/job/jobNodeActions.unit.test.ts
- __tests__/__unit__/uss/ussNodeActions.unit.test.ts
- __tests__/__unit__/utils/profileLink.unit.test.ts
- package.json
to mock `fs` and other core node modules,
explicit call to jest.mock('<module-name>') is required
Signed-off-by: Vit Gottwald <vit.gottwald@gmail.com>
> fix: do not modify fs node module

- .gitignore
- __tests__/__theia__/extension.theia.test.ts
- theia_tests.Jenkinsfile
I ran some tests here and seems work as expected: https://wash.zowe.org:8443/job/Zowe%20Explorer%20-%20Theia%20Test/job/users%252Fjack%252Ftheia-dind/2/console.
The build time reduced to 4 min from 16 min. Thanks for the good suggestion!
One thing I didn't find junit test result, if you have, please update `theia_tests.Jenkinsfile` line 81, and turn line 82 `allowMissingJunit` to false.
When I debug the changes, I added some code in `__tests__/__theia__/extension.theia.test.ts` to create screenshots during test. You can find them from https://github.com/zowe/vscode-extension-for-zowe/blob/228cada1a52689b2d57f093bbfeddb99d17400e9/__tests__/__theia__/extension.theia.test.ts
> Run theia in dind

- src/utils/profileLink.ts
Edge condition. If manually deleting content from yaml file the content may be left in a corrupt state. If an extender application subsequently accesses the API before a user has used profile link which would fix the corrupt file an undefined error will occur.
This is an edge condition so next fix release would be fine
> Additional safety checks for profile links

- package-lock.json
- src/Profiles.ts
- src/abstract/ZoweTreeProvider.ts
**Fix #767** - Editing of Credentials and setting them to spaces
**Fix #748** - Pressing Escape does not abort Edit profile dialogue
The prompt function is triggered if the profile is changed to spaces
When you press escape when editing the URL, it will not go through the next dialogue box
**Milestone:** v1.5.1
**Changelog:** Fix bugs for edit session
> Fix: bugs found for edit session

- package-lock.json
- package.json
This pull request updates the Zowe CLI version from 6.13.0 to 6.14.0. Version 6.14.0 uses Zowe Imperative version 4.6.4, which includes logging with improved compatibility with Webpack (needed for issue #74).
(More generally, Zowe CLI 6.14.0 also adds encoding/code page support for data set upload and download operations in library and CLI.)
Milestone: 1.7 Release
Changelog: Update Zowe CLI to version 6.14.0.
If this is a relatively large or …
> Update Zowe CLI version

- src/shared/utils.ts
@zFernand0 with further testing it looks like just passing the etag isn't fixing the issue for #928 I am noticing that it fixes the issue seen among extenders (rse & zftp) but with zosmf profiles it is still overwriting without doing the compare. It looks like this line is causing the issue:
`// Upload without passing the etag to force upload`
`const uploadOptions: IUploadOptions = {`
`returnEtag: true`
`};`
If I move it into the if (isZoweDatasetTreeNode(node)) section it fixes the issue for USS, but I don't think we want to force upload data set changes either.
Update: moving this piece of code into the if (isZoweDatasetTreeNode(node)) doesn't force the upload to MVS, the compare box is working as it should. …
> fix for zosmf overwriting issue

- __tests__/__unit__/Profiles.unit.test.ts
- __tests__/__unit__/shared/actions.unit.test.ts
- src/Profiles.ts
- src/dataset/actions.ts
- src/dataset/dsNodeActions.ts
- src/job/actions.ts
- src/shared/actions.ts
- src/shared/utils.ts
- src/uss/actions.ts
Re validation for invalid profiles automatically, refresh tree clears profilesForValidation[] and resets icons.
Milestone: 1.8.0
Changelog: Ability to clear validations and re-validate as needed using refresh view.
> Issue 917 Refresh for Profile Validation

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: KRISTINA MAYO <ktopchi@us.ibm.com>
There has been instances in the past where is was not clear how the code in a PR would change the User Experience even after lengthy description was included. I propose to add a guideline so a user who makes UI changes would need to include either a gif (preferably) or a screenshot (if a change is really simple). That way, the reviewer can quickly see what changes has been made without even loading the code locally and running it. 
Request developer to include gif or screenshot showing changes they made
Milestone:
Changelog:
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any …
> Request developer to include gif or screenshot showing changes they made

- __tests__/__integration__/DatasetTree.integration.test.ts
- __tests__/__unit__/dataset/DatasetTree.unit.test.ts
- i18n/sample/src/dataset/DatasetTree.i18n.json
- src/dataset/DatasetTree.ts
Resolves #962. This fix ensures datasets and dataset members are displayed in uppercase when renamed by the user.
Not sure which milestone this falls under.
Milestone:
Changelog: Ensures datasets and dataset members are displayed in uppercase when renamed by the user.
> Fix issue 962

- packages/zowe-explorer/src/ZoweExplorerExtender.ts
- scripts/systemTestEnv.ts
Update filepaths so integration tests run for the zowe-explorer package.
- I updated the top-level `scripts/systemTestEnv.ts` to use the zowe-explorer package's `resources/testProfileData.ts` file for now. In the future, if we want to instead bring that file to the top level to use in other packages' integration tests, we can change the path back.
> Update filepaths for monorepo

- packages/zowe-explorer-api/README.md
- packages/zowe-explorer-ftp-extension/README.md
- packages/zowe-explorer-ftp-extension/docs/README.md
Copyedit suggestions for #1152 (FTP API readme updates)
Includes:
- Minor punctuation/wording suggestions.
- Uses ordered lists for sequential instructions.
- In Zowe Explorer FTP extension's readme, I added a link to prerequisites for installing the FTP extension for Zowe CLI (in case the user happens to not realize they need to separately install Zowe CLI first).
> Copyedit suggestions for 1152 FTP API readme updates

- packages/zowe-explorer/src/Profiles.ts
I believe these lines can be taken out since the prompt doesn't worry about host and port, and after testing all profiles work (creds included, creds as empty string, and creds as undefined) https://github.com/zowe/vscode-extension-for-zowe/blob/62442606b95dc048d2c829b78d0ee7e93029facb/packages/zowe-explorer/src/Profiles.ts#L91. By the time this method is called the base profile merging is already done so that line I mentioned isn't useful and the prompting that is called within that try is only dealing with user/pass not other values.  So if a profile has user/pass but doesn't match the host and port of the base profile you are prompted. Once that is taken out line 87 is no longer needed as well.  Also lines …
> update check for missing creds to not rely on base profile

- packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
In PR #1120, we noticed that users won't be prompted to enter their credentials, if a profile was previously marked `invalid`.
This should cause prompting to occur if the user is missing enough credentials in their session/combined profiles, no matter whether the profile was validated before or not.
I've tested this with the contents of PRs #1120 & #1150 and found no huge showstoppers.
Milestone: 1.12.1
Changelog: Updated credential prompting to occur even if profile has been marked "invalid".
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as …
> PR #1120 linked issue: Always allow prompting

- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer-api/src/tree/IZoweTree.ts
- packages/zowe-explorer/__tests__/__unit__/KeytarCredentialManager.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/abstract/TreeProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/src/KeytarCredentialManager.ts
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
This is one change that fixes several issues.
1. **Fix for issue #989:** There has been a bugfix! 😃 Which means in Zowe Explorer we can now pass an `IUpdateProfile` object to `CliProfileManager.update()`...and we don't have to change the profile object key names to resemble CLI command params. This was the cause of #989.
2. **Fix for issue #1095:** I set `merge: false` in the profile, so only the new values will be kept, not the old (ie. now we don't have to store an empty string as a placeholder for an optional field).
3. **Fix for issue #1016:** There are two new conditions in our `updateProfile()` function, which will remove the `responseTimeout` field if it was set to 0, and any other field if it was set to an empty string. And because of fix 2 (above), #1016 should not reoccur. …
> Multiple issues: Fixed errors with updating optional profile fields

- packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
- packages/zowe-explorer/src/shared/actions.ts
This fixes issue #992...apparently class name is not a reliable way to determine the type of a custom object in VSCode...
Milestone: 1.13
Changelog: Fixed bug with listing files on CTRL+ALT+P command
> Issue #992: File picker doesn't work

- packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
- packages/zowe-explorer/src/Profiles.ts
This will pre-fill the placeholder with a previously chosen `rejectUnauthorized` value as well as bring that selection to the top of the list and is highlighted to be entered passed or changed by user when editing a profile.  Creating a profile the placeholder is the same as before as well as the selection order.
Milestone: 1.13.0
Changelog: Bugfix to pre-select existing value for rejectUnauthorized and show existing value in the quickPick placeholder so it can be entered by unless user decides to change the value.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If …
> issue 1127: Pre-select existing reject unauthorized value for update profile

- packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
- packages/zowe-explorer/src/uss/ZoweUSSNode.ts
Resolves issue #1134 (USS files menu serves incorrect content from another directory).
This PR adds a `parentPath` (file path) check to the check for existing USS node children when `getChildren` is called on the USS node. Previously, only the label (i.e. the very last part of the filepath) was being compared, leading to identically-named files/folders being identified as "existing children", when they were in fact residing under different directories (e.g. different user directories).
Milestone: 1.13.0
Changelog: Bugfix to check file path when comparing for existing USS node children.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure …
> Bugfix issue 1134: Add parentPath check for existing USS node children

- packages/zowe-explorer-ftp-extension/README.md
Resolves #1242 ([zFTP] Add pre-requisite in readMe file). No code changes.
Milestone: 1.13.1
Changelog: Add z/OS FTP Plug-in for Zowe CLI as a prerequisite to Zowe Explorer Extension for FTP.
> Add FTP prerequisites to ReadMe

- .github/workflows/deployment.yml
- package.json
- packages/eslint-plugin-zowe-explorer/package.json
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/package.json
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/package.json
Preparation for 1.14.0 release
Milestone:
Changelog:
> Preparation for 1.14.0 release

- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/i18n/sample/package.i18n.json
- packages/zowe-explorer/package.json
- packages/zowe-explorer/package.nls.json
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/globals.ts
Signed-off-by: Rudy Flores <68666202+rudyflores@users.noreply.github.com>
Adding a right-click action to refresh data sets to retrieve new list of members from the mainframe
Milestone: Release v1.16.0
Changelog: Refresh feature for data set member names in a profile.
> Allow refresh for dataset member names

- packages/zowe-explorer/src/shared/actions.ts
- packages/zowe-explorer/src/shared/refresh.ts
Fixes issue #1403 (Refresh view does not consistently reset profile status).
(See issue for recreate/testing steps.)
Gif of fix:
Milestone: 1.17.1 hotfix or 1.18.0
Changelog: Ensure status icons are reset when refreshing views
> Issue 1403: Ensure status icons are reset when refreshing view

- packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
Bug Fix: Remove validation check before updating profile, then after updating the profile it is revalidated and the icon is updated.
Milestone: 1.18.0
Changelog: Bug Fix: Remove validation check before updating profile.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives …
> Remove validation check before updating profile

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/README.md
Moves doc updates into `v1.18.x` branch from PR #1451 (Update Readme and Changelog for 1.18.1).
> (doc)1.18.1 updates into v1.18.x branch

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/README.md
Reverts zowe/vscode-extension-for-zowe#1451 due to incorrect base branch for hotfix.
Contents of #1451 will be moved to the `v1.18.x` branch via #1452.
> Revert "(Docs) Update Readme and Changelog for 1.18.1"

- packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fixes issue #1469 by checking that a base profile exists before running `getCombinedProfile()` in `syncSessionNode()`.
Milestone: 1.19.0, ideally
Changelog: Check that a base profile exists before running the function to combine base and service profiles.
> Add check for baseProfile before running getCombinedProfile in syncSessionNode

- .github/workflows/theia-zowe-explorer-ci.yml
- packages/zowe-explorer/src/Profiles.ts
> Change Theia GHA tests to use quay.io

- packages/zowe-explorer/i18n/sample/src/job/ZoweJobNode.i18n.json
- packages/zowe-explorer/src/job/ZoweJobNode.ts
Resolves an issue #845 by skipping all the objects which are returned from `GetSpoolFiles` API call and do not correspond to the proper `zowe.IJobFile` type. As a result there will be no more `undefined:undefined(undefined)` items in the spool files tree.
> [Issue #845] Do not show undefined spool files for a job

- packages/zowe-explorer/i18n/sample/src/job/ZoweJobNode.i18n.json
- packages/zowe-explorer/src/job/ZoweJobNode.ts
Resolves an issue #845 for the `next` branch.
Skipping all the objects which are returned from `GetSpoolFiles` API call and do not correspond to the proper `zowe.IJobFile` type. As a result there will be no more `undefined:undefined(undefined)` items in the spool files tree.
> [Next] Do not show undefined spool files for a job

- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/README.md
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/README.md
Signed-off-by: ik673626 <igor.kazmyr@broadcom.com>
Update to the Readme (the release notes section) and Changelog for 1.21.0
Milestone:
Changelog: 1.21.0
> (Doc) 1.21.0 Regular doc update

- packages/zowe-explorer/i18n/sample/src/job/actions.i18n.json
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/job/actions.ts
Resolves issue #1338 by introducing progress bar during multi-delete for jobs.
> [Next][Issue #1338] Add progress bar for multi-deletion of jobs

- packages/zowe-explorer/__tests__/__unit__/command/tsoCommandHandler.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/command/TsoCommandHandler.i18n.json
- packages/zowe-explorer/src/command/TsoCommandHandler.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
This one fixes #1560. 
_(The issue itself is opened for TSO command execution feature initially, but this bugfix affects a helper function, which is used in many places, and as a result it also fixes the cancelling cases for other commands (e.g. Issue MVS command, filter selections and etc.)_
Added an `onDidHide` handler for `resolveQuickPickHelper`, which always return `undefined` result. 
Milestone:
Changelog:
After a PR is merged into the …
> [Issue #1560] Fix input cancelling messaging

- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/i18n/sample/package.i18n.json
- packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
- packages/zowe-explorer/package.json
- packages/zowe-explorer/package.nls.json
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/globals.ts
- packages/zowe-explorer/src/shared/refresh.ts
Silently reload Zowe Explorer to reset which treeProviders are used after types of profile handling are changed, old style => config, config -> old sytle, etc.  User is presented with a botton in the Popup Message after config file creation to `Refresh Zowe Explorer` other options for this action are the Command Palette `Zowe Explorer: Refresh Zowe Explorer` and quick keys `alt+z`
> Another approach for refreshing after config file creation/deletion

- packages/zowe-explorer-api/src/security/KeytarApi.ts
- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/src/extension.ts
some changes where made on imperative and with our call to activateKeytar() line 33 call to CredentialManagerFactory() during activation and the API seems to be v1 specific with this check in it ` const scsActive = profiles.isSecureCredentialPluginActive();`  was breaking our new Refresh Zowe Explorer command pallete and quick-key options. Also the removed test was checking that vscode.workspaces.getConfiguration was called 2 times but the 2nd time was within activateKeytar.
On this note I will propose to remove the Keytar API requirement for extenders in the V2 Conformance.
It may be good to remove the code from ZE API completely as well for v2 since it is v1 specific.
Changelog:
_Put an `x` in the boxes …
> Bugfix: Refresh of Zowe Explorer

- packages/zowe-explorer/__tests__/__unit__/command/tsoCommandHandler.extended.unit.test.ts
- packages/zowe-explorer/src/command/TsoCommandHandler.ts
- Retrieve team config information for TSO commands
- Reuse the same TSO profile-selection logic between v1 and v2 profiles.
- Fix #1515
Milestone: V2
Changelog: Fixed TSO commands in when using teamConfig
> fix(tso-cmd): Retrieve team config information for tso commands

- packages/zowe-explorer/i18n/sample/src/extension.i18n.json
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
The new Zowe configurations files are more error prone and harder to troubleshoot. We need to provide more clear logging and error messages to help users self-diagnose. 
I started cleaning up the error message shown when activation runs into issues loading configuration files. I was talking about problems with the logger before.  I also started adding more information about the actual profiles found to the `readConfigFromDisk()`, but that only works when loading a valid file.  Looking for more ideas for how to diagnose and invalid file or problems reading the files.
Also moved down the mkdir operations in activation as they were calling error handling which required profiles to be loaded first.
Milestone:
Changelog:
_Put an …
> Improve activation errors and team config logging

- packages/zowe-explorer/src/job/ZoweJobNode.ts
Signed-off-by: Rudy Flores <68666202+rudyflores@users.noreply.github.com>
Milestone:
Changelog: Fix duplicate jobs appearing in the jobs view upon making an owner/prefix filter search for extenders.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …
> Remove duplicate jobs for extenders

- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Signed-off-by: KutluOzel-b <kutlu.ozel@broadcom.com>
Fixed extra space in the Invalid Credentials dialog, at profile validation `profilename`
#1494 
Changelog:
- [ x] Bugfix (non-breaking change which fixes an issue)
- [ x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ x] PR Description is included
- [ x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x ] There is coverage for the code that I have added
- [ x] I have tested it manually and there are …
> fix(validate profile) Extra space in the dialog box text

- packages/zowe-explorer/src/ZoweExplorerExtender.ts
Signed-off-by: KutluOzel-b <kutlu.ozel@broadcom.com>
fix runtime error profileTypeConfigurations iteration. 
Milestone:
https://github.com/zowe/vscode-extension-for-zowe/issues/1872
Changelog:
- [x ] Bugfix (non-breaking change which fixes an issue)
- [ x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ x] PR Description is included
- [ x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ x] There is coverage for the code that I have added
> fix runtime err profileTypeConfiguration iteration

- README.md
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Signed-off-by: KutluOzel-b <kutlu.ozel@broadcom.com>
Fix registerCustomProfileType for extenders throwing error while v1 profile not in use but v2 in use. 
Checking if v1 or v2 is used if so then registers profile.
Milestone:
https://github.com/zowe/vscode-extension-for-zowe/issues/1870
Changelog:
- [ x] Bugfix (non-breaking change which fixes an issue)
- [ x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ x] PR Description is included
- [ x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ x] There is coverage for the code that I have added
> (Fix) registerCustomProfileType for extenders throwing error while v1 profile not in use but v2 in use. 

- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/FtpApi/ZoweExplorerAbstractFtpApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
Fixes some zftp profile properties like "connectionTimeout", "rejectUnauthorized", and "serverName" being ignored.
Updated the changelog in the PR.
Bugfix (non-breaking change which fixes an issue)
> Fix some zftp profile properties being ignored

- packages/zowe-explorer/src/job/actions.ts
fix for `Pull from Mainframe` for spool files after label change
Milestone: 2.3.0
Changelog:
> Fix for pull from mainframe bug for spool files

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/extension.ts
Fix refresh job & spool file pull from mainframe doesn't update job status by refreshing parent node.
Milestone:
https://github.com/zowe/vscode-extension-for-zowe/issues/1857
Changelog:
The Bug is solved by refreshing parent node method which leads to refreshing unnecessary nodes as well. Since we are populating nodes into belonging trees in a singular way this maybe not the best option but good for consistency.
> Bug/refresh job/status

- package.json
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__mocks__/fs.ts
- packages/zowe-explorer/__tests__/__unit__/ProfilesCache.unit.test.ts
- packages/zowe-explorer/src/ZoweExplorerExtender.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
- yarn.lock
Fix #1802 by falling back to an empty string for the project directory when the VS Code workspace root is undefined.
This depends on Zowe CLI 7.6.1 which includes an update to the Imperative ProfileInfo API that skips loading project profiles when `projectDir` is `false`.
Milestone: 2.4
Changelog: Updated with TBD Release
See #1802 for steps to reproduce the issue and verify the fix.
> Don't load project profiles when no workspace folder is open

- .github/workflows/zowe-explorer-ci.yml
- .github/workflows/zowe-explorer-ftp-ci.yml
Update workflows for Zowe Explorer and Zowe Explorer FTP extension:
* Increase yarn network timeout from 30s to 60s to reduce build failures
* Fix Codecov uploader not running in ZE workflow
* Fix test results not uploaded in ZE FTP workflow
* Package VSIX in both workflows and upload it as artifact to make testing PRs easier
N/A
This commit provides an example of the workflows running successfully: https://github.com/zowe/vscode-extension-for-zowe/commit/4e26a4f14b0f60681f55dee8579df7e5b54076ba
> Update GitHub workflows

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfileUtils.unit.test.ts
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/globals.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
This PR will 
1. check for and create if needed the .zowe/settings/imperative.json file making Zowe Explorer independent of the Zowe CLI installation.  
2. fixes the watcher of the Secure Credentials Enabled setting, to update file when checked or unchecked.  
3. will read and parse the file if existing and changing the CredentialManager value then write back. This is done just incase imperative, zowe cli, or an extender/plugin decide to introduce more values to this file.
Milestone: 2.4.1
Changelog:
- Added independence from Zowe CLI installation by creating the `~/.zowe/settings/imperative.json` file during activation if it doesn't already exist. This file is for Zowe Explorer to know the Security Credential …
> Make Zowe Explorer independent of Zowe CLI installation

- packages/zowe-explorer/package.json
Signed-off-by: Benjamin Santos <Benjamin.Santos@ibm.com>
Currently the Zowe Explorer web extension acts only as a stub intended to resolve other web extensions dependencies on it
Despite this, when installing ZE on vscode.dev or any other browser based VS Code instance, the ZE icon is still added to the activity bar, and the tree views are shown. Interacting with these views creates an ugly, unhandled errors (e.g. "command 'zowe.jobs.refreshAllJobs' not found)
The Zowe Explorer views and icon are initialized in the package.json "viewContainers" field. Adding a "when: !isWeb" clause will prevent the views and icon from being loaded in a browser, while not affecting their rendering on desktop or other environments.
To test on your own: 
1. Package the extension as normal, install the .vsix, …
> [fix] Disabling ZE views for web extension

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
- packages/zowe-explorer/i18n/sample/src/shared/utils.i18n.json
- packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/shared/utils.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Added localization that was missing for certain strings in VScode error/info/warning messages.
_Note:_ I searched for missing localization using the regular expression `window.show(Information|Error|Warning)Message\("`, so all of the `window.show*` calls should now be localized.
Changelog: Fixed (added) localization that was missing for certain strings in VScode error/info/warning messages.
> Fix: Added missing localization for strings in info/warning/error messages

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/dataset/actions.ts
- Fixes bug described in #1973 to allow `allocateLike` to continue execution
- **Update:** Originally #1974 was factored into this issue, but the block size problem appears to be an issue with z/OSMF REST client.
- Also updated logic in `removeFavorite` to skip `undefined` nodes
Changelog: Fixed issue where "Allocate Like" feature fails to grab dataset node during execution
> Fix: "Allocate Like" execution stops due to error

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/src/tree/IZoweTree.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__mocks__/mockCreators/datasets.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/shared/context.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/dataset/actions.i18n.json
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/shared/context.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- Sync tree nodes in favorites list with their actual state under "Data Sets" panel
Changelog: Fixed issue where Favorites section was not refreshing after changes were made to data sets or their members.
- **Future Proposal:** Change method of storing favorites such that the nodes can be mapped 1:1; this should shorten lookup time for corresponding nodes and make logic more straightforward for adding/removing favorites. Since we are searching based on labels, we could assign the node labels as keys for a map-based structure.
- **For next standup:** The `findFavoritedNode` and `findNonFavoritedNode` functions are marked deprecated, but they're being used in the codebase. Reimplement (as suggested above) or keep the same data structure?
> Fix: Cannot delete favorited PS, PDS, or member

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/job/actions.i18n.json
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/job/actions.ts
- Fixes issue where the parent node (in job tree) automatically closes after 1+ job(s) are deleted from that parent node.
Changelog: Fixed issue where parent job node closes after deleting 1+ job(s) belonging to that parent.
> Fix: Parent node auto-closes after single/multiple job deletion

- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfileUtils.unit.test.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fixes regression introduced in #2006, which failed to log errors causing the `errorHandling` method to throw an error and skip showing a message to the user.
Changelog: n/a
> Fix errorHandling utility method throwing an error

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/src/logger/IZoweLogger.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
- packages/zowe-explorer-api/src/security/KeytarCredentialManager.ts
- packages/zowe-explorer-api/src/tree/IZoweTree.ts
- packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/__mocks__/vscode.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpJesApi.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
- packages/zowe-explorer-ftp-extension/src/extension.ts
- packages/zowe-explorer-ftp-extension/src/ftpSession.ts
Signed-off-by: Trae Yelovich <trae.yelovich@broadcom.com>
- All ESLint errors in `zowe-explorer-api` are now fixed
- Significantly reduced ESLint errors in `zowe-explorer-ftp-extension`
Milestone:
Changelog:
- Reduced amount of warnings down to 4; those warnings require a refactor of other packages (namely `zowe-cli-ftp-plugin`) to be merged before the warnings can be properly fixed.
> Fix: Clean-up ESLint errors

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/dataset/actions.ts
Signed-off-by: Trae Yelovich <trae.yelovich@broadcom.com>
Previously, the "Show Attributes" feature was using yellow and white as the default color scheme. However, with light themes the text for this feature is unreadable. This fix resolves the issue by falling back to VSCode's colors for the keys and values.
Thanks again to @anaxceron for discovering this issue, and my apologies for the implementation oversight.
**Before:**
**After:**
| Light Theme | Dark Theme |
| ------ | ------ |
| ![image](https://user-images.githubusercontent.com/86500639/207967757-de34abe7-f682-4d9a-82f1-f29ce55ed96e.png) | ![image](https://user-images.githubusercontent.com/86500639/207967683-d92bfb40-6658-4ba7-b0fc-cfb4d18415d8.png) |
Milestone: 2.6
Changelog: 
- Fixed issue where "Show Attributes" feature used …
> fix: "Show Attributes" feature should adjust colors dependent on VSCode theme

- package.json
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/package.json
- yarn.lock
Resolves #1997 by adding file association for `zowe.config.json` and `zowe.config.user.json` to automatically detect them as JSON with Comments.
Changelog: updated in PR
The original solution suggested in the issue was to define `contributes.configurationDefaults.files.associations` in package.json. However, I realized after testing this change that it was the wrong way to go about it, because it overrides default values set by other extensions. The correct solution seems to be defining a `contributes.languages` section.
> Automatically detect team config files as jsonc

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/job/actions.ts
Brought success message inside the try of the try/catch and removed try/catch from provider.delete method so error will be thrown for methods, like job delete, that is calling it.
Changelog: Fixed issue with a success message being returned along with error for Job deletion. [#2075](https://github.com/zowe/vscode-extension-for-zowe/issues/2075)
> remove success message from when error is returned

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/src/globals/Gui.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/shared/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/uss/ZoweUSSNode.i18n.json
- packages/zowe-explorer/src/uss/ZoweUSSNode.ts
Signed-off-by: Trae Yelovich <trae.yelovich@broadcom.com>
- Removes excess pop-ups when listing USS files in favor of a minimal progress bar at the top of the tree view.
- Replaced "Opening USS file..." pop-up => status bar item w/ `$(sync~spin)` icon.
Milestone: 2.6.1
Changelog:
- Removed excess pop-ups when listing/opening USS files, and replaced required pop-ups with status bar items to improve UX. #2091
> fix(uss): Removed excess pop-ups when listing and opening USS files/folders

- packages/zowe-explorer/README.md
Added "Known Issues" section to ReadMe file, which contains a section titled "Bidirectional languages."
A user reached out to Brightside and asked about support for BiDi languages and was informed that VSC doesn't currently support these. (See Microsoft VSC [Issue 86667](https://github.com/microsoft/vscode/issues/86667)) 
Adding it to the ReadMe documentation in case of similar queries in the future. (Already added to Zowe Docs via [PR 2634](https://github.com/zowe/docs-site/pull/2634))
> added section on BiDi languages support

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/job/ZoweJobNode.ts
Signed-off-by: Trae Yelovich <trae.yelovich@broadcom.com>
This PR removes the outdated `.command` object that was previously being added to job nodes. This command object was invalid since it was pointing to a command name that is not registered. Since VScode 1.75, the tree view behavior has changed and the `.command` object is no longer needed to maintain the intended behavior - a single-click action on job nodes to toggle its tree state (collapsed/expanded).
Milestone: 2.6.1
Changelog:
- Fixed bug where a JSON error occurs for job nodes when collapsing or expanding with a single click. #2121 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If …
> fix(jobs): Fix `JSON.stringify` error when expanding job nodes

- packages/zowe-explorer-api/__tests__/__unit__/globals/Gui.unit.test.ts
- packages/zowe-explorer-api/src/globals/Constants.ts
- packages/zowe-explorer-api/src/globals/Gui.ts
- packages/zowe-explorer-api/src/tree/IZoweTree.ts
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- packages/zowe-explorer/src/uss/ZoweUSSNode.ts
This fixes #2125, where a double-click event always opened a data set member or USS file in preview mode. It implements a function to check for a double-click event on a node, found in the `Gui.utils` namespace. This implementation can be used for any Zowe node (in any Zowe tree provider), and works in tandem with an optional `lastOpened` member in the `IZoweTree` class so that extenders can also implement this functionality if desired.
Milestone: 2.6.1 (?)
Changelog: 
- Fixes issue where data set members and USS files always opened in preview mode when double-clicked. #2125
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any …
> fix (uss/ds): Data set members and USS files only open in preview mode

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
- packages/zowe-explorer-api/src/vscode/doc/IPromptCredentials.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__mocks__/@zowe/cli.ts
- packages/zowe-explorer/__mocks__/@zowe/imperative.ts
- packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/ZoweExplorerExtender.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfileUtils.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/ZoweExplorerExtender.ts
- packages/zowe-explorer/src/uss/actions.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fixes #2187 by implementing the following behavior:
* When ZE launches it should create `imperative.json` if it doesn't exist, but should not overwrite the file if it already exists unless requested to.
* When ZE updates the contents of `imperative.json` it should remove all old contents from the file even if the new contents are shorter.
* When ZE fails to parse the contents of `imperative.json` it should show an error message that accurately conveys what happened.
Also fixes a few other credential-related issues discovered when testing the K8s plugin:
* The utility method `readConfigFromDisk` was catching errors and rethrowing them with less information, which can make it difficult to debug problems with loading custom credential managers.
* When v1 profiles are in use, right-clicking …
> Fix errors related to Imperative overrides file

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/init.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/init.unit.test.ts
- packages/zowe-explorer/package.json
- packages/zowe-explorer/src/dataset/init.ts
- packages/zowe-explorer/src/uss/init.ts
Looks like the function call to `TreeViewUtils.fixVsCodeMultiSelect` (VSCode multi-select bug workaround) was removed in a previous commit to the codebase.
This adds back the function calls for USS and Dataset trees, and also removes the "Paste" option from dataset multi-select, as it currently only supports one selected node per operation.
Changelog: 
- Added back fix that was accidentally removed between updates: Resolved an issue where VSCode did not provide all context menu options for a profile node after a multi-select operation. [#2108](https://github.com/zowe/vscode-extension-for-zowe/pull/2108)
- Fixed issue where "Paste" option is shown for a multi-select operation in the "Data Sets" pane (currently unsupported).
What types of changes does your code introduce to …
> fix(vscode): Added back multi-select fix; remove 'Paste' from dataset multi-select

- packages/zowe-explorer/__tests__/__unit__/utils/ProfileUtils.unit.test.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
There was a null-like access of `node` when trying to determine profile info, specifically when updating credentials. This should resolve the CWE on Coverity.
Changelog: 
- Fixed issue where a node is accessed while updating credentials, even if the node is invalid.
> fix(cwe): `null`-like node in `ProfilesUtils.promptCredentials`

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts
- packages/zowe-explorer/__tests__/__unit__/ZoweNode.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/dataset/DatasetTree.i18n.json
- packages/zowe-explorer/i18n/sample/src/dataset/ZoweDatasetNode.i18n.json
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
Fixes a regression in ZE 2.6.0 and restores the original behavior
Before:
After:
Changelog: Fixed error message when no data sets found that match pattern.
> Fix error message when no data sets found

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Sometimes `fs.realpathSync.native` will throw an error on Windows. Previously, we were defaulting to this method for Windows systems, but were not catching any exceptions from this function within `getFullPath`.
This proposes a fallback to `fs.realpathSync` when `fs.realpathSync.native` throws an error. Thanks @t1m0thyj for finding where realpath was referenced and for the helpful discussion 🙂 
Inspired by [this issue](https://github.com/SimenB/realpath-native/issues/35), from a repo that proposed the addition of this implementation into Node.js.
Changelog:
- Resolved an issue where Windows users encountered errors, specifically while Zowe Explorer is building the path for a project directory. (This should help with [this …
> fix(fs): `realpathSync.native` sometimes fails on Windows

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts
- packages/zowe-explorer/__tests__/__unit__/ZoweExplorerExtender.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
- packages/zowe-explorer/src/shared/utils.ts
- packages/zowe-explorer/src/uss/ZoweUSSNode.ts
Resolves #2172 by removing `/` characters in `path.join()` calls.
Milestone: v2.9.0
Changelog: Removed "/" characters in path.join() calls.
> fix: remove instances of slashes in path.join calls

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/dataset/actions.ts
fixes issue https://github.com/zowe/vscode-extension-for-zowe/issues/2323
Milestone: 2.9.0
Changelog: Fixed issue with Windows path when uploading file to data set. [#2323](https://github.com/zowe/vscode-extension-for-zowe/issues/2323)
> Fix for upload member bug on Windows

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
This fix introduces a patch to allow extenders to handle Theia environments, and use the VSCode provided keytar, fixing an error in the CICS extension for specific remote sessions.
Fixed error when an extender's extension attempts to access the keyring in a remote VSCode session
Milestone:
Changelog:
> fix: Zowe Explorer API to use VSCode keytar

- package.json
- packages/zowe-explorer-api/package.json
- yarn.lock
This PR bumps `semver` to `7.5.3` (latest). Versions below `7.5.2` are vulnerable to a ReDoS attack, see the link below for more information:
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
Milestone: 2.9.1
> fix(dep): bump semver to 7.5.3 to resolve audit

- package.json
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
- packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
- packages/zowe-explorer-api/src/vscode/doc/IPromptCredentials.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/abstract/TreeProvider.unit.test.ts
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
- yarn.lock
This PR cherry-picks the fix for #2330 for merging into the maintenance branch.
Milestone: 2.9.1
Changelog: 
Fixed issue where profiles with authentication tokens were breaking functionality for direct-to-service profiles after user interaction. #2330 
> fix(profiles): Apply #2330 fix to maintenance branch

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/job/ZoweJobNode.i18n.json
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/job/ZoweJobNode.ts
This PR should fix the issue where job nodes are not being created after submitting a job and then clicking "Refresh".
To verify, open a session in the jobs tree and search for a filter. Once searched, go to the data sets tree and submit a job. Come back to the jobs session and right click -> select "Refresh." The new job should appear in the list of children.
Fixes #2370 and #2376 
Changelog:
- Fix bug in 2.9.1 where job session nodes were not updated with new nodes.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference …
> fix(jobs): Job tree not creating new nodes after submitting job

- package.json
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/ZoweNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/dataset/ZoweDatasetNode.i18n.json
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- yarn.lock
Handles control characters in data set member names returned by the `List.allMembers` API.
Depends on https://github.com/zowe/zowe-cli/pull/1730
Changelog: Fixed error when listing data set members that include control characters in the name.
> fix(ds): Handle control characters in ds member names

- README.md
Adding yarn version to top level README for dev setup
Milestone: n/a
Changelog: n/a
> Add yarn version to setup steps

- .gitignore
- .vscode/launch.json
- .vscode/sample_env
- .yarnrc
- package.json
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/__tests__/__unit__/security/KeytarApi.unit.test.ts
- packages/zowe-explorer-api/__tests__/__unit__/security/KeytarCredentialManager.unit.test.ts
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer-api/src/security/KeytarApi.ts
- packages/zowe-explorer-api/src/security/KeytarCredentialManager.ts
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/package.json
- packages/zowe-explorer-ftp-extension/webpack.config.js
- packages/zowe-explorer/.prettierignore
- packages/zowe-explorer/.vscodeignore
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/package.json
- packages/zowe-explorer/scripts/getSecretsPrebuilds.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
- packages/zowe-explorer/webpack.config.js
- yarn.lock
This PR:
- implements the use of the `keyring` module from the new [`@zowe/secrets-for-zowe-sdk`](https://github.com/zowe/zowe-cli/tree/master/packages/secrets)
- removes old references to `node-keytar` in the codebase and tests
- updates old `node-keytar` references to the new `keyring` module
**Note** that tests will fail until the imperative PR (linked below) is merged and published.
Milestone: 2.10.0
Changelog: TBD
> feat: Use `keyring` module from `@zowe/secrets-for-zowe-sdk` to replace use of `node-keytar`

- lerna.json
- package.json
- packages/eslint-plugin-zowe-explorer/CHANGELOG.md
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/README.md
- packages/zowe-explorer/__tests__/__theia__/extension.theia.test.ts
- packages/zowe-explorer/__tests__/__theia__/theia/Locators.ts
- packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts
- packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts
- packages/zowe-explorer/__tests__/__unit__/ZoweNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/dataset/ZoweDatasetNode.i18n.json
- packages/zowe-explorer/i18n/sample/src/job/ZoweJobNode.i18n.json
- packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json
- packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/job/ZoweJobNode.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
- yarn.lock
Merge in released changes from 2.9.2 on maintenance branch
Changelog: n/a
> [vNext] Merge maintenance with 2.9.2 work

- lerna.json
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/README.md
2.10.0 release PR
Milestone: 2.10.0
Changelog: n/a
> 2.10.0 Release

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__mocks__/fs.ts
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/package.json
- yarn.lock
This PR bumps `@zowe/secrets-for-zowe-sdk` to 7.18.3. This version resolves the following issues:
- Windows binaries were packaged without a static C runtime (required MSVC redistributables)
- Package install failed if `libsecret` or other Linux dependencies were missing in the user's environment
I've also fixed a couple of tests that were broken because of the `existsSync` check added to the Secrets SDK - since we mock the `fs` module, I had to make some adjustments to get the tests passing again.
Changelog:
- Bump `@zowe/secrets-for-zowe-sdk` to 7.18.3 to handle install errors gracefully and to allow running without MSVC redistributables.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
> chore(secrets): Bump Secrets SDK to 7.18.3

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/package.json
This PR is a one-line change that adjusts the scope of the setting "Security: Secure Credentials Enabled." This setting was missing from some cloud IDEs and as a result, was breaking some environments that do not want to use secure credentials.
Changing the scope from `machine` to `machine-overridable` allows the option to appear.
Milestone: 2.10.1
Changelog:
- Adjust scope of "Security: Secure Credentials Enabled" setting to `machine-overridable` so it appears again in certain cloud IDEs.
> fix(settings): Change scope of "Security: Secure Credentials Enabled" to fix missing setting for some Cloud IDEs

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/package.json
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/dataset/actions.ts
- yarn.lock
In some scenarios, if data set content did not finish downloading, any subsequent clicks on the data set node will cause the editor to appear without any content. The content is then added to the local document, but because of this, it can break extensions such as the COBOL language support extension. This PR adds some logic that will wait for the dataset node to finish fetching contents before opening the editor.
This also bumps the Secrets SDK to 7.18.4 because some bug fixes were not released as intended w/ 7.18.3.
Changelog:
- Fixed issue where data set content does not always appear as soon as the editor is opened. [#2427](https://github.com/zowe/vscode-extension-for-zowe/issues/2427)
_Put an `x` in …
> fix(ds): wait until contents are received to show editor

- .gitignore
- .vscode/launch.json
- .vscode/sample_env
- package.json
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-api/src/security/KeytarApi.ts
- packages/zowe-explorer/.vscodeignore
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/package.json
- packages/zowe-explorer/webpack.config.js
- yarn.lock
This PR ports the Secrets SDK work from #2405 into the `v1-lts` branch.
To test, sign into a v1 profile with your credentials. The `.yaml` file with your v1 profile should update so that the username and passwords fields are set to `Managed by Zowe Explorer`.
Milestone: 1.22.5
Changelog:
- Replaced `keytar` dependency with `keyring` module from [`@zowe/secrets-for-zowe-sdk`](https://github.com/zowe/zowe-cli/tree/master/packages/secrets). [#2358](https://github.com/zowe/vscode-extension-for-zowe/issues/2358)
- Bump `semver` to 7.5.3 to resolve audit
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the …
> feat(v1/secrets): Port Secrets SDK changes to v1

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/abstract/TreeProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Refresh Zowe Explorer after a logout is performed for token based auth
Milestone: 2.10.1
Changelog: Fixed issue with endless credential prompt loop when logging out 
> Refresh Zowe Explorer after token auth logout

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/uss/USSTree.ts
This PR fixes the following bug: when "Automatic Profile Validation" is disabled, the search prompts do not appear after clicking on the search icon for all 3 trees.
This was resolved for the jobs tree as a part of #2440, but the issue remained for the data set and USS trees.
Fixes #2454, #2344 
Changelog:
- Fixed issue where disabling "Automatic Profile Validation" caused the search prompts to stop appearing for all tree views. #2454 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and …
> fix(ds,uss): Check if profile is invalid before searching

- .github/workflows/deployment.yml
The prerelease published successfully with this workflow:
https://github.com/zowe/vscode-extension-for-zowe/actions/runs/6161558200
But the post-publish step to create a snapshot version failed. I think we can disable it for the "next" branch because it doesn't make sense to be creating "SNAPSHOT" versions on a prerelease branch.
> Skip creating snapshot version after publish for next

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
This PR fixes the bug where new data sets created in Zowe Explorer were added to the bottom of the list, rather than re-sorting the list by name.
This sorting logic matches the sorting logic for the USS tree.
To test, create a new data set member with a name that comes before another data set alphabetically. Notice that the new data set member will appear above the existing data set as intended, rather than at the bottom of the list (current behavior in v2.11)
Milestone: 2.11.1 ?
Changelog:
- Fixed bug where the list of datasets from a filter search was not re-sorted after a new data set was created in Zowe Explorer. #2473 
> fix(ds): Sort dataset list by label after adding new children

- lerna.json
This is the PR for the upcoming 1.22.5 release. Code freeze is next week (9/19, I believe)
Milestone: 1.22.5
There's only one change for this release:
- Replaced `keytar` dependency with `keyring` module from [`@zowe/secrets-for-zowe-sdk`](https://github.com/zowe/zowe-cli/tree/master/packages/secrets). [#2358](https://github.com/zowe/vscode-extension-for-zowe/issues/2358)
> 1.22.5 Release

- .github/workflows/zowe-explorer-samples.yml
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- samples/menu-item-sample/package.json
- samples/menu-item-sample/yarn.lock
- samples/tree-view-sample/package.json
- samples/tree-view-sample/yarn.lock
- samples/uss-profile-sample/package.json
- samples/uss-profile-sample/yarn.lock
- samples/vue-webview-sample/package.json
- samples/vue-webview-sample/yarn.lock
* Fixes a code smell flagged by Coverity in `ZoweDatasetNode.ts`
* Updates samples to reference ZE API with a symlink, so that Samples CI workflow will test for breaking changes to API
> Fix Coverity issue and use local ZE API in samples

- packages/zowe-explorer/.vscodeignore
Add missing webview package to `.vsix` bundle in order to not break webviews in future 2.12.0 release after making updates to webview structure against main
Milestone: v2.12.0
Changelog: Add missing webview package to `.visx` bundle
> Add missing webviews to vsix bundle

- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/shared/init.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Here is a solution that registers a setting that would set false for Theia env before handling cred manager. Also removes new dup calls since calls are made in following code if needed
> Remove extra call and register before for theia = false

- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Turns out our issue with the breaking Theia test wasn't due to multiple calls to ProfilesInfo occuring on credential management load, the issue was a missing error handling for when reading the `imperative.json` file, since in Theia the file doesn't exist initially in our tests.
Milestone: v2.12.0
Changelog: Fixed issue with `writeOverridesFile` function not writing properly
> Fix for issue with overrides file not writing correctly

- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
_If we would prefer to keep this for a potential 2.12.1 release, then I will add a changelog. Otherwise, I think we can keep this as `no-changelog` as the feature will be released with 2.12._
---
I've cleaned up the sorting function a bit so that it falls back to sorting by name when 2 node values are equal.
In addition, I've adjusted the date checks slightly to also use Day.js (consistent with the rest of the date processing for this feature) for easier date comparison.
Milestone: 2.12.0 (or 2.12.1)
Changelog:
- Fixed an issue where sorting functionality did not consider the sort direction when values were equal.
_Put an `x` in the boxes that apply. You can also fill these out after …
> fix(ds/sort): Fallback to sorting by name when values are equal

- lerna.json
- packages/eslint-plugin-zowe-explorer/CHANGELOG.md
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer/CHANGELOG.md
> Prepare v2.12.0 release

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/package.json
`Submit as JCL` option should not show in the context menu of the Output Channel and shouldn't be offered with multi-selection of files
Milestone: 2.12.1
Changelog: Update when the option to submit local file as JCL will be displayed in context menus. [#2541](https://github.com/zowe/vscode-extension-for-zowe/issues/2541)
> Update when clause of Submit as JCL for when to show option

- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/shared/actions.ts
- packages/zowe-explorer/src/shared/utils.ts
Fixes race condition where etag might be set to undefined on dataset node, resulting in changes being overwritten if there is a conflict.
Also fixes an issue found during testing where `willForceUpload` tried to upload dataset with extension.
Unfortunately since this is a race condition, I can't provide consistent steps to reproduce. Try to repeat the following steps several times:
1. Open a data set in the tree in different ways: single-click to preview it, double-click quickly, double-click slowly, etc
After trying this several times myself I think you need to have a fast connection and double-click as slowly as possible, so that the data set downloads in between clicks, but it still registers as a double-click.
2. Make changes to the data set on the mainframe
3. Make changes to the …
> Fix undefined etag for dataset nodes

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
This PR fixes a bug where Day.js interpreted an `undefined` value as a valid date (same behavior as `dayjs()` or `Date.now()`) instead of coercing the invalid/missing date parameter to null.
Fixes #2552 
Milestone: 2.12.1
Changelog:
- Fixed issue where sort PDS feature applied the date description to members without a valid date. #2552 
> fix(sort/ds): Coerce invalid PDS date values to `null` during parsing

- lerna.json
- packages/eslint-plugin-zowe-explorer/CHANGELOG.md
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/shared/utils.ts
- packages/zowe-explorer/src/uss/actions.ts
The important part of this PR that fixes the issue is:
https://github.com/zowe/vscode-extension-for-zowe/blob/b7065698f5b22e7a4df3e2a1f26fb58d6e691c4f/packages/zowe-explorer/src/shared/utils.ts#L292-L293
The other changes in this PR are just to make the save and diff handling more consistent between data sets and USS files.
Milestone: 2.12.2
Changelog: Fixed issue where etag was not updated for USS files after conflict is detected and user selects Overwrite option.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the …
> Fix etag not updated for USS files on overwrite

- packages/eslint-plugin-zowe-explorer/CHANGELOG.md
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/PersistentFilters.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/src/PersistentFilters.ts
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- packages/zowe-explorer/src/utils/LoggerUtils.ts
- pnpm-lock.yaml
- samples/tree-view-sample/package.json
- samples/uss-profile-sample/package.json
Added back lost local storage code, this should allow local storage to be used again and the migration script to kick in for vscode settings of persistent items to move to local storage, this means the history view should behave just like v2 does but with local storage behind the scenes!
Milestone: v3 pre-releases
Changelog: Added back local storage for Zowe Explorer persistent items
> Add back lost local storage code

- packages/eslint-plugin-zowe-explorer/CHANGELOG.md
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/command/mvsCommandHandler.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/command/mvsCommandHandlerTheia.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/command/tsoCommandHandler.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfileManagement.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/shared/actions.i18n.json
- packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json
- packages/zowe-explorer/package.json
- packages/zowe-explorer/src/command/MvsCommandHandler.ts
- packages/zowe-explorer/src/command/TsoCommandHandler.ts
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/globals.ts
- packages/zowe-explorer/src/shared/actions.ts
- packages/zowe-explorer/src/shared/utils.ts
- packages/zowe-explorer/src/uss/actions.ts
- packages/zowe-explorer/src/utils/ProfileManagement.ts
Merge maintenance with 2.12.1 & 2.12.2
Milestone: n/a
Changelog: n/a
> [next] Merge from maintenance with 2.12.1 & 2.12.2

- lerna.json
- packages/eslint-plugin-zowe-explorer/CHANGELOG.md
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- yarn.lock
Prepare 2.13.0 release
Milestone: 2.13.0
Changelog: n/a
> 2.13.0 Release

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/shared/init.ts
Fixes https://github.com/zowe/vscode-extension-for-zowe/issues/1985
Minimize Zowe Explorer `activate()` function to only run functions necessary for `indirect` actions. That way Zowe Explorer will only complete full activation of the `direct` actions if Zowe Explorer is opened (clicking on the Zowe icon in the activity bar for example)
Indirect and Direct actions on Zowe Explorer is those that are used by extenders (indirect) and those that are used straight from the Zowe Explorer UI (direct).
**Direct**
- `tempPath`
- `globals.defineGlobals`
- `hideTempFolder`
- `ProfilesUtils.initializeZoweTempFolder`
- `SettingsConfig.standardizeSettings`
- `globals.setActivated`
**Indirect**
- `ZoweLogger.initializeZoweLogger`
- `ZoweLocalStorage.initializeZoweLocalStorage`
- …
> Minimize activation function

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
- packages/zowe-explorer/src/dataset/actions.ts
Fixes #2616 
There was an existing issue when submitting JCL from the editor right-click option `Submit JCL`, if the use performed this action the JCL file focused in the editor will lose it's focus after clicking on `Submit JCL` which would cause the wrong job to be focused. This PR addresses that same issue.
Milestone: v2.14.0
Changelog: Fixed issue with `Submit JCL` losing focus on JCL being submitted, causing the wrong job submission.
> Retain focus when submitting JCL files from editor right-click action

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/dataset/actions.ts
Fixed the allocate-like functionality by removing the inclusion of DS item created by right click "Allocate Like" context menu option from the filter history
Milestone:
Changelog:
> Allocate-like to exclude DS items from the filter history.

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__mocks__/mockCreators/jobs.ts
- packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/src/job/ZoweJobNode.ts
> feat: Add SMFID to Jobs Tree View

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/src/job/ZoweJobNode.ts
To make spools files order doesn't reverse when the job is expanded and collapsed.
Milestone:
Changelog:
> Bug: Order of Spool files reverses when the job is Expanded and Collapsed

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
Currently, the Local Filtering of Jobs is based on jobid, jobname and return code. With these proposed changes filtering of jobs is even possible with exec-member field.
Milestone:
Changelog:
> Local filtering of Jobs with exec-member field

- package.json
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Jes/ZoweExplorerFtpJesApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/utils/ProfileManagement.ts
- samples/uss-profile-sample/package.json
- samples/uss-profile-sample/yarn.lock
- yarn.lock
Fixes #2633. The patch was made in Imperative, so the only changes in this PR are to update the Zowe CLI package and fix unit tests that broke locally after updating to Node 20.
Milestone: 2.14.0
Changelog: N/A since this bug fix is already listed in the changelog
> Fix "Log out from API ML" missing from Manage Profile menu

- packages/zowe-explorer/src/uss/ZoweUSSNode.ts
Fixes #2675 which was caused by regression introduced in #2634
Milestone: 2.14.0
Changelog: N/A since this is a regression, bug is not present in 2.13.1
> fix(uss): Fix error shown when deleting USS directory

- package.json
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/package.json
- samples/uss-profile-sample/package.json
- yarn.lock
Resolves #2533
Update the version of the FTP plug-in in the zFTP extension
Milestone: 2.14.1 (or 2.15.0)
Changelog: Fix Windows-specific hangs when saving members that contain JCL via the FTP extension. Thanks @tiantn & @std4lqi. [#2533](https://github.com/zowe/vscode-extension-for-zowe/issues/2533)
> fix: Update FTP plug-in version

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
- packages/zowe-explorer-api/src/tree/sorting.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/dataset/utils.i18n.json
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/dataset/utils.ts
To add an additional PDS member sorting option that allows users to sort by Date Created.
Milestone:
Changelog:
> Sorting of PDS members by date created

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/src/job/ZoweJobNode.ts
Solves #2315 
Solve an issue where duplicate dd names in a spool file inside of a job would get overwritten by the last ocurrence. e.g for job:
MyJob Spools:
- Spool1 - `record-count`
- Spool2 - `record-count`
- Spool3 - `record-count`
- Spool3 - `record-count`
Spool 3 will only appear once in the output, now we will append the ID of the spool at the start to provide uniqueness to each spool (as well as prevent real duplicates) and remain consistent to how the CLI also outputs these spools by putting the `id` in the head instead of the `record-count` property at the tail of the label which is not always unique for each spool.
MyJob Spools:
- `id` - Spool1
- `id` - Spool2
- `id` - Spool3
- `id` - Spool3
Milestone: `v2.15.0`
Changelog: Fixed issue where spools with duplicate DD names would …
> `BugFix` Issue with duplicate dd names on job output view

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
This is a port of #2705 for the `next` branch.
Milestone:
Changelog: 
- Fixed issue where `zosmf` profiles did not respect the `protocol` property [#2703](https://github.com/zowe/vscode-extension-for-zowe/issues/2703).
> fix(v3): include protocol in `zosmf` session objects

- packages/zowe-explorer/__tests__/__unit__/command/unixCommandHandler.unit.test.ts
- packages/zowe-explorer/src/command/UnixCommandHandler.ts
As RSE profiles do not require ssh profile for issuing unix commands. Fixing the bug for the line of code  https://github.com/zowe/vscode-extension-for-zowe/blob/e07d93405327995fd83c15622cfb0e7e9633c608/packages/zowe-explorer/src/command/UnixCommandHandler.ts#L336 so that it would work with RSE profiles too.
Milestone:
Changelog:
> Fix bug for Unix command to work with profile that doesn't require ssh

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/l10n/bundle.l10n.json
- packages/zowe-explorer/package.json
- packages/zowe-explorer/package.nls.json
1. Modified the changelog to have the note for the adjusted Jobs tree context menu for the next V3 release
2. Added internationalization string for jobs.filterBy
3. Rearranged the order of items on the jobs context menu (see #2689 for a screenshot)
4. Removed context menu items to edit and delete the profile
Resolves https://github.com/zowe/vscode-extension-for-zowe/issues/2670 for v3.
Milestone:
Changelog:
Adjusted order of 'Manage Profile' and 'Edit History' in the jobs tree's context menu to match the other trees.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This …
> fix(v3): Port jobs context menu changes from 2689

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
Resolves #2660 
Changelog: Updated sorting of PDS members to show items without stats at bottom of list
> feat(ds): Move PDS members without stats to bottom of list

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
To fix error when user clicks on a favourited job (meaning they click on the tree item label, not the expander '>' icon)
Converting circular structure to JSON --> starting at object with constructor 'v' | property 'mParent' -> object with constructor 'v' | property 'children' -> object with constructor 'Array' --- index 0 closes the circle
Milestone:
Changelog:
> Error when user clicks on favorited job

- .github/workflows/zowe-explorer-ci.yml
- .github/workflows/zowe-explorer-ftp-ci.yml
- package.json
- packages/zowe-explorer-api/package.json
- samples/uss-profile-sample/package.json
- yarn.lock
Resolves #2773 
Updates the Zowe CLI dependency, resolving an issue that surfaced from Imperative's `ProfileInfo` class.
Milestone: 2.15.1
Changelog:
> deps: update Zowe CLI to 7.23.6 to pull in Imperative bug fixes

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Port of #2795 for the `next` branch
Milestone:
Changelog:
- Fixed an issue where the `ProfilesCache` class would retain old service profiles, even if they were removed from the team config. [#2395](https://github.com/zowe/zowe-explorer-vscode/issues/2395)
> [v3 port] fix(ProfilesCache): Clear object caches before refresh

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__mocks__/mockCreators/uss.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/shared/init.i18n.json
- packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/shared/init.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- packages/zowe-explorer/src/uss/ZoweUSSNode.ts
- packages/zowe-explorer/src/uss/actions.ts
This PR addresses several issues that can cause the undefined node error:
* Fixes documents being removed from open files map prematurely, before they are actually closed. The event `onDidCloseTextDocument` is misleadingly named - it fires whenever a document's language is changed.
* Fixes creation of new node in `createMember` action so that member name is converted to uppercase. Also the new member's etag is now stored in a child node of the tree instead of an orphan node.
* Fixes logic to find favorited nodes in the tree when saving data sets and USS files. Also updates tests to verify that favorite nodes are found and etags are handled correctly, instead of mocking functions that find the node.
Milestone: 2.15.2
Changelog: Fixed issue where saving changes to favorited data set or USS …
> Fix undefined node error on save

- lerna.json
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Resolves #2395 
Milestone: 2.15.2
Changelog:
- Fixed an issue where the `ProfilesCache` class would retain old service profiles, even if they were removed from the team config.
> fix(ProfilesCache): Clear object caches before refresh

- .github/workflows/deployment.yml
- yarn.lock
Fixes the failing workflow: https://github.com/zowe/zowe-explorer-vscode/actions/runs/8661844096
> Use Node 18 for v1 deployment since ovsx requires it

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/shared/utils.i18n.json
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/job/ZoweJobNode.ts
- packages/zowe-explorer/src/shared/utils.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- packages/zowe-explorer/src/uss/actions.ts
* Fixes document being removed from `openFiles` map prematurely when diff editor is closed
* Fixes node not found on save when favorited file is opened outside of favorites
* Adds error handling for case when file is saved and node cannot be found in tree
Milestone: 2.15.3
Changelog: Fixed issue where saving changes to favorited data set or USS file could fail when it is opened outside of favorites
> Fix undefined node error on save - part 2

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/package.json
Hides the following commands from the Command Palette as they do not function properly without a node or other arguments:
- `Zowe Explorer: Cancel job`
- `Zowe Explorer: Filter jobs`
- `Zowe Explorer: Filter PDS members`
- `Zowe Explorer: Sort jobs`
- `Zowe Explorer: Sort PDS members`
- `Zowe Explorer: Start Polling`
- `Zowe Explorer: Stop Polling`
If we want to add support for running some of these commands in the Command Palette, I'll file an issue to track those. For now, it's best to hide these so users don't try to run them, as there isn't any error handling in place - so any errors will show in a modal dialog. Thanks to @awharn for spotting some of these during our offline discussion 🙂 
Milestone: 2.16.0 (or 2.15.3 if we want to release another patch, whichever is preferred) …
> fix(commands): Hide commands from palette that require nodes/info

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/ZoweExplorerExtender.unit.test.ts
- packages/zowe-explorer/src/ZoweExplorerExtender.ts
Since developers and extenders are the primary users to inform when schema warnings occur, I figured it was best to move this into the log file for now until an "error code" is added to the schema management return values. Once that is available we can choose to show UI messages for specific scenarios - currently, I would have to implement hardcoded checks against error messages and I don't think that is a viable solution.
Milestone:
Changelog:
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the …
> fix(config): Log schema warnings instead of UI warning message

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
Resolves the issue where expanding a PDS member results in a TypeError. The logic for `getSessionNode` was updated for 2.15.3 and now returns the proper node for favorited items. However, due to this change, the sorting logic needs an adjustment to define the `sort` property for sessions under the Favorites folder. 
Milestone: 2.15.4
Changelog:
- Fixed issue where expanding a favorited PDS resulted in an error message.
> fix(ds): resolve TypeError when expanding favorited PDS

- lerna.json
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/src/dataset/actions.ts
Fixes #2857
Milestone: 2.15.4
Changelog: Fixed issue where new PDS member node cannot be re-opened unless you pull from mainframe
> Fix command not assigned to new member nodes

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/i18n/sample/src/dataset/init.i18n.json
- packages/zowe-explorer/i18n/sample/src/job/init.i18n.json
- packages/zowe-explorer/i18n/sample/src/uss/init.i18n.json
- packages/zowe-explorer/src/dataset/init.ts
- packages/zowe-explorer/src/job/init.ts
- packages/zowe-explorer/src/uss/init.ts
This PR addresses issue https://github.com/zowe/zowe-explorer-vscode/issues/2484.  I began by searching the codebase for the string "Pull from Mainframe" and found the associated keys "refreshDataset", "uss.refreshUSS", and "jobs.refreshSpool". This led me to the relevant code sections, where I determined that these keys trigger commands responsible for pulling data from the mainframe in different contexts. I added status bar indicators within the corresponding command handlers in the init.ts file to provide users with visual feedback during "Pull from Mainframe" operations.
Milestone:
Changelog: Added Status bar to indicate that data is being pulled from mainframe.
_Put an `x` in the …
> Fix #2484: Added Status bar to indicate data is being pulled from mainframe.

- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
This updates the FTP extension to use `sha256` instead of `sha1` for hashing file contents (generating fake e-tags).
Milestone: 
Changelog:
- Changed the hashing algorithm for e-tag generation from `sha1` to `sha256`. [#2890](https://github.com/zowe/zowe-explorer-vscode/pull/2890)
- _Reason:_ Hash collisions can occur when using the `sha1` algorithm, so it was replaced to avoid collisions.
> fix(ftp): use 'sha256' instead of 'sha1'

- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
This is a port of the SHA256 change for the next branch.
Milestone: 
Changelog:
> port(v3/ftp): Use `sha256` instead of `sha1`

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Fixes #2910
Milestone:
Changelog: Fixed regression of issue where the `ProfilesCache` class would retain old service profiles, even if they were removed from the team config
> Fix regression with clearing profile object caches on refresh

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/src/job/ZosJobsProvider.ts
- packages/zowe-explorer/src/job/ZoweJobNode.ts
To add the ability to open a Favorited Job Search under Favorites and as well as when the extension is reloaded.
Milestone:
Changelog:
> Unable to open Favorited Job Search

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/src/dataset/actions.ts
1. Solves: https://github.com/zowe/zowe-explorer-vscode/issues/2941
Fix the issue of right-click-Delete option which is deleting the currently open/selected file and not the file which is right-clicked when the names of members are same.
Milestone:
Changelog:
> Fix issue Right-click-delete deletes the wrong program

- package.json
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/SpoolProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/job/actions.i18n.json
- packages/zowe-explorer/src/SpoolProvider.ts
- packages/zowe-explorer/src/job/actions.ts
- samples/uss-profile-sample/package.json
- yarn.lock
Fixes bug where nothing happens when trying to download spool files in the ZE jobs tree.
Milestone: 2.17.0
Changelog: Fixed issue where Download Spool action could fail to find spool files to download
> Fix downloading spool files failing to match tree nodes

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Previously, we ran the `zowe.extRefresh` command to signal a refresh of Zowe Explorer and its extenders when credentials are updated for a profile. While this worked to synchronize credentials in most cases, extender event callbacks for `onProfilesUpdate` were never fired for this scenario.
This updates the logic so that we fire the `onProfilesUpdateEmitter` event when the following conditions are met:
* Secure credentials are enabled in Zowe Explorer
* The credentials were successfully updated on the profile
* Subscribe to the `onProfilesUpdate` event in a Zowe Explorer extender with a test callback, e.g.,
```ts
ZoweVsCodeExtension.getZoweExplorerApi().onProfilesUpdate?.(
(eventType: any) =>
vscode.window.showInformationMessage(`onProfilesUpdate fired, type: ${eventType}` as string)
); …
```
> fix: Fire `onProfilesUpdate` event when secure credentials are updated

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/WebView.unit.test.ts
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-api/src/vscode/ui/WebView.ts
- packages/zowe-explorer-api/src/vscode/ui/utils/HTMLTemplate.ts
- pnpm-lock.yaml
Uses the `mustache` dependency instead of `handlebars` to minimize dependency count.
Changelog:
Removed `handlebars` dependency in favor of `mustache` for technical currency purposes.
**General**
**Deployment**
> refactor: Use Mustache instead of Handlebars

- .github/workflows/theia-zowe-explorer-ci.yml
- packages/zowe-explorer/__tests__/__theia__/extension.theia.test.ts
- packages/zowe-explorer/__tests__/__theia__/theia/Locators.ts
- packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts
- packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts
Fixes #2977 by updating element IDs in tests.
Also updates workflow to use new VSCE directory supported by Theia (see https://github.com/eclipse-theia/theia/pull/13178).
Milestone:
Changelog:
**General**
**Deployment**
This PR is probably a good candidate to be squash merged 😋
> Fix Theia integration tests

- .gitignore
- packages/zowe-explorer/src/webviews/package.json
- Adds the `zedc/target` folder to `.gitignore` so that changing between v2 and v3 branches does not affect working tree
- Updates the webviews `package` script to check for the existence of the `dist` folder
- If it does not exist, it will run `pnpm build`
- Otherwise it will print the message `"webviews: already packaged."`
Milestone: 
Changelog: None
**General**
**Deployment**
- The port will be a part of the `rnd/tables` branch
> fix(v2): add zedc to gitignore; update webviews package script

- .github/release.config.js
Updates the `release.config.js` file:
- handle `release/2.*` branches for new versions
- removes the `maintenance` and `main` branches as `maintenance` was deleted and `main` is no longer used for release.
Milestone: 2.17.0
Changelog:
**General**
**Deployment**
> chore: update release.config.js w/ release wildcard

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
- packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/shared/refresh.unit.test.ts
- packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/shared/init.ts
- packages/zowe-explorer/src/shared/refresh.ts
- packages/zowe-explorer/src/utils/LoggerUtils.ts
- packages/zowe-explorer/src/utils/TreeViewUtils.ts
Ports #3009 from vNext to the main branch
This PR removes some Theia-specific logic in the config watcher. I've tested in Theia that there is no regression for https://github.com/zowe/zowe-explorer-vscode/issues/2211
Changelog: Fixed issue where creating a new team configuration file could cause Zowe Explorer to crash, resulting in all sessions disappearing from trees
**General**
**Deployment**
- Otherwise, please check with the rest of …
> fix: Fix sessions disappearing from trees caused by `zowe.extRefresh`

- package.json
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-ftp-extension/webpack.config.js
- packages/zowe-explorer/package.json
- packages/zowe-explorer/webpack.config.js
- pnpm-lock.yaml
**What It Does**
Fixes regression of #2686 in the vNext branch after we migrated from `ts-loader` to `esbuild-loader`
Although `esbuild` doesn't officially support TS project references, we can trick it into supporting them by adding an `exports` section to ZE API package.json as suggested in https://github.com/evanw/esbuild/issues/1250#issuecomment-1463826174.
Also removes 2 Webpack plugins:
* `copy-webpack-plugin` - It tried to overwrite files on every incremental build which could cause file access errors on Windows. Replaced with a `copy-secrets` npm script that runs only on build.
* `tsconfig-paths-webpack-plugin` - It conflicts with the `conditionNames` configuration added in this PR.
**How to Test**
* Launch the debug task to run ZE or the FTP extension which starts a watch task in …
> build(v3): Fix watch task to detect changes in ZE API package

- packages/zowe-explorer/src/Profiles.ts
Fixes 2 code smells detected by Coverity for nullable values
Milestone:
Changelog:
**General**
**Deployment**
> Fix Coverity code smells in Profiles.ts

- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
- packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
- packages/zowe-explorer/src/shared/utils.ts
- packages/zowe-explorer/src/uss/actions.ts
See build breaking in some instances, this PR addresses that removing imports from Zowe SDKs and point the import to the already used zowe/cli dependency.  Full migration to the SDKs is in the v3 work.
Changelog: n/a
**General**
**Deployment**
> Adjust imports to main 

- packages/zowe-explorer-api/src/vscode/ui/WebView.ts
Fixes regression introduced in #3023 where Edit History webview fails to open when debugging ZE:
Milestone: N/A
Changelog: N/A
**General**
**Deployment**
The fix was inspired by https://github.com/janl/mustache.js/issues/786#issuecomment-870894150 😋
> Fix mustache import for webviews

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__mocks__/vscode.ts
- packages/zowe-explorer-api/src/extend/IApiExplorerExtender.ts
- packages/zowe-explorer-api/src/extend/MainframeInteraction.ts
- packages/zowe-explorer-api/src/fs/types/abstract.ts
- packages/zowe-explorer-api/src/tree/IZoweTree.ts
- packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__mocks__/DatasetTree.ts
- packages/zowe-explorer/__tests__/__mocks__/USSTree.ts
- packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/src/commands/ZoweCommandProvider.ts
- packages/zowe-explorer/src/configuration/Profiles.ts
- packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
- packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
- packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
- packages/zowe-explorer/src/trees/job/JobTree.ts
- packages/zowe-explorer/src/trees/shared/SharedInit.ts
- packages/zowe-explorer/src/trees/uss/USSTree.ts
- packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
- samples/uss-profile-sample/src/SshUssApi.ts
- Add return types as needed
- To Be Discussed 😋 
- Fix #2952
Milestone: 3.0
Changelog: Added missing return types to Zowe Explorer API programmatic interfaces.
**General**
**Deployment**
TODO:
> types: Add missing return types, see #2952

- package.json
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/package.json
- packages/zowe-explorer-ftp-extension/package.json
- packages/zowe-explorer/package.json
- samples/uss-profile-sample/package.json
- yarn.lock
Update CLI dependency in ZE API to fix https://github.com/zowe/zowe-cli/issues/2219
Changelog: Updated the `@zowe/cli` dependency to fix error when using session with auth type "none"
**General**
**Deployment**
> Update CLI dependency in ZE API

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__mocks__/vscode.ts
- packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/ZoweExplorerExtender.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/src/Profiles.ts
- packages/zowe-explorer/src/ZoweExplorerExtender.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fixes #3074
Changelog: Fixed JSON errors being ignored when `zowe.config.json` files change on disk and are reloaded
**General**
**Deployment**
> Fix ZE activation and commands failing when team config contains JSON error

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/fs/BaseProvider.unit.test.ts
- packages/zowe-explorer-api/src/fs/BaseProvider.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
- packages/zowe-explorer/package.json
- packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
- packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
- Fixes a bug with the BaseProvider where the new remote lookup functionality caused the local side of conflict to update during a conflict resolution.
- Fixes the issue where conflict icons show when comparing two files w/ a Zowe scheme.
Changelog:
- Fixed an issue where remote lookup functionality caused the local side of a conflict to be overwritten with the remote contents.
- Fixed an issue where the remote conflict icons showed when using the "Compare with Selected" feature.
**General**
**Deployment** …
> fix(v3): Hide conflict icons during normal diff; fix remote lookup causing local side of conflict to update

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/shared/init.ts
Fixes an issue where the event callback for the Team Config file watcher stopped abruptly before firing the emitter for extenders. 
Changelog: 
- Resolved an issue where extender event callbacks were not always fired when the team configuration file was created, updated or changed. [#3078](https://github.com/zowe/zowe-explorer-vscode/issues/3078)
**General**
**Deployment**
- Otherwise, please check with the rest of the squad about any …
> fix(v2): `onProfilesUpdate` does not always fire for extenders

- .github/workflows/merge-by-comments.yml
- .github/workflows/merge-by-table.yml
- .github/workflows/merge-by/build-table-and-notify.js
- .github/workflows/merge-by/post-date.js
Adds two new workflows to the `.github` folder of the repo:
- posts merge-by dates when a new PR is opened (not in draft state) or marked as ready, as well as for existing PRs (before this workflow) once a new change is pushed
- check the comment below by **github-actions[bot]** to see it in action 😋 
- updates a [PR Status List](https://github.com/zowe/zowe-explorer-vscode/discussions/3091) in the Discussions tab with PRs that have a merge-by date <= 1 week away
- posts a reminder on open PRs with merge-by dates <24 hours away, tagging attached reviewers who haven't yet approved
**General**
> ci: Automated merge-by comments and table

- .github/workflows/merge-by-comments.yml
- .github/workflows/merge-by-table.yml
- .github/workflows/merge-by/build-table-and-notify.js
- .github/workflows/merge-by/post-date.js
_port of #3090 for `next` branch_
Adds two new workflows to the `.github` folder of the repo:
- posts merge-by dates when a new PR is opened (not in draft state) or marked as ready, as well as for existing PRs (before this workflow) once a new change is pushed
- check the comment below by **github-actions[bot]** to see it in action 😋 
- updates a [PR Status List](https://github.com/zowe/zowe-explorer-vscode/discussions/3091) in the Discussions tab with PRs that have a merge-by date <= 1 week away
- posts a reminder on open PRs with merge-by dates <24 hours away, tagging attached reviewers who haven't yet approved
**General**
> ci(v3): Automated merge-by comments and table

- lerna.json
- packages/eslint-plugin-zowe-explorer/CHANGELOG.md
- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer/CHANGELOG.md
v3 Pre-release of changes from week 1 September 2024
Changelog: n/a
**General**
**Deployment**
> V3 pre-release Sept week 1

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer/CHANGELOG.md
v3 pre-release scheduled for week 2 of September
Changelog: n/a
**General**
**Deployment**
> v3 pre-release Sept week 2

- .github/workflows/auto-comment.yml
- .github/workflows/update-project.yml
- package.json
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/utils/LoggerUtils.unit.test.ts
- packages/zowe-explorer/src/globals.ts
- packages/zowe-explorer/src/utils/LoggerUtils.ts
- packages/zowe-explorer/src/utils/SettingsConfig.ts
- samples/menu-item-sample/yarn.lock
- samples/tree-view-sample/yarn.lock
- samples/uss-profile-sample/yarn.lock
- samples/vue-webview-sample/yarn.lock
- yarn.lock
Fixing command for v2 as to not break ZE when used.
Also ports https://github.com/zowe/zowe-explorer-vscode/pull/3102 to v2.18.1 release branch
Proposal for v3:
With the introduction of the Event management and removal of all instance of Zowe Explorer using the zowe.extRefresh command I propose possible removal of command from command palette and suggest users use the new command from VS Code `Extensions: Refresh` in v3.
Changelog: Fix issue where the Zowe Explorer VS Code command `Refresh Zowe Explorer` failed catastrophically. [#3100](https://github.com/zowe/zowe-explorer-vscode/issues/3100)
**General** …
> [v2] Fix for extension failure with refresh Zowe Explorer command

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableViewProvider.unit.test.ts
- packages/zowe-explorer-api/src/vscode/ui/TableViewProvider.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/package.json
Hides the "Zowe Resources" panel until a table view is provided to the `TableViewProvider`.
We (as well as extenders) can also hide the panel by invoking `TableViewProvider.setTableView` with `null` as the parameter.
Changelog:
- Added placeholder text to the "Zowe Resources" panel to provide clarity when a table is not visible.
**General**
**Deployment**
- Otherwise, please check with the rest of the squad about any needed documentation …
> fix(ux): Hide Zowe Resources panel until content is shown

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer/CHANGELOG.md
Fixed a bug where old profiles remained in the Zowe Explorer tree views after deleting a Team configuration file. [#3124](https://github.com/zowe/zowe-explorer-vscode/issues/3124)
Set a breakpoint at the end of `ProfilesCache.refresh` and then delete your team config.
Notice that at the end of the refresh call, all of the cache structures are emptied as a result. All profiles from that team config will be removed from the tree views.
Changelogs:
- **ZE:** Fixed bug where old profiles remained in the Zowe Explorer tree views after deleting a Team configuration file. [#3124](https://github.com/zowe/zowe-explorer-vscode/issues/3124)
- **ZE API:** Fixed bug in `ProfilesCache` class where old profiles were still accessible after deleting a Team configuration file. …
> fix(v3): Continue refresh even when team config doesn't exist

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
- packages/zowe-explorer/src/configuration/Profiles.ts
Solves #3122 
Fix bug regarding extender profiles not being added to the config file during creation.
Milestone:
Changelog: Fix issue with extender profiles not being included in fresh team configuration file. [#3122]
**General**
**Deployment**
> fix(v3): Not including extenders in Team config during creation

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
- packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
Solves #2632 
To fix the incorrect job label under favorites when VSC is reloaded
Milestone:
Changelog:
**General**
**Deployment**
> To fix Strange behaviour of Job label under Job Favorites

- .gitignore
- packages/zowe-explorer/package.json
- packages/zowe-explorer/scripts/stripL10nComments.js
Adds a script that strips comments out of `bundle.l10n.json`, sorts properties by key, and saves a new file `bundle.l10n.json.template`.
Use this command to run the script from top level of repo: `pnpm --filter vscode-extension-for-zowe strip-l10n`
Milestone: 3.0.0
Changelog: N/A
**General**
**Deployment**
> Add npm script to strip l10n comments

- packages/zowe-explorer-ftp-extension/CHANGELOG.md
- packages/zowe-explorer-ftp-extension/src/extension.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
- packages/zowe-explorer/l10n/poeditor.json
- packages/zowe-explorer/package.json
- packages/zowe-explorer/package.nls.json
- packages/zowe-explorer/src/configuration/Constants.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/trees/shared/SharedInit.ts
fix for #2862 & #3100 
log writing can be found at `~/.vscode/extension/zowe.zowe-explorer-ftp-extension-3.0.0-next-SNAPSHOT/logs`
Milestone: 3.0 GA
Changelog:
ZE - Removal of broken VSC command `Zowe Explorer: Refresh Zowe Explorer`, use VS Code's `Extensions: Refresh` command instead. [#3100](https://github.com/zowe/zowe-explorer-vscode/issues/3100)
zFTP - Removed popup notification of successful registration with Zowe Explorer and log the success instead. [#2862](https://github.com/zowe/zowe-explorer-vscode/issues/2862)
**General**
**Deployment** …
> Remove extRefresh cmd & FTP registration popup

- .github/release.config.js
**What It Does**
This PR updates the `release/3.*` branch to publish patch releases, as well as the latest tag to match the same version as zowe-v3-lts going forward.
This PR should be merged only after the Zowe v3.0 announcement 😋
> Update release.config.js for Zowe V3 GA

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fixed a bug where a new `ProfileInfo` instance was being created when initializing Zowe profiles, but that instance was missing the `homeDir` and `projectDir` from its constructor options.
Changelog:
- Fixed an issue where `ProfilesUtils.getProfileInfo` returned a new `ProfileInfo` instance that did not respect the home directory or workspace paths. [#3168](https://github.com/zowe/zowe-explorer-vscode/issues/3168)
**General**
**Deployment**
- If you're an outside contributor, please post in the [#zowe-doc Slack channel](https://openmainframeproject.slack.com/archives/CC961JYMQ) to coordinate …
> [v2] fix(profiles): Pass `homeDir, projectDir` when creating `ProfileInfo` instance

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fixed a bug where a new `ProfileInfo` instance was being created when initializing Zowe profiles, but that instance was missing the `homeDir` and `projectDir` from its constructor options.
Milestone: 3.0.1
Changelog:
- Fixed an issue where Zowe Explorer displayed a "No Zowe client configurations" prompt when a project user configuration existed but no global configuration was present. [#3168](https://github.com/zowe/zowe-explorer-vscode/issues/3168)
- Fixed an issue where the `ProfilesUtils.getProfileInfo` function returned a new `ProfileInfo` instance that ignored the `ZOWE_CLI_HOME` environment variable and workspace paths. [#3168](https://github.com/zowe/zowe-explorer-vscode/issues/3168)
**General**
- …
> fix(profiles): Pass `homeDir, projectDir` when creating `ProfileInfo` instance

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
- packages/zowe-explorer/src/uss/actions.ts
- Fixed an issue where the location prompt for the `Create Directory` and `Create File` USS features would appear even when a path is already set for the profile or parent folder. [#3183](https://github.com/zowe/zowe-explorer-vscode/pull/3183)
- Fixed an issue where the `Create Directory` and `Create File` features would continue processing when the first prompt was dismissed, causing an incorrect path to be generated. [#3183](https://github.com/zowe/zowe-explorer-vscode/pull/3183)
- Fixed an issue where the `Create Directory` and `Create File` features would incorrectly handle user-specified locations with trailing slashes. [#3183](https://github.com/zowe/zowe-explorer-vscode/pull/3183)
Changelog: See `Proposed changes`
**General**
- **v2 and below:** `yarn workspace …
> fix(v2): prompt optimizations for create file/dir; address case of skipping prompt

- packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
- packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
Fixes an issue where if you search for jobs with a valid ID, and then search a second time with an invalid job ID, the results from the first search persist instead of emptying the list of child nodes.
Milestone: 3.0.1
Changelog: N/A since this issue does not exist in 3.0.0
**General**
**Deployment**
> Fix children in tree nodes persisting on error

- .github/workflows/deployment.yml
- .github/workflows/lint.yml
porting changes to `main` for #3226
> ci: change node versions on lint & deployment workflows

- .github/workflows/zowe-explorer-ci.yml
`libsecret` was removed from the Ubuntu 24.04 runner images. For the time being, we can use the `ubuntu-22.04` image in CI until we get clarification on whether this change was intentional.
> fix(ci): Use `ubuntu-22.04` images to get access to libsecret

- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Works around a bug with `imperative.ProfileInfo.onlyV1ProfilesExist` - it currently looks at the team config on `ImperativeConfig.instance`, but this is not defined through Zowe Explorer, so the getter function ignores presence of a team config.
Milestone: 3.0.2
Changelog:
**General**
**Deployment**
> fix: add ProfileInfo.getTeamConfig.exists check to v1 profile prompt

- packages/zowe-explorer/package.json
- packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentUtils.ts
- packages/zowe-explorer/src/webviews/src/table-view/ActionsBar.tsx
This PR mainly deals with the optional comments left in PR: #3162 
1. Remove build:nlsExtract from package.json as we already have `generateLocalization`
2. Removed localization for one of internal error message.
Milestone:
Changelog:
**General**
**Deployment**
> Remove duplicate build:nlsExtract from package.json for webview localization

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__mocks__/vscode.ts
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
- packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
- packages/zowe-explorer/src/trees/job/JobFSProvider.ts
- packages/zowe-explorer/src/trees/job/JobTree.ts
- packages/zowe-explorer/src/trees/uss/USSTree.ts
- packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
VS Code does not explicitly document that you need to use their `vscode.workspace.fs` façade when deleting or renaming entries in a file system implementation. If you do it directly through the implementation, other services (such as the editor service) are not made aware of the change.
This will make the editors behave properly such that:
- a deleted URI is reflected *permanently* in an open editor
- a renamed URI is updated in the editor to show the new path with existing contents
Milestone: 3.0.3
Changelog:
- Fixed an issue where renaming or deleting a USS file or data set did not update the opened editor. [#3260](https://github.com/zowe/zowe-explorer-vscode/issues/3260)
**General**
- **v3:** `pnpm …
> fix: use `vscode.workspace.fs` for `delete` and `rename`

- .github/workflows/deployment.yml
Updates our deployment workflow to allow it to be triggered manually only by repo admins.
Merging this PR into `main` branch should allow the deployment workflow to be triggered for any other branch.
> Allow deployment workflow to be triggered manually

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__mocks__/vscode.ts
- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
- packages/zowe-explorer/package.json
- packages/zowe-explorer/package.nls.json
- packages/zowe-explorer/src/configuration/Constants.ts
- packages/zowe-explorer/src/trees/shared/SharedInit.ts
- packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Resolves #3265 
Doc: 
Virtual workspaces can be used to access multiple resources from the Explorer pane, such as local files or resources from other schemes. Zowe Explorer v3 now supports virtual workspaces for Data Sets and USS files or folders.
To add a resource to a virtual workspace:
1. Click the magnifying glass icon beside a profile in the Data Sets or Unix System Services (USS) tree.
2. Type in a data set search pattern or a USS file path and execute the search.
3. Once resources are listed in the tree view, right click on an item and select the "Add to Workspace" context menu option.
4. A message "Extension Zowe Explorer has added X folder(s) to the workspace" is presented in the status bar. The resource is accessible in the Explorer pane of VS Code.
Changelog:
- …
> feat: 'Add to Workspace' context menu option (Data Sets & USS resources)

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetInit.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
- packages/zowe-explorer/src/extension.ts
- packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
- packages/zowe-explorer/src/utils/ProfilesUtils.ts
Fixes #3280
Milestone: 3.0.3
Changelog:
- Fixed issue where Zowe Explorer would present the "No configs detected" notification before it was used in a workspace without a Zowe config. [#3280](https://github.com/zowe/zowe-explorer-vscode/issues/3280)
**General**
**Deployment**
> fix: Only show "No configs detected" prompt if ZE opened

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Extenders can fetch a USS resource on demand using `vscode.workspace.fs.stat()` with the `fetch=true` query. When done with a USS file that has not expanded in the USS tree view, Zowe Explorer gets stuck in an infinite loop of calling `stat()` over and over again. Here's how it happens:
1. `vscode.workspace.fs.stat()` is called for a USS resource with the fetch query set to true. Example: `vscode.workspace.fs.stat(zowe-uss:/zosmf/user/test.txt)`
2. `UssFSProvider.remoteLookupForResource()` is called to fetch the file from the host.
3. This eventually calls `UssFSProvider.fetchEntries()`. `fetchEntries()` checks if the parent directory of the requested file is in the file system. If it's not, `await vscode.workspace.fs.createDirectory(parentUri)` is called on line 191 to create it.
4. …
> Fix infinite loop when fetching USS resources with stat()

- package.json
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/TreeViewUtils.unit.test.ts
- packages/zowe-explorer/src/dataset/DatasetTree.ts
- packages/zowe-explorer/src/uss/USSTree.ts
- packages/zowe-explorer/src/utils/TreeViewUtils.ts
- yarn.lock
v2 port of the error dialog from #3326 
Changelog:
- Fixed an issue where renaming a data set with unsaved changes did not cancel the rename operation. Now, when renaming a data set with unsaved changes, you will be prompted to resolve them before continuing. [#3328](https://github.com/zowe/zowe-explorer-vscode/pull/3328)
**General**
**Deployment**
- Otherwise, please check with the rest of the squad about any needed documentation before …
> fix(v2): Show error for unsaved data set rename

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/ZoweDatasetNode.unit.test.ts
- packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/dataset/actions.ts
Fixes the following issues:
- Fixed an issue where a migrated data set is unusable after it is recalled through Zowe Explorer
- Fixed an issue where a recalled PDS is expandable after it is migrated through Zowe Explorer
- Fixed an issue where data set nodes did not update if migrated or recalled outside of Zowe Explorer
Changelog:
- Fixed an issue where a migrated data set is unusable after it is recalled through Zowe Explorer. [#3294](https://github.com/zowe/zowe-explorer-vscode/issues/3294)
- Fixed an issue where a recalled PDS is expandable after it is migrated through Zowe Explorer. [#3294](https://github.com/zowe/zowe-explorer-vscode/issues/3294)
- Fixed an issue where data set nodes did not update if migrated or recalled outside of Zowe Explorer. …
> fix(v2): Update migrated and recalled data sets in tree

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Resolves #3347 
1. Set a valid search pattern on a profile in your Data Sets tree.
2. Open one of the datasets in the list with a specific encoding - right-click -> "Open with Encoding"
3. Select an encoding to open the data set in an editor tab.
4. Once opened, set a search pattern on your profile that returns no results (ex: PROWOBUF).
5. Then, set the same search pattern used in step 1.
6. Once the search is finished, the data sets are listed without any errors.
Following the same steps when using the `main` branch or 3.0.3 VSIX results in a TypeError.
Milestone: 3.1.0 (or a 3.0.4 if needed?)
Changelog:
- Fixed an issue where listing data sets resulted in an error after opening a data set with an encoding. [#3347](https://github.com/zowe/zowe-explorer-vscode/issues/3347)
**General**
- …
> fix: TypeError when listing data sets after opening one w/ encoding

- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Add check for ISession before assigning proxy info
Changelog: n/a since new functionality needed fix
**General**
**Deployment**
> Add check for ISession before assigning proxy info

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__mocks__/vscode.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/USSInit.unit.test.ts
- packages/zowe-explorer/src/trees/uss/USSInit.ts
Fixes #3355 
Changelog:
- Fixed an issue where binary USS files were not fetched using the "Pull from Mainframe" context menu option. [#3355](https://github.com/zowe/zowe-explorer-vscode/issues/3355)
**General**
**Deployment**
> fix(uss): Support "Pull from Mainframe" w/ binary files

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/uss/init.ts
Fixes #3355 
Changelog:
- Fixed an issue where binary USS files were not fetched using the "Pull from Mainframe" context menu option. [#3355](https://github.com/zowe/zowe-explorer-vscode/issues/3355)
**General**
**Deployment**
> [v2] fix(uss): Support "Pull from Mainframe" w/ binary files

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
- packages/zowe-explorer/src/uss/ZoweUSSNode.ts
- yarn.lock
Fixes #2486 
1. Search for a USS directory under one of your profiles containing a lot of files
2. Scroll to a point in the list where files take up the entire space in the USS tree
3. Click on a file at the top of the list and start scrolling immediately
4. Notice that the tree no longer snaps to the item you last clicked, and the file is opened in the editor
In v2.18.0, scrolling after clicking a file results in the tree snapping back to the selected item.
Changelog:
- Fixed an issue where clicking on a file in the Unix System Services tree caused the tree to abruptly change focus to the selected item. [#2486](https://github.com/zowe/zowe-explorer-vscode/issues/2486)
**General**
- **v3:** …
> [v2] fix(uss): Opening file in tree causes focus to abruptly change

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/abstract/ZoweSaveQueue.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/workspace.unit.test.ts
- packages/zowe-explorer/i18n/sample/src/uss/USSTree.i18n.json
- packages/zowe-explorer/i18n/sample/src/utils/TreeViewUtils.i18n.json
- packages/zowe-explorer/i18n/sample/src/utils/workspace.i18n.json
- packages/zowe-explorer/src/abstract/ZoweSaveQueue.ts
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/uss/actions.ts
- packages/zowe-explorer/src/utils/workspace.ts
- yarn.lock
Fixes #2406, #2627 
**Error message shown when Auto Save is enabled:**
- Locate a UNIX file or data set with insufficient write permissions.
- Open this resource in Zowe Explorer.
- Enable Auto Save and make changes to the file
- Notice that when the save error occurs, the document is marked unsaved and no more save requests are made. Notice that Auto Save is also disabled.
- Try enabling the Auto Save feature using either the "Enable Auto Save" option in this dialog, or by using the Command Palette -> "Files: Toggle Auto Save". The process will repeat at this point, but the save request will only happen once.
When Auto Save is used with v2.18.0, save requests were continuously added for each data set and file that failed to save. Even if you would try to close the file or dismiss the …
> fix(v2): Toggle off Auto Save and warn user after save error

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
- packages/zowe-explorer/package.json
- packages/zowe-explorer/src/trees/job/JobFSProvider.ts
- packages/zowe-explorer/src/trees/job/JobTree.ts
- packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
- packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Adds the ability to open a job spool file with an encoding as described in #1941 
Changelog: 
- Added `Open with Encoding` to the context menu of Job Spool files. [#1941](https://github.com/zowe/zowe-explorer-vscode/issues/1941)
- Added optional `setEncoding`, `getEncoding`, and `getEncodingInMap` functions to the `IZoweJobTreeNode` interface. [#3361](https://github.com/zowe/zowe-explorer-vscode/pull/3361)
**General**
**Deployment**
- …
> Add ability to view Job Spool with encoding

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/trees/shared/SharedUtils.ts
- packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
Fixes an issue where two profiles with the same dataset would share the same cached encoding value.
- Get 2 LPARs and search for the same data set (`SYS1.PARMLIB`)
- Find a member with the same name in the data set for both LPARs
- Right-click on the member in one LPAR -> "Open with Encoding" -> select "Binary"
- Right-click on the member in the second LPAR. Notice that no encoding is cached, and the default quick pick options for this menu are shown.
- Now right-click on the member under the first LPAR that was opened as binary and select "Open with Encoding." The cached encoding is displayed as the placeholder in the quick pick.
In v3.0.3, right-clicking on the member in the second LPAR causes it to show "binary" as the cached encoding, which should not be the case. …
> fix: store cached encoding by URI path instead of label/short path

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
- packages/zowe-explorer/src/shared/utils.ts
Ports #3253 to v2-lts branch
Milestone:
Changelog: Fixed an issue where "Open with Encoding" menu failed when tagged encoding was selected for a binary USS file
**General**
**Deployment**
> [v2] Port fix for Open with Encoding quickpick

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
- Resolves #3327 
Milestone: 3.1.1
Changelog: Prevented data-loss when creating a new member called something that already exists.
**General**
**Deployment**
> fix: Avoid data-loss when creating new members

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__mocks__/mockCreators/jobs.ts
- packages/zowe-explorer/__tests__/__unit__/trees/job/JobTableView.unit.test.ts
- packages/zowe-explorer/src/trees/job/JobTableView.ts
- packages/zowe-explorer/src/webviews/src/table-view/style.css
- Implements #3055 
- Resolves a small UX issue with inconsistent height for table views after resizing the VS Code Panel.
Changelog:
- **Enhancement:** Added Time Started, Time Ended, and Time Submitted job properties to the Jobs table view. [#3055](https://github.com/zowe/zowe-explorer-vscode/issues/3055)
- **Bug fix:** Resolved user interface bug with tables that caused an inconsistent table height within the VS Code Panel. [#3389](https://github.com/zowe/zowe-explorer-vscode/pull/3389)
**General**
**Deployment** …
> feat: Add time started, submitted and ended fields to Jobs table view

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
- Cherry-pick #3392
Changelog: Fixed data loss when creating a data set member with the same name as an existing member. When creating a new member, the user is now prompted to replace it if the member already exists.
**General**
**Deployment**
> fix: Avoid data-loss when creating new members (#3392)

- packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts
- packages/zowe-explorer-api/src/profiles/AuthHandler.ts
- packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
- packages/zowe-explorer/src/trees/job/JobFSProvider.ts
- packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Fixes #3408
Sorry for the oversight @benjamin-t-santos @phaumer - I did not intend to limit extenders to sequential processing, but I had inadvertently done so by forcing the filesystem to acquire the mutex for each request. With these changes, the filesystem only waits for the mutex to be unlocked *after* a 401 error is encountered *and* if the extender explicitly enables their profile type to use locks (using `AuthHandler.enableLocksForType`). This allows extenders to:
- perform their own credential management (detecting your API's credential error, then prompting for credentials), 
- leverage Zowe Explorer's credential prompting/log in functionality as usual (default behavior) without using/waiting for the locks
- or opt-in to the locks, which prevents repeated requests for REST API …
> fix: call Mutex.waitForUnlock instead of locking profile before request

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
Milestone:
Changelog:
**General**
**Deployment**
> fix(ds): Pass correct DS name in `stat` when doing remote lookup

- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Jes/ZoweExplorerFtpJesApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
- packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/src/dataset/actions.ts
- Resolves #3327 
Milestone: next V2 release
Changelog: Prevented data-loss when creating a new member called something that already exists.
**General**
**Deployment**
> fix(v2): avoid data-loss when creating new members

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
Fixes https://github.com/zowe/zowe-explorer-vscode/issues/3345
Milestone:
Changelog:
**General**
- [ x] All PR dependencies have been merged and published (if applicable)
**Deployment**
> Unable to open a Renamed Sequential DS 

- packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
- packages/zowe-explorer/src/trees/job/JobTree.ts
Added try catch block for openWithEncoding function in order to catch any of the errors thrown.
Milestone:
Changelog:
**General**
**Deployment**
> Add ErrorHandling for OpenWithEncoding function

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/trees/shared/SharedHistoryView.ts
- packages/zowe-explorer/src/webviews/src/edit-history/App.tsx
- packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentDataPanel.tsx
There are two parts to this bug:
1. When the edit history webview first opened, the ready message was not being sent so it was no populating the fields
2. When the selection field was being changed, the data inside each tab was not being refreshed
This fixes both of these issues. However, the first part caused a test to fail as the refresh is now happening too fast for the test, meaning that `getHistoryData` would return undefined data. Therefore, I also had to update the `getHistoryData` method to handle the case where a tree provider might not be found.
Milestone:
Changelog: Fixed a bug where edit history does not show the correct information.
**General**
- **v3:** `pnpm --filter vscode-extension-for-zowe …
> Fix edit history does not show the correct information

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/src/vscode/ui/TableViewProvider.ts
Updates access modifier for constructor and properties of `TableViewProvider` so it can be extended by extenders for their own panels.
Milestone: 3.1.1 (or 3.2.0, no strong preference)
Changelog: No changelog needed as behavior is non-breaking & has no effect on current ZE logic
**General**
**Deployment**
> refactor(TableViewProvider): make constructor & properties protected

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/commands/MvsCommandHandler.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/commands/TsoCommandHandler.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/commands/UnixCommandHandler.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
- packages/zowe-explorer/src/commands/ZoweCommandProvider.ts
Ports #3440 to the release/3.1 branch in preparation for a 3.1.2 patch release.
Changelog: Fixed an issue where cancelling Unix, MVS or TSO command still submits the command.
**General**
**Deployment**
> Port #3440 to release/3.1

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
- packages/zowe-explorer/src/trees/job/JobTableView.ts
- packages/zowe-explorer/src/webviews/src/table-view/types.ts
Fixes #3473 by using the `initialSort` property for the `Name` columns for both the Jobs table and the Data Set search table. The `initialSort` property is only applied when creating a new column, which allows for sort options to persist after row selection and table actions. When the sort is changed on a column by clicking on its header, its definition is updated - however, setting the `sort` property for the columns themselves overrides any updates to the column definitions.
I've also made a small change to column definitions so that they are explicitly marked as sortable. This could be seen as breaking, but this is done by AG Grid by default, so this change just makes our column definition logic explicit.
See [this page on AG grid column …
> fix: Use `initialSort` instead of `sort` in table column definitions

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
- packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Makes recall/refresh logic more reliable by first checking for the presence of the `migr` property.
However, while this does not directly fix #3471, it ensures that our logic is always correct. The refresh logic is working as expected - sometimes the mainframe system does not recall the data set immediately, even if the recall API returned a successful response, but we can only update the node based off of information we receive at the time of the refresh. This varies from system to system based on configuration and the archive tool used. 
Unfortunately, we cannot subscribe to events using z/OSMF REST APIs, so the user might have no other choice than to refresh the tree once they know the data set is recalled.
This also implements #3487
Changelog:
-  Fixed an issue where …
> refactor(node/ds): Make recall/migration logic more reliable

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/src/tree/IZoweTree.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerExtender.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
- packages/zowe-explorer/l10n/bundle.l10n.json
- packages/zowe-explorer/l10n/poeditor.json
- packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
- packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
- packages/zowe-explorer/src/trees/job/JobTree.ts
- packages/zowe-explorer/src/trees/uss/USSTree.ts
package and install for testing
reuse initialization of favorites code for a new optional tree method refreshFavorites() that is now called after adding session to the tree
can use ftp to recreate and test fix
Milestone: 3.1.2 ?
Changelog:
ZE API - Added new optional `refreshFavorites` to IZoweTree interface. [#3470](https://github.com/zowe/zowe-explorer-vscode/issues/3470)
ZE - Fixed an issue seen where extender favorites not showing in the tree views. [#3470](https://github.com/zowe/zowe-explorer-vscode/issues/3470)
**General**
**Deployment** …
> Fix for extenders favorites not loading after registration

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts
- packages/zowe-explorer-api/src/profiles/AuthHandler.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
- packages/zowe-explorer/src/trees/shared/SharedInit.ts
- packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
- packages/zowe-explorer/src/utils/AuthUtils.ts
- Adds a 30 second timeout to `waitForUnlock` to prevent deadlocks when using the function (safety mechanism)
- "Debounces" credential prompts from parallel requests to a mainframe system by only showing one credential prompt, until the user answers that prompt. 
- **Behavior remains unchanged:** If the user selects "Cancel" or closes the dialog, the profile remains locked. The user can update their profile through the tree views through the "Manage Profile" to unlock the profile in the filesystem.
- Resolves an issue where the user was spammed with multiple credential prompts when using a virtual workspace with a profile w/ invalid credentials.
- **Eliminated cached profile use in filesystems:** All filesystem requests will get the latest profile object to prevent invalid, cached …
> Debounce credential prompts and check profile locks in more places

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/src/dataset/actions.ts
Avoid extra prompts when the user already decided to replace the existing member
Fix #3420
Changelog: Avoids unnecessary prompting after choosing to replace the existing member
**General**
**Deployment**
> fix: avoid extra prompts when replacing conflicting member on creation

- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
- packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
In PR #3515 I tried to port the debounce PR and #3457, and in the process I accidentally overwrote a change from my PR that was not yet resolved in the other PR. Although the change is small, this ensures that upload operations still use the latest profile rather than the cached one. 
I also realized that the changes in #3457 did not completely resolve the cached profile issue w/ the data sets & USS providers, as it was still using cached profiles in certain places. This PR refactors those functions so both providers use the latest profile for any operation. I'll make sure these changes are also added to `main` so we do not experience a regression in 3.2.0.
Changelog: No changelog, changelogs are already present w/ these fixes
**General**
- **v2 and below:** `yarn …
> port: line overwritten by another port; avoid using cached profiles

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/init.unit.test.ts
- packages/zowe-explorer/src/dataset/init.ts
Ports #3549 to fix #3545 for `v2-lts`
Changelog:
- Fixed an issue where the attributes were not shown for VSAM data sets when using the Show Attributes feature.
**General**
**Deployment**
> fix(v2): Show Attributes not working for VSAM data sets

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
- packages/zowe-explorer/src/dataset/actions.ts
- packages/zowe-explorer/src/utils/TreeViewUtils.ts
Ports #3539 to v2-lts branch
Changelog: Fixed an issue where right-click menu for data set shows wrong options after deleting multiple PDS members
**General**
**Deployment**
> v2: Fix wrong context menu options after deleting members

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
- packages/zowe-explorer/src/trees/uss/USSTree.ts
Fixes two issues:
- Searching for the root directory (`/`) under a profile caused the profile to show a placeholder rather than a list of the files and folders at that path
- Edge case for `cd ..` / "Go Up One Level" (blocked by above issue)
Issue 1 (searching for root dir):
- Click on the magnifying glass beside a profile in the USS tree
- Enter in the root directory as the directory to search (`/`)
- Notice that the files/folders are listed for the root directory rather than a misleading placeholder.
Issue 2 (cd up):
- Click on the magnifying glass beside a profile in the USS tree
- Enter in a top-level directory as the directory to search (e.g., `/users`)
- Click the Up Arrow / "Go Up One Path" action button to go up a folder
- Notice that the path is updated to `/` and the results are …
> fix: allow listing root in USS, fix edge case w/ `cd ..`

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/fs/BaseProvider.unit.test.ts
- packages/zowe-explorer-api/src/fs/BaseProvider.ts
- packages/zowe-explorer/CHANGELOG.md
Fixes #3613 
- Try dragging and dropping a USS file from one folder to another while the Settings tab is open
- Notice that the operation succeeds and the node is moved
- _Previous behavior:_ Operation "succeeds" but uncaught exception occurs while updating node state
Changelog: 
**General**
**Deployment**
> fix: add optional chaining to tab input check

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
- packages/zowe-explorer/src/uss/USSTree.ts
Fixes an issue where the root directory cannot be listed. The previous RegEx expressions had inadvertently removed the `/` from the path, resulting in an empty string being set for the profile node's `fullPath` property.
Changelog:
- Fixed an issue where searching for the root directory (`/`) under a profile caused the profile to show a placeholder rather than a list of the files and folders at that path.
**General**
**Deployment**
- …
> fix(v2): Allow listing root directory under USS profile

- packages/zowe-explorer-api/__mocks__/vscode.ts
- packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableView.unit.test.ts
- packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/WebView.unit.test.ts
- packages/zowe-explorer-api/src/vscode/ui/WebView.ts
- packages/zowe-explorer/l10n/poeditor.json
- packages/zowe-explorer/package.json
- packages/zowe-explorer/package.nls.json
- packages/zowe-explorer/src/configuration/Constants.ts
- Renames `zowe.ds.paginate.datasetsPerPage` to `zowe.ds.paginate.dataSetsPerPage` so the right text is shown in the VS Code settings UI: "Data Sets Per Page"
- Follow-up to a recent change I made in an attempt to resolve #3619. Turns out I was missing one step where the disposables for the event listeners need added to the array of disposables, as `dispose` gets called when the view is re-initialized (e.g., table contents change).
Changelog: No changelog as we already have entries for pagination (not yet released) & the WebView change
**General**
**Deployment**
- If you're an outside contributor, please …
> `datasets` -> `dataSets`, fix event not being disposed

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__mocks__/vscode.ts
- packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
- packages/zowe-explorer-api/src/extend/IRegisterClient.ts
- packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__mocks__/vscode.ts
- packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerApiRegister.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/__snapshots__/ZoweUSSNode.unit.test.ts.snap
- packages/zowe-explorer/l10n/poeditor.json
- packages/zowe-explorer/src/extending/ZoweExplorerApiRegister.ts
- packages/zowe-explorer/src/trees/shared/SharedInit.ts
- packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Fixes #3622 
**Note:** this sample extension may modify credentials for your default z/OSMF profile. You may want to start with a fresh config file (`zowe config init --gc`) before continuing.
1. Checkout this branch locally and run `pnpm install && pnpm build && pnpm package`
2. Clone the sample extension linked in #3622 
3. In its `package.json`, update the `@zowe/zowe-explorer-api` dependency to point to the tarball built from step 1. Change its version from 3.1.0 to:
`file:<path-to-zowe-explorer-repo>/dist/zowe-zowe-explorer-api-3.2.0-refactor_move-onprofileupdated.tgz` 
4. Install dependencies and compile the sample extension: `npm install && npm run compile`
5. Run the command `vsce package`. Answer yes (y) to all prompts.
6. Once the sample extension is packaged, install it from …
> refactor: Move `onProfileUpdated` to API register, preserve access through getters

- packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
I tried to keep the behavior of returning `undefined` from previous data set logic as part of the paginator. However, the paginator expects items to be defined as part of its type definition.
This changes the behavior of `listDatasetsInRange` and `listMembersInRange` to return an empty list of items once we've caught and handled an error. This prevents undefined behavior by the paginator when an error is encountered while expanding a PDS or a profile. 
Changelog: No changelog as feature isn't yet available
**General**
**Deployment** …
> fix(ds): return empty list to paginator when request fails

- .github/workflows/merge-by-comments.yml
- .github/workflows/report-artifact-pr.yml
Why is the report vsix workflow failing on #3648 but not on #3646? 
This PR tests the theory that somehow opening a PR from a branch on a fork causes it to break.
After workflow run... it does indeed. Same error as the `merge_by` workflow on some of my past PR's.
This is because even though the workflow grants write permissions, the `GITHUB_TOKEN` [only has read permissions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token) when running based on the workflow file in the PR's fork branch. 
There's a few different ways to fix this, but only one that would actually work for this use case, and also the others aren't very mindful of security. 
- Create a fine-grained PAT, grant "Read and …
> Fix report artifact workflow failing on fork PR

- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/uss/init.ts
Fixed an issue where clicking the refresh icon beside a profile in the Unix System Services (USS) view had no effect.
Changelog:
- Fixed an issue where clicking the refresh icon beside a profile in the Unix System Services (USS) view had no effect.
**General**
> fix(v2): Allow profile node to be refreshed using its refresh action button

- packages/zowe-explorer-api/CHANGELOG.md
- packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
- packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
- packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/src/utils/TreeViewUtils.ts
Fixes #3772 and resolves multiple scenarios due to a `ZoweTreeNode.getProfile` regression in the Zowe Explorer API. The `loadNamedProfile` function was called outside of a try/catch block, causing exceptions from the function to be propagated to the caller/API consumer (breaking change).
If the user:
- deletes a profile from their team configuration
- renames a profile in the team configuration
- deletes the team configuration entirely
- renames the team configuration file
The matching profile node is not removed from any of the trees, because the Zowe Explorer core logic abruptly terminated due to the uncaught exception.
Changelog:
**General**
- **v3:** `pnpm --filter …
> fix(regression): Handle uncaught exception in `ZoweTreeNode.getProfile`

- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetTableView.ts
- packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
- packages/zowe-explorer/src/trees/uss/USSTree.ts
Fixes side effect from #3768 where pre-existing filters no longer show an input box to confirm submission.
- Search under a profile in Data Sets or USS tree
- Select an existing pattern
- Notice that you can use this pre-existing pattern as a template for a new pattern. This is currently not the case in `main` - clicking on a pre-existing filter would just submit the filter. I wanted to preserve this UX to avoid any perceived breaking changes.
Changelog: N/A (new UX hasn't been released yet)
**General**
**Deployment** …
> fix: allow editing existing DS/USS filters

- packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
- packages/zowe-explorer/CHANGELOG.md
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
- packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
- packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
- packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
- packages/zowe-explorer/src/utils/AuthUtils.ts
Fixes #3807  
Enable data set list pagination before trying these steps.
- Set invalid credentials on a profile
- Enter in a pattern in the data set filter prompt
- Encounter the auth prompt. Respond "Update Credentials" and enter new creds
- The auth prompt disappears and data sets are listed.
- Set invalid credentials on a profile
- Enter in a pattern in the data set filter prompt
- Encounter the auth prompt. Respond "Cancel"
- The auth prompt disappears and the profile shows "No data sets found".
- Refresh this profile and encounter the same prompt. Select "Cancel." 
- The prompt no longer re-appears until the user enters a new filter or refreshes the profile again. 
Milestone: 3.3.0 hopefully - if not 3.3.1
Changelog:
Fixed issue where the `getChildren` function made requests …
> fix(ds): Do not allow listing data sets while filter prompt is open
